### ISSUE TITLE
Pagination & search

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#111]

**Comment by trungdq88** [comment]
Anh @phucnguyen60749 review phần pagination và search nha, có lỗi thì comment và assign lại cho em.

**Comment by phucnguyen60749** [comment]
search chưa bắt khoảng trắng! chưa  trim()

**Comment by phucnguyen60749** [comment]
Pagination nếu đang ở trang đầu thì disable button "đầu" hoặc khi ở trang cuối disable button "cuối"

**Comment by trungdq88** [comment]
@phucnguyen60749 Review lại cho em nha.

**Comment by phucnguyen60749** [comment]
@trungdq88 
review search contract list bên customer
 - nhấn 1 chử cái ko khớp pagination xuất hiện chữ cuối nhấn vào thì ra trang 500
![untitled](https://cloud.githubusercontent.com/assets/12363394/8407921/8ad4cc7a-1e95-11e5-9c11-9d6d5d55a60e.png)

**Comment by phucnguyen60749** [comment]
![untitled](https://cloud.githubusercontent.com/assets/12363394/8407934/a248537c-1e95-11e5-9acd-f4e3a8bba25e.png)

**Comment by phucnguyen60749** [comment]
khi refresh trang nên xóa giá trị ngay field nhập

**Comment by trungdq88** [comment]
:+1: +1 tìm được bug 500.
Khi refresh trang thì không xoá giá trị đã nhập.

**Comment by phucnguyen60749** [comment]
vẫn còn Khi refresh trang thì không xoá giá trị đã nhập.
khi cố tình nhập sai giá trị search --> hiện paging số 1? nhấn vào thì load trang?
![untitled](https://cloud.githubusercontent.com/assets/12363394/8409887/1450b02c-1ea5-11e5-9e4d-84ad88646ede.png)

**Comment by phucnguyen60749** [comment]
1 trang nghĩa là sao! @trungdq88

**Comment by trungdq88** [comment]
Lúc refresh thì sẽ không xoá giá trị đã nhập, phải giữ lại để người dùng biết. Cho nên sẽ không sửa.

Lúc search ra 0 kết quả em đã đổi lại thành hiển thị thông báo.

Anh review tiếp nha.
