### ISSUE TITLE
<Staff> customer.jsp: Sửa lại các cột hiển thị cho phù hợp, sau đó sửa lại trong use case

### ISSUE THREAD

**Issue by hydrangea8604** [trungdq88/insurance-card#116]

**Comment by trungdq88** [comment]
Không thấy commit vào gắn với issue này?

**Comment by hydrangea8604** [comment]
Cái này lúc e làm pagination sửa mất rồi, giờ không còn cần sửa nữa.

**Comment by trungdq88** [comment]
Ok, lần sau close issue thì ghi rõ lý do giùm em nha.

**Comment by hydrangea8604** [comment]
Hôm qua nhìn nhầm, chưa sửa, reopen.

**Comment by hydrangea8604** [comment]
Đã sửa trong file .jsp, sửa document vào milestone sau.
