### ISSUE TITLE
<Staff> customer-detail.jsp: Sửa lại các cột hiển thị bảng Card cho phù hợp, sau đó sửa lại trong use case

### ISSUE THREAD

**Issue by hydrangea8604** [trungdq88/insurance-card#117]

**Comment by hydrangea8604** [comment]
Business change: card đi theo hợp đồng, vậy trong detail customer không có bảng card. Update lại document là đủ.

**Comment by trungdq88** [comment]
Anh ghi rõ đã update những chỗ nào trong document và gắn số issue này vào message khi commit hoặc copy link commit gắn vào đây nha.

**Comment by hydrangea8604** [comment]
Cái này a định tạo issue mới sửa một loạt document luôn.

**Comment by trungdq88** [comment]
Ok, lần sau nhớ ghi rõ lý do khi close.
