### ISSUE TITLE
Implement contract type list ở trang home.jsp

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#13]
Trong trang home.jsp, chỗ này phải load các contract type từ database lên.

                        <select class="form-control" name="ddlContractType">
                            <option value="1">Xe trên 50cc có tham gia BH tai nạn người trên xe</option>
                            <option value="2">Xe trên 50cc không tham gia BH tai nạn người trên xe</option>
                            <option value="3">Xe từ 50cc trở xuống có tham gia BH tai nạn người trên xe</option>
                            <option value="4">Xe từ 50cc trở xuống không tham gia BH tai nạn người trên xe</option>
                            <option value="5">Xe mô tô 3 bánh, xe gắn máy và các loại xe cơ giới tương tự</option>
                        </select>

**Comment by minhtridn2001** [comment]
Done!

**Comment by trungdq88** [comment]
Làm lại, load từ controller lên chứ không dùng taglib <sql:>. Không viết code business ở View.
