### ISSUE TITLE
[Client Validation] Public / Homepage

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#133]

**Comment by minhtridn2001** [comment]
@hydrangea8604 review giúp t nha

**Comment by hydrangea8604** [comment]
Tên: nên bắt ký tự đặt biệt !@#$%.
Số điện thoại có cái type là tel, nhiều người có thói quen nhập số điện thoại kèm dấu . VD: 0989.337.283
Ngày bắt đầu nên có max, nếu không nhập năm 3333 vẫn chấp nhận.
Nên đặt placeholder hiển thị ví dụ vào các field cần. Số điện thoại....

**Comment by trungdq88** [comment]
Confirm 09:48 PM June 21: chưa thấy sửa. Anh @minhtridn2001 sửa lại theo review của anh Kha nhé.

**Comment by minhtridn2001** [comment]
@hydrangea8604 T sửa rồi Kha review giúp nha. Cái ngày bắt đầu t ko set max vì có hỏi qua Trung và Thầy hôm nọ cũng nói thế nha :D

**Comment by hydrangea8604** [comment]
Đã review.
