### ISSUE TITLE
[Client Validation] Public / Register page

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#134]

**Comment by minhtridn2001** [comment]
@hydrangea8604  K review giúp nha!

**Comment by hydrangea8604** [comment]
---- Tab 1 ----
Địa chỉ nên có geolocation luôn, nếu chẳng may người dùng muốn thay đổi địa chỉ ở đây.
Thời hạn bảo hiểm: 01 năm hoặc đưa lên cùng dòng, hoặc để dưới thì viết dài ra "01 năm kể từ ngày..."
Họ tên để col-sm-4, cùng hàng với email col-sm-6
Địa chỉ (col-sm-7) dài hơn email nên đưa xuống dưới cùng hàng với số điện thoại (col-sm-3).
Ngày bắt đầu đưa ra trước số cmnd/ hộ chiếu
---- Tab 2 ----
Placeholder nên sửa lại thành ví dụ giá trị cần nhập.
Biển số có thể nhập toàn số và ký tự đặt biệt, hình như biển số luôn luôn có chữ và không có ký tự đặc biệt.
Số khung, số máy cũng luôn có chữ (http://vietbao.vn/O-to-xe-may/So-khung-xe-VIN/61000336/388/)
Dung tích luôn có số, có thể có chữ cc hoặc không.
Loại xe luôn có chữ.
Màu sơn chỉ có chữ.
Placeholder của tự trọng và số người không đọc được với màn hình bề ngang 1000px.
Trang thanh toán, khi chọn trực tiếp, bản đồ bị vượt khung, lấn xuống footer.
Trang hiển thị thông báo "Bạn đã hủy thanh toán." Có thêm hướng dẫn gì đó, ví dụ tài khoản đã được tạo hay đã bị xóa, làm thế nào để thanh toán lại, link để đăng nhập...

**Comment by trungdq88** [comment]
@hydrangea8604 thanks. Review rất chi tiết.

Một số chi tiết có thể bỏ qua:
- **Pattern cho các field biển số, số khung, số máy, dung tích...**: không cần validate quá kỹ như anh Kha mô tả, validate required và độ dài là đủ.
- **Bản đồ bị vượt khung, lấn xuống footer.**: lỗi giao diện, không liên quan đến milestone Client side validation. Tạo issue khác.

Bây giờ là 09:38 PM June 21, em thống kê lại các lỗi chưa sửa từ review của anh Kha. Anh Trí sửa lại rồi commit nhé:
1. Ở Tab 1: Địa chỉ nên có geolocation luôn, nếu chẳng may người dùng muốn thay đổi địa chỉ ở đây.
2. Ở Tab 1: Thời hạn bảo hiểm: 01 năm hoặc đưa lên cùng dòng, hoặc để dưới thì viết dài ra "01 năm kể từ ngày...". Họ tên để col-sm-4, cùng hàng với email col-sm-6. Địa chỉ (col-sm-7) dài hơn email nên đưa xuống dưới cùng hàng với số điện thoại (col-sm-3).
3. Ở Tab 1: Ngày bắt đầu đưa ra trước số cmnd/ hộ chiếu
4. Ở Tab 2: Placeholder nên sửa lại thành ví dụ giá trị cần nhập.
5. Ở trang checkout: Trang hiển thị thông báo "Bạn đã hủy thanh toán." Có thêm hướng dẫn gì đó, ví dụ tài khoản đã được tạo hay đã bị xóa, làm thế nào để thanh toán lại, link để đăng nhập...

**Comment by minhtridn2001** [comment]
OK cám ơn 2 bạn :D

**Comment by minhtridn2001** [comment]
@hydrangea8604 T fix theo review Của Kha rồi. Còn lại cái phần trang Cancel payment do nằm ngoài phần validation nên t tạo issue khác. Do đó là trang dùng chung của nhiều payment nên t ko có để message chi tiết như vậy :D Sẽ sửa lại

**Comment by hydrangea8604** [comment]
Đã review
