### ISSUE TITLE
[Client Validation] Staff / Create contract

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#135]

**Comment by hydrangea8604** [comment]
@phucnguyen60749 Review dùm với nha, nếu có lỗi thì assign lại, không có thì close luôn :+1:

**Comment by phucnguyen60749** [comment]
- nếu chọn thời đểm có hiệu lực và thời đểm hệt hiệu lực cùng ngày -> vẫn accept?
- số máy, số khung, dung tích: nếu chỉ nhập chử -> vẫn accpet-> submit lỗi
- submit tạo mới hợp đồng-> error

**Comment by hydrangea8604** [comment]
Có thể đưa hình lỗi không? Nhiều khả năng lỗi là nhập mã khách hàng không tồn tại trong database. Chứ bên này tạo mới bình thường.
Số máy, số khung, dung tích là String. Mà để viết thêm pattern bắt luôn.

**Comment by hydrangea8604** [comment]
@phucnguyen60749 Review lại lần nữa dùm nha

**Comment by trungdq88** [comment]
1. Chỗ chọn ngày tháng "thời điểm hiệu lực": minimum = cách đây 1 tuần, business này từ đâu ra vậy? Trong use case có nhắc đến hay không? Tại sao lại là 1 tuần? Sao không phải là 2, 3 tuần? Tương tự với ngày nộp phí. (Thảo luận bổ sung business chỗ này?)
2. Nếu để "Thời điểm có hiệu lực" với "Thời điểm hết hiệu lực" bằng nhau thì không ổn lắm. Chỗ này nên thảo luận có nên bổ sung business **hợp đồng ký kết tối thiểu phải là 1 tháng** (mặc dù theo luật là bắt buộc phải 1 năm).
3. Phí bảo hiểm chưa tự động tính theo thời hạn bảo hiểm?
4. Nhấn F12, bật qua tab console. Mỗi lần nhấn submit thì có lỗi javascript xuất hiện "control with name='' is not focusable.". Có thể sửa được không?
![screenshot 2015-06-21 20 54 00](https://cloud.githubusercontent.com/assets/4214509/8271876/0874e488-1858-11e5-9b3a-e5a1ce6b0114.png)
5. Lúc tạo hợp đồng xong, chỗ review không thấy tên khách hàng?
![screenshot 2015-06-21 20 56 10](https://cloud.githubusercontent.com/assets/4214509/8271871/019152be-1858-11e5-8540-9621d5537089.png)

**Comment by hydrangea8604** [comment]
Đã xử lý theo review. Thêm issue #146 ngày bắt đầu và ngày kết thúc xử lý sau. Tên khách hàng đã xử lý ở issue #145

**Comment by trungdq88** [comment]
Đã review ✅
