### ISSUE TITLE
[Client Validation] Staff / Renew contract

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#136]

**Comment by hydrangea8604** [comment]
@phucnguyen60749 Review plz. Tks

**Comment by phucnguyen60749** [comment]
- ngày gia hạn đến, ngày nộp phí: có thể edit?

**Comment by hydrangea8604** [comment]
Staff mà, cho phép edit trong giới hạn.

**Comment by trungdq88** [comment]
1. Tính phí gia hạn dựa trên số ngày gia hạn.
2. Ngày nộp phí: tại sao minimum lại cách đây 1 tuần? (Bổ sung business?)
3. Lỗi javascript khi validate sai.

**Comment by hydrangea8604** [comment]
Đã sửa theo review, review lại lần nữa dùm nha.

**Comment by minhtridn2001** [comment]
@hydrangea8604 Ngày nộp phí ko validate hả Kha? Với khi click vào Ngày nộp phí thì Phí gia hạn bị thay đổi.

**Comment by minhtridn2001** [comment]
Ngày Gia hạn đến phải sau ngày kết thúc hợp đồng. Hiện tại Kha đang validate ngày Gia hạn đến là sau current date.

**Comment by hydrangea8604** [comment]
Ngày nộp phí ko validate
Đã sửa click vào Ngày nộp phí thì Phí gia hạn bị thay đổi.
Đã sửa ngày gia hạn sau ngày kết thúc hợp đồng.

**Comment by trungdq88** [comment]
Đã review ✅
