### ISSUE TITLE
[Client Validation] Staff / Cancel contract

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#137]

**Comment by hydrangea8604** [comment]
@phucnguyen60749 Review plz. Tks

**Comment by phucnguyen60749** [comment]
- thông báo của validation thêm tiếng việt ở dưới
- hợp đồng staff đã cancel có nút button "hủy yêu cầu" để hủy yêu cầu "hủy hợp đồng không"
- ngày hủy hợp đồng sao lại cho thay đổi
- lý do hủy hợp đồng: nếu chỉ nhập số vẫn accept

**Comment by hydrangea8604** [comment]
- Thông báo của validation để trình duyệt tiếng Việt sẽ thành tiếng Việt. Một số form input type như number hay date để title sẽ không hiển thị rõ ràng thông báo trong từng trường hợp mà chỉ hiển thị title.
- Nút từ chối hủy hợp đồng theo yêu cầu của Customer chưa cần làm.
- Ngày hủy hợp đồng đương nhiên cho đổi. VD: Khách hủy hôm qua mà cúp điện, hôm nay mới làm được. Staff mà, cố gắng cho business đáp ứng tốt nhất, Customer mới phải cố gắng hạn chế nhập liệu.
- Lý do mà, muốn nhập cái gì thì nhập, không quá 255 ký tự là được. VD có thể nhập cái số điện thoại vào, cần gì liên lạc.

**Comment by trungdq88** [comment]
1. Tại sao ngày huỷ hợp đồng lại có minimum = cách đây 1 tuần?
2. Lỗi javascript khi validate.
