### ISSUE TITLE
[Client Validation] Customer / Renew contract

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#138]

**Comment by trungdq88** [comment]
Hiển thị thông tin loại hợp đồng ở popup Gia hạn. (Chỉ hiển thị, không cho phép edit)

**Comment by trungdq88** [comment]
- [ ] Đưa thông tin loại hợp đồng lên đầu tiên.
- [ ] Nếu trạng thái hợp đồng là "No card" thì field "Gia hạn đến" không hiển thị.

**Comment by trungdq88** [comment]
Chỗ này sao lại dùng session để lưu status cũ? Lúc tắt trình duyệt thì session bị huỷ mà?! 

```java
    String oldStatus = contractOld.getStatus();
    HttpSession session = r.equest.getSession();
```

Làm đúng thì phải thế này: sau khi nhấn nút "Huỷ yêu cầu" (tức là trạng thái đang là "Request cancel"), thì lúc này phải **tính toán** lại trạng thái của hợp đồng.

- Nếu không có card nào gắn với hợp đồng: status = "No card".
- Nếu hợp đồng chưa hết hạn: status = "Ready".
- Nếu hợp đồng hết hạn: status = "Expired".

**Comment by hydrangea8604** [comment]
No Card field gia hạn đến vẫn chưa hiển thị.
Khi gia hạn thì phí gia hạn là lấy từ bảng contractType chứ. Lấy contractFee cũ sao được, lỡ công ty thay đổi phí hợp đồng thì sao? Customer cả đời dùng bảo hiểm chỉ có 1 giá.

**Comment by phucnguyen60749** [comment]
sữa db của ong lai thành No card ngen

**Comment by trungdq88** [comment]
Đã review ✅
