### ISSUE TITLE
[Client Validation] Customer / Request contract cancel

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#139]

**Comment by trungdq88** [comment]
- Bỏ dấu chấm than ở cuối mỗi câu đi.
- Bỏ bớt chữ "Cảnh báo!" ở thông báo lỗi đi.

**Comment by minhtridn2001** [comment]
Sau khi click Hủy yêu cầu hủy hợp đồng trước đó. Tình trạng hợp đồng luôn là Ready. Mặc dù trước đó là Expired,...

**Comment by trungdq88** [comment]
Chỗ này sao lại dùng session để lưu status cũ? Lúc tắt trình duyệt thì session bị huỷ mà?! 

```java
    String oldStatus = contractOld.getStatus();
    HttpSession session = r.equest.getSession();
```

Làm đúng thì phải thế này: sau khi nhấn nút "Huỷ yêu cầu" (tức là trạng thái đang là "Request cancel"), thì lúc này phải **tính toán** lại trạng thái của hợp đồng.

- Nếu không có card nào gắn với hợp đồng: status = "No card".
- Nếu hợp đồng chưa hết hạn: status = "Ready".
- Nếu hợp đồng hết hạn: status = "Expired".

**Comment by hydrangea8604** [comment]
Khi chọn lý do khác, nhập lý do, bấm vào Đồng ý vẫn hiện alert ở trên, sau đó lại chấp nhận gởi yêu cầu. Không thể dùng required ở đây hả? Hiện cái thông báo lên gây hiểu nhầm.
Sau khi gởi yêu cầu hủy thì nên hiển thị thông tin hủy hợp đồng: ngày hủy, lý do. Trạng thái là cancelled thì có thêm ghi chú hủy từ Staff.

**Comment by trungdq88** [comment]
Đã review ✅

**Comment by minhtridn2001** [comment]
@phucnguyen60749 Trường hợp hợp đồng có status là Pending. Khi hủy yêu cầu Hủy hợp đồng bị exception.

**Comment by trungdq88** [comment]
@minhtridn2001 nếu hợp đồng mà ở trạng thái Pending thì đáng lẽ sẽ không dùng được nút "Gia hạn" và "Huỷ hợp đồng". Xem issue #91 
Nhưng mà chỗ nào bị quăng exception thì đúng là không hay thật, anh @phucnguyen60749 fix cái exception nha.

**Comment by trungdq88** [comment]
@minhtridn2001 em không tái tạo bug được, không thấy exception gì cả, chỉ là sau khi huỷ yêu cầu thì status bị đổi về No Card (sai).
Anh có hình không?

**Comment by minhtridn2001** [comment]
![image](https://cloud.githubusercontent.com/assets/12363317/8340361/28eaffb2-1ae8-11e5-8b22-f60dc181752b.png)

Ah lỗi này là do trong database, cái hợp đồng này có 2 card deactivedDate = NULL.

![image](https://cloud.githubusercontent.com/assets/12363317/8340403/711d2a76-1ae8-11e5-92e3-985347daf1c1.png)

Là do lỗi Database sai, mà ko biết nên bắt exception chỗ này ko e nhỉ?
