### ISSUE TITLE
<<Customer>>

### ISSUE THREAD

**Issue by phucnguyen60749** [trungdq88/insurance-card#141]
review validation of contract belong to customer :renew and cancel contract

**Comment by minhtridn2001** [comment]
Phần Renew contract thì trừ những hợp đồng Ready ra, còn lại bị lỗi ko hiện số tiền và nội dung thanh toán.
Phần Cancel contract thì lỗi phải hiển thị trực tiếp trên trang jsp luôn. Dùng Validator HTML5 luôn cho đồng bộ nha Phúc.
