### ISSUE TITLE
Lỗi trạng thái của contract khi Customer hủy yêu cầu hủy hợp đồng

### ISSUE THREAD

**Issue by minhtridn2001** [trungdq88/insurance-card#144]
Sau khi click Hủy yêu cầu hủy hợp đồng trước đó. Tình trạng hợp đồng luôn là Ready. Mặc dù trước đó là Expired,Pending,No Card,...

**Comment by trungdq88** [comment]
👍 Phát hiện lỗi nghiêm trọng. Anh @phucnguyen60749 hotfix luôn nha.

**Comment by trungdq88** [comment]
Close this issue because duplicate with #139
