### ISSUE TITLE
<Staff> Trang chi tiết hợp đồng: đổi label và thứ tự hiển thị

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#147]
![screenshot 2015-06-22 20 58 50](https://cloud.githubusercontent.com/assets/4214509/8283506/e515db76-1921-11e5-8796-1d3078cad4d4.png)

**Comment by hydrangea8604** [comment]
Không phải sai đâu Trung, thời hạn hợp đồng tối đa là 1 năm, nên tính thời hạn còn lại là lấy ngày hết hạn trừ ngày hiện tại. Trên đó là tháng 7 hợp đồng mới có hiệu lực, tính ra số ngày thì đúng rồi.

**Comment by trungdq88** [comment]
Nếu vậy cần phải đưa field này xuống dưới và đổi tên lại thành "Thời gian đến ngày hết hạn" để khỏi hiểu nhầm.

- Thời điểm có hiệu lực:
- Thời điểm hết hiệu lực:
- Thời gian đến ngày hết hạn:

**Comment by trungdq88** [comment]
Lỗi nhỏ nên em đổi trong issue này luôn, khỏi tạo issue mới.

**Comment by hydrangea8604** [comment]
Ok, got it

**Comment by trungdq88** [comment]
Đã review :tada:
