### ISSUE TITLE
<Staff> contract-detail.jsp Hoàn thiện nội dung trang

### ISSUE THREAD

**Issue by hydrangea8604** [trungdq88/insurance-card#150]

**Comment by hydrangea8604** [comment]
Đã sửa hiển thị thông tin ở issue khác, đã hoàn thiện phần trong core flow. Giữ issue để hoàn thiện phần compensations, accidents và punishments

**Comment by trungdq88** [comment]
Issue chung chung quá. Close.
Sau này sẽ tạo issue khác cho từng chức năng cụ thể hơn.
