### ISSUE TITLE
<Customer> Implement server side validation

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#154]
- [x] Customer/ContractController#getContractDetail(): nếu contract code không tồn tại thì trả về 404
- [x] Customer/ContractController#postCancelContract(): validate DTO
- [x] Customer/ContractController#getActiveNewContract(): session không tồn tại => 404
- [x] Customer/ContractController#postRejectRequestCancel(): contract code không tồn tại => 404

**Comment by phucnguyen60749** [comment]
kha ơi review giúp

**Comment by phucnguyen60749** [comment]
tri oi review giup <Customer> Implement server side validation #154

**Comment by minhtridn2001** [comment]
- Customer/ContractController#postCancelContract(): validate DTO : dù chọn lý do hủy hợp đồng hay không chọn thì cũng thông báo lỗi "Lý do hủy hợp đồng không được để trống" => ko hủy được hợp đồng. Lần sau P test qua trước nhé.

 Customer/ContractController#getActiveNewContract(): session không tồn tại => 404 
getSession(true) sẽ tự tạo mới session nếu chưa có. Cho nên session chỗ này ko bao giờ null được.
```
 HttpSession session = r.equest.getSession(true);
        if(session == null){
            return new RedirectTo("/error/404");
        }
``` 

- Customer/ContractController#getContractDetail(): nếu contract code không tồn tại thì trả về 404 [đã review OK]
- Customer/ContractController#postRejectRequestCancel(): contract code không tồn tại => 404  [đã review OK]

**Comment by phucnguyen60749** [comment]
alo tri! Customer/ContractController#postCancelContract(): validate DTO : dù chọn lý do hủy hợp đồng hay không chọn thì cũng thông báo lỗi "Lý do hủy hợp đồng không được để trống" => ko hủy được hợp đồng. Lần sau P test qua trước nhé
--> Trí có thể mô tả cách trí test ko! chứ cái này P test qua trước rồi mới đưa trí review chứ :)

**Comment by minhtridn2001** [comment]
Tự nhiên comment ai biết mà bỏ @@

**Comment by minhtridn2001** [comment]
Phúc sửa xong hết commit lại rồi t review lần nữa

**Comment by minhtridn2001** [comment]
Customer/ContractController#postCancelContract(): validate DTO
Chọn lý do khác thì ko hủy hợp đồng đc P ơi. Luôn bị bắt lỗi Lý do hủy hợp đồng không được để trống

**Comment by phucnguyen60749** [comment]
trí bỏ comment ben customer.js la dc
