### ISSUE TITLE
<Public> Implement server side validation

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#155]
- [ ] Public/RegisterController#postRegister(): validate DTO
- [ ] Public/RegisterController#postCreateContract(): validate DTO
- [ ] Public/RegisterController#getActiveContract(): validate session không tồn tại => 404

**Comment by minhtridn2001** [comment]
@hydrangea8604 Kha review giúp t với nha.

**Comment by hydrangea8604** [comment]
Bổ sung theo: https://www.facebook.com/groups/insurancecard/permalink/876101855758756/
Bổ sung theo: #157
Có cách nào tách hiển thị lỗi ở trang register không? Hiện tại lỗi khi nhập thông tin xe đều hiện ở tab thông tin cá nhân.

**Comment by minhtridn2001** [comment]
Tạm thời t hiển thị lỗi ở cả 2 Tab luôn.
