### ISSUE TITLE
<Staff> Implement server side validation

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#156]
- [ ] Staff/ContractController#postRenew: validate DTO
- [ ] Staff/ContractController#postCancel: validate DTO
- [ ] Staff/CustomerController#getDetail: validate customerCode không tồn tại => 404
- [ ] Staff/CustomerController#postCreate: validate DTO

**Comment by hydrangea8604** [comment]
Phúc review dùm nha, nhớ thêm novalidation.
Renew và cancel contract bởi vì hiện popup nên chỉ hiển thị lỗi, không dùng submitted để hiển thị giá trị đã nhập (đã confirm với Trung)

**Comment by phucnguyen60749** [comment]
Staff/ContractController#postCancel: validate DTO:
      -   lý do hủy : chưa validate nếu nhập khoảng trắng
      -   sau khi nhập sai chọn hủy hợp đồng: cái đường link http://localhost:8080/staff/contract ?
      -  thời đểm hủy: có thể modify tùy ý. vd có thể chọn 25/06/1951? 
    
Staff/ContractController#postRenew: validate DTO
     -   ngày nộp phí : có thể modify tùy ý. vd có thể chọn 25/06/1951? 
Staff/CustomerController#postCreate: validate DTO
    -   ngày nộp phí : có thể modify tùy ý. vd có thể chọn 25/06/1951?

**Comment by hydrangea8604** [comment]
Lý do hủy: #157
Đường link sau khi validate fail, trả về là do bên này nó vậy, đã confirm với Trung.
Thời điểm hủy, ngày nộp phí (renew, cancel) đã vote trên facebook là không giới hạn. https://www.facebook.com/groups/insurancecard/permalink/874226959279579/

**Comment by phucnguyen60749** [comment]
còn cái vụ nhập khoảng trắng! khi cancel contract?
