### ISSUE TITLE
Implement password encryption

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#161]

**Comment by trungdq88** [comment]
Các test case:

- [ ] Public/Register tạo hợp đồng mới, vào email nhận pass và đăng nhập thành công.
- [ ] Public/Register tạo hợp đồng mới, gửi lại email (sẽ sinh pass mới), nhận mail thứ 2, đăng nhập thành công.
- [ ] Staff tạo khách hàng mới, vào email nhận pass và đăng nhập thành công.
- [ ] Staff tạo khách hàng mới, gửi lại email (sẽ sinh pass mới), nhận mail thứ 2, đăng nhập thành công.
- [ ] Customer đăng nhập, đổi mật khẩu, đăng nhập thành công với mật khẩu mới.
- [ ] Mở database bảng customer và staff, kiểm tra mật khẩu có được mã hoá hay không.

**Comment by trungdq88** [comment]
Anh @phucnguyen60749 xem các test case và review nhé.
Review cẩn thận giùm em, lần trước cái issue email template em làm bị thiếu phần email template cho staff/create customer mà anh không phát hiện ra đó.

**Comment by phucnguyen60749** [comment]
@hydrangea8604  review dùm nhé! co fix lổi của trung lun

**Comment by trungdq88** [comment]
Review lâu quá anh ơi, 4 ngày rồi kể từ khi được assign.

**Comment by phucnguyen60749** [comment]
đã review
