### ISSUE TITLE
Fix: tuyệt đối không được session.invalidate(); ở bất kỳ đâu

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#162]
Lý do:
Session được dùng ở nhiều nơi với nhiều mục đích khác nhau, invalidate ở một nơi sẽ xoá toàn bộ session và làm ảnh hưởng đến tất cả những nơi khác. Cụ thể là phần đăng nhập.

**Comment by minhtridn2001** [comment]
Đã đổi thành session.removeAttribute(...)
