### ISSUE TITLE
<Guest> register.jsp THÔNG TIN HỢP ĐỒNG BẢO HIỂM: Sửa lại các label và title

### ISSUE THREAD

**Issue by hydrangea8604** [trungdq88/insurance-card#163]
Thay đổi thứ tự hiển thị thông tin lại như lúc nhập.
Địa chỉ nên để nguyên 1 dòng.
Email chỉnh lại cho ngang bằng với các label dưới.

**Comment by trungdq88** [comment]
Đã review ✅
