### ISSUE TITLE
<Staff> Create customer: implements Form Reader, client-side & server-side validation. Generate password and send email

### ISSUE THREAD

**Issue by hydrangea8604** [trungdq88/insurance-card#164]

**Comment by trungdq88** [comment]
Lúc tạo tài khoản thì cũng phải generate mật khẩu random. Dùng hàm `StringUtils.randomString()`, lúc create xong thì gửi mail mật khẩu đến khách hàng, xem `RegisterBusiness.java#registerNewContract` để xem cách gửi mail.

**Comment by trungdq88** [comment]
Đã review :gem:
