### ISSUE TITLE
Field receiver trong bảng Payment không phải lưu tên staff mà là lưu mã số staff và phải có khoá ngoại qua bảng Staff

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#167]
Các chỗ cần sửa:
- [x] Thêm khoá ngoại trong database: @minhtridn2001 
- [x] Chỉnh sửa entity (sau khi xong database): @trungdq88
- [x] Chỉnh sửa code phần lưu xuống và hiển thị: @hydrangea8604 

Issue này assign trước cho anh @minhtridn2001, anh Trí làm xong thì assign lại cho @trungdq88, sau đó đến @hydrangea8604.

**Comment by minhtridn2001** [comment]
Đã thêm khóa ngoại trong database.

**Comment by trungdq88** [comment]
Đã sửa entity :+1:

**Comment by trungdq88** [comment]
Hiển thị chưa đúng.
Cần hiển thị tên của staff kèm link tới trang detail của staff (tạm thời có thể gắn link giả)

**Comment by hydrangea8604** [comment]
Ủa sao nó ra số vậy ta :(
![image](https://cloud.githubusercontent.com/assets/12366868/8390716/1094677c-1cce-11e5-861c-f83852ea2be7.png)

**Comment by trungdq88** [comment]
À.. đúng rồi.
Tại staff bên em tên là "1". Sorry.
Close :tada:
