### ISSUE TITLE
Thêm nút gửi lại email cho phần register và create customer

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#174]

**Comment by trungdq88** [comment]
@phucnguyen60749  review giúp em nhé.

**Comment by minhtridn2001** [comment]
Chức năng gửi lại email ok rồi. Mà email a nhận được bị lỗi tiếng Việt như này nè
![image](https://cloud.githubusercontent.com/assets/12363317/8412536/aa8e30aa-1eb4-11e5-8014-89ef46555888.png)

**Comment by hydrangea8604** [comment]
Assign cho t làm gì thế?

**Comment by trungdq88** [comment]
Issue này là em làm, anh Phúc review. Không hiểu sao anh Phúc lại assign cho anh Kha?
Anh Trí đã review rồi thì có thể close.
Về lỗi font trong email: #200.

**Comment by minhtridn2001** [comment]
Phúc nhờ a review mà assign nhầm Kha thôi

**Comment by trungdq88** [comment]
Ok
