### ISSUE TITLE
<Customer> trang contract detail: ngày tham gia và ngày hết hạn: hiển thị thêm giờ.

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#177]
Ví dụ:

- Ngày tham gia: 28/06/2015 lúc 5:21:19 AM
- Ngày hết hạn: 28/06/2016 lúc 5:21:19 AM

**Comment by phucnguyen60749** [comment]
@hydrangea8604 review dum nhe!

**Comment by hydrangea8604** [comment]
Mặc dù chưa đúng ví dụ lắm nhưng cũng đã hiển thị. Tạo issue mới để chỉnh sửa về giao diện.
