### ISSUE TITLE
<Customer> Kiểm tra ràng buộc khi gia hạn hợp đồng: thời gian còn lại phải ít hơn 2 tháng.

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#179]
Nếu thời gian còn lại nhiều hơn thì hiện thông báo lỗi.

**Comment by phucnguyen60749** [comment]
@hydrangea8604 review dùm nhé

**Comment by hydrangea8604** [comment]
Trong commit không thấy code validate server-side?

**Comment by trungdq88** [comment]
https://github.com/trungdq88/insurance-card/commit/a7fac4aa2dbb5a4de3ae63502a8406dd0ac50d7d

**Comment by trungdq88** [comment]
Anh Kha review lại giùm.

**Comment by hydrangea8604** [comment]
Đã review :+1:
