### ISSUE TITLE
<Staff> Kiểm tra ràng buộc khi gia hạn hợp đồng: thời gian còn lại phải ít hơn 2 tháng.

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#180]
Nếu thời gian còn lại nhiều hơn thì hiện thông báo lỗi.

**Comment by hydrangea8604** [comment]
Hôm trước có nói vụ này với Trung, Trung nói là chỉ cần hiển thị thông báo cho người dùng biết là được, giờ thành không cho gia hạn luôn hả?

**Comment by trungdq88** [comment]
Nhưng hiện tại là có thông báo gì không anh? 
Về chuyện staff có được quyền đặt ngày tuỳ ý hay không thì chắc tới thứ 3 mình hỏi thầy lại cho chắc. 
Giờ anh cứ làm là không cho gia hạn đi.

**Comment by hydrangea8604** [comment]
Có thông báo, nếu thời hạn hợp đồng còn hơn 2 tháng thì hiện thông báo này
![image](https://cloud.githubusercontent.com/assets/12366868/8396631/a91fb20c-1dd8-11e5-94c8-073b093c96f8.png)
Còn nếu dưới 2 tháng hoặc đã hết hạn thì không hiện thông báo gì cả.
![image](https://cloud.githubusercontent.com/assets/12366868/8396634/bcc5de44-1dd8-11e5-9334-7194fb9ddcda.png)

**Comment by trungdq88** [comment]
Ồ ra đó là cái thông báo, anh để như vậy khiến em nhầm lẫn là lúc nào nó cũng hiện ra số ngày còn lại.
Bây giờ anh cho hiện thêm câu giải thích "Bạn không thể gia hạn hợp đồng còn giá trị trên 2 tháng" và disable các nút đi. Nhớ validate cả ở server.

**Comment by hydrangea8604** [comment]
@minhtridn2001 Review dùm nha Trí

**Comment by minhtridn2001** [comment]
Trường hợp này sai nè. Min max ngày gia hạn đến được tính từ ngày expired date
![image](https://cloud.githubusercontent.com/assets/12363317/8397565/56f8ea3a-1dfa-11e5-8d24-cb5df267f653.png)

**Comment by hydrangea8604** [comment]
Là do dummy database sai đó. Hợp đồng hết hạn ngày 1/1/2015 thì trạng thái hợp đồng phải là Expired mới đúng.
