### ISSUE TITLE
<Staff> bỏ các badge (notification) trên side bar

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#182]
Nhìn số giả rất rối mắt.

**Comment by hydrangea8604** [comment]
@phucnguyen60749 Nhỏ nhưng cũng review cho đúng quy trình dùm nha.

**Comment by minhtridn2001** [comment]
Cái side bar Trung nói là ở đâu? Trên trang thông tin chung hay sao K?

**Comment by hydrangea8604** [comment]
Không, bên thanh navigation bar, Khách hàng, Thẻ hiện hành, Hợp đồng đó. Bỏ mấy con số giả đi thôi, thấy không còn nữa thì close là được.
