### ISSUE TITLE
[Staff] Renew contract chưa validate startDate bên phía server

### ISSUE THREAD

**Issue by minhtridn2001** [trungdq88/insurance-card#183]
Khi gia hạn, nếu đã validate expiredDate không quá startDate 1 năm thì cũng phải validate luôn startDate. Vì startDate bên client có thể chỉnh sửa được và khi renew thì sẽ không chỉnh sửa ngày start date trên database nữa.

**Comment by hydrangea8604** [comment]
Khi renew, startDate bên client đâu chỉnh sửa được? Truyền startDate vào DTO để tính thời hạn hợp đồng thôi chứ không làm gì khác. Cũng đâu có chỉnh sửa ngày startDate trên database.

**Comment by minhtridn2001** [comment]
Người dùng bấm F12 chỉnh startDate rồi renew vẫn được mà. Như vậy có thể set expiredDate khi nào cũng được.

**Comment by hydrangea8604** [comment]
Thử mô tả cách test hoặc cho tấm hình được không @minhtridn2001

**Comment by trungdq88** [comment]
Bug report rất chính xác.
Như đã nói ở trong milestone server validate, phải implement tất cả các validation mà có ở client thì server cũng phải có.

**Comment by hydrangea8604** [comment]
Vẫn không hiểu.
Inspect element là không có value, 
![image](https://cloud.githubusercontent.com/assets/12366868/8396677/e9e6eaa2-1dd9-11e5-86fe-1d1d845c8557.png)
Tự thêm attribute
![image](https://cloud.githubusercontent.com/assets/12366868/8396681/186211b8-1dda-11e5-9b5e-f850c6115071.png)
Bấm gia hạn thì nó vẫn lấy value đi kèm theo input mà, nó đâu có nhận value nhập vào?

**Comment by trungdq88** [comment]
Anh có thể xoá thuộc tính min và max đi, sau đó chọn value bậy bạ và submit.

**Comment by hydrangea8604** [comment]
@phucnguyen60749 Review lại dùm nha

**Comment by hydrangea8604** [comment]
Validate thiếu.

**Comment by hydrangea8604** [comment]
@minhtridn2001 Review dùm nha, chú ý thời gian và trạng thái của hợp đồng.

**Comment by minhtridn2001** [comment]
Kha ơi xem lại chỗ so sánh giờ nha. Thêm giờ phút vào thì ko gia hạn được. @hydrangea8604 
![image](https://cloud.githubusercontent.com/assets/12363317/8409798/96c54f3c-1ea4-11e5-8b9b-5fb7fc125520.png)

**Comment by hydrangea8604** [comment]
Mò sâu quá @@

**Comment by hydrangea8604** [comment]
Thêm giờ phút vào cái renew:startDate đó hả? Thêm vào thì không đúng giờ trong hợp đồng, nó báo lỗi là "Ngày bắt đầu gia hạn hợp đồng không đúng"?

**Comment by minhtridn2001** [comment]
@hydrangea8604 Thêm giờ phút vào expiredDate trong database đó

**Comment by hydrangea8604** [comment]
@minhtridn2001 Hehe, giờ cho ông khỏi F12 luôn, review lại dùm lần nữa (hi vọng là lần cuối) nha.

**Comment by minhtridn2001** [comment]
Done! Mai nhớ sửa phần giờ phút nha :D
