### ISSUE TITLE
<Customer> Renew contract. Expired date sai khi renew các contract khác "Ready" và "Expired"

### ISSUE THREAD

**Issue by minhtridn2001** [trungdq88/insurance-card#184]

**Comment by phucnguyen60749** [comment]
sai sao trí! 
- ví dụ no card thì ngày gia hạn = ngày expired + 1 năm mà

**Comment by minhtridn2001** [comment]
Trong hàm postRenewContract của Phúc bắt thiếu TH. Nên contract những status khác sẽ ko update expiredDate. Phúc kiểm tra lại Database mà xem:
```
Timestamp expiredDate = contract.getExpiredDate();
        if (contract.getStatus().equalsIgnoreCase(Constants.ContractStatus.READY)) {
            expiredDate = DateUtils.addOneYear(expiredDate);
        } else if (contract.getStatus().equalsIgnoreCase(Constants.ContractStatus.EXPIRED)) {
            expiredDate = DateUtils.addOneYear(new Timestamp(date.getTime()));
        }
```

**Comment by minhtridn2001** [comment]
@phucnguyen60749  sao chưa review đã closed rồi Phúc. Vẫn chưa được kìa. Còn thiếu những trường hợp khác nữa, ví dụ: request cancel, pending.... Phải bắt full TH chứ

**Comment by phucnguyen60749** [comment]
@minhtridn2001  p wen assign review cái này! sr!  request cancel, pending có renew contract ko nhi??? check lại kĩ nay nha trí

**Comment by phucnguyen60749** [comment]
@hydrangea8604  review dùm kha oi

**Comment by minhtridn2001** [comment]
@phucnguyen60749 Những TH còn lại P ko bắt thì nó vẫn thanh toán nhưng ko update status thôi. Phía server ko validate chặn những contract status còn lại mà

**Comment by trungdq88** [comment]
Anh @minhtridn2001 review lại giùm.

**Comment by minhtridn2001** [comment]
Đã review :+1:
