### ISSUE TITLE
<Staff> navigation bar: implements các badges

### ISSUE THREAD

**Issue by hydrangea8604** [trungdq88/insurance-card#185]
Làm sau khi có notification.

**Comment by trungdq88** [comment]
Ý nghĩa của các badges mình đã thống nhất chưa nhỉ? (Em nhớ là chưa)
Anh implement như thế nào, sao không thấy commit nào gắn với issue này nhỉ, anh commit link commit vào đây được không?

**Comment by hydrangea8604** [comment]
Tại đến gần cuối mới làm notification, giờ để vướng quá nên a close luôn đó. Thôi thì open lại

**Comment by trungdq88** [comment]
Close phải ghi rõ lý do nếu không thì mặc định hiểu là đã làm xong.
Em nghĩ cứ nên để nó open như vậy cũng được. Em edit description.

**Comment by trungdq88** [comment]
Có vẻ như là mình không cần mấy cái badges này nữa.
