### ISSUE TITLE
<Guest> User interface: hiển thị nội dung hợp đồng và thanh toán chưa phù hợp

### ISSUE THREAD

**Issue by hydrangea8604** [trungdq88/insurance-card#188]
![image](https://cloud.githubusercontent.com/assets/12366868/8397071/18d872f4-1de9-11e5-8228-2c4523fe429a.png)
Đưa câu dưới thay thế câu trên. Chuyển câu trên xuống trên nút thanh toán.
![image](https://cloud.githubusercontent.com/assets/12366868/8397107/548f436c-1dea-11e5-8f44-66bd4ad29f48.png)
2 dòng nội dung và số tiền bị lệch, đưa vào class=text-center để căn giữa. Dòng phương thức thanh toán đưa xuống trước 2 cái radio button.

**Comment by minhtridn2001** [comment]
@hydrangea8604 Sao lại căn giữa Kha ? Căn giữa nó còn xấu hơn đó

**Comment by minhtridn2001** [comment]
Sửa lại theo ý Kha nha
