### ISSUE TITLE
<Customer> User interface: trường hợp pending khi customer nhấn thanh toán, markup lại tooltip

### ISSUE THREAD

**Issue by phucnguyen60749** [trungdq88/insurance-card#189]

**Comment by phucnguyen60749** [comment]
@hydrangea8604  review dùm nha

**Comment by trungdq88** [comment]
@phucnguyen60749 nhớ gắn số vào commit message giùm em nha. Nếu lỡ quên thì có thể copy link của commit đó ở trang này: https://github.com/trungdq88/insurance-card/commits/master và paste vào comment.

**Comment by hydrangea8604** [comment]
Lại có dấu &times ở alert.
Icon định vị bản đồ đó nếu không phải là người quen dùng thì chắc không biết nó dùng để làm gì, nên có description. Bấm vào cũng không chỉ tới địa chỉ của công ty, chỉ hiện lên bản đồ thế giới.
![image](https://cloud.githubusercontent.com/assets/12366868/8412293/21de86d4-1eb3-11e5-967f-c367d26032c7.png)
@trungdq88 Trang checkout vẫn còn lỗi font nè Trung.

**Comment by phucnguyen60749** [comment]
![untitled](https://cloud.githubusercontent.com/assets/12363394/8412353/8a2e6b3c-1eb3-11e5-881c-2b58191f998c.png)

**Comment by hydrangea8604** [comment]
![image](https://cloud.githubusercontent.com/assets/12366868/8412396/dcf92000-1eb3-11e5-975a-1b7081d4d23f.png)
I don't know

**Comment by trungdq88** [comment]
Lỗi bản đồ thế giới: dùng cửa sổ ẩn danh sẽ hết lỗi. Nguyên nhân: không rõ.

**Comment by trungdq88** [comment]
Lỗi font: cấu hình lại tomcat theo hướng dẫn này: http://stackoverflow.com/a/138950/1420186

**Comment by trungdq88** [comment]
@hydrangea8604 mà sao em chưa thấy markup lại tooltip gì hết nhỉ? Anh thấy markup tooltip rồi hả?

**Comment by hydrangea8604** [comment]
![image](https://cloud.githubusercontent.com/assets/12366868/8412648/58e446f8-1eb5-11e5-8dd4-9ca297b7e05a.png)
Không phải cái này hả?

**Comment by trungdq88** [comment]
Đó là tooltip cũ.

**Comment by phucnguyen60749** [comment]
cái củ màu đỏ mà!

**Comment by trungdq88** [comment]
@_@ vậy hả, vậy thôi tạm thời tooltip vậy cũng được, chắc chắn sau này phải đổi. Nhìn không đẹp.

**Comment by phucnguyen60749** [comment]
@trungdq88  ok vậy em nói lý do không đẹp để a dễ chỉnh sữa nha! :)

**Comment by trungdq88** [comment]
Anh có thể sửa lại thành nền trắng, không trong suốt, viền xám dày khoảng 4px góc bo tròn, đổ bóng.
Và đừng để cái mũi tên nhỏ nhỏ kia màu xanh.

**Comment by phucnguyen60749** [comment]
@trungdq88  nhu the nay thi sao
![untitled](https://cloud.githubusercontent.com/assets/12363394/8413012/b54acafa-1eb7-11e5-989a-147493dfe71f.png)

**Comment by trungdq88** [comment]
Anh đọc thiếu rồi: 
- Không trong suốt
- Viền xám, dày khoảng 4px
- Góc bo tròn
- Đổ bóng mờ.

**Comment by phucnguyen60749** [comment]
@trungdq88  tạm thời vậy nha trung
![untitled](https://cloud.githubusercontent.com/assets/12363394/8413650/30b2a25e-1ebc-11e5-8dd7-f5007f23715f.png)

**Comment by trungdq88** [comment]
Ặc, sao còn tệ hơn cái cũ vậy.
Thôi để đó em sửa luôn cho rồi. Mất thời gian nhiều quá.

**Comment by trungdq88** [comment]
Anh @hydrangea8604 còn lỗi gì nữa không nhỉ?

**Comment by hydrangea8604** [comment]
Không @trungdq88 Trung sửa rồi close luôn cũng được.

**Comment by phucnguyen60749** [comment]
@hydrangea8604  review lai dùm! 
@trungdq88  xấu chổ nào ta! có thể mai để thầy review cái đó ko nhĩ!

**Comment by trungdq88** [comment]
Chỉ còn cái tooltip. Sửa sau.
Close.
