### ISSUE TITLE
<Staff> renew contract

### ISSUE THREAD

**Issue by phucnguyen60749** [trungdq88/insurance-card#191]
Chọn gia hạn đến chọn 06/dd/yyyy --> hệ thống vẫn tính được tiền! phải show ra NAN
![untitled](https://cloud.githubusercontent.com/assets/12363394/8397478/8f3c1d62-1df6-11e5-90ea-cb186d9cc4d4.png)

**Comment by hydrangea8604** [comment]
Bởi vì người dùng không biết NaN là gì nên nếu nhập invalid date thì phí gia hạn sẽ là 0. @minhtridn2001 review lại dùm nha

**Comment by minhtridn2001** [comment]
Đã review.
