### ISSUE TITLE
<Staff> cancel contract

### ISSUE THREAD

**Issue by phucnguyen60749** [trungdq88/insurance-card#192]
Chưa validate nhập khoảng trắng vào field "Lý do hủy hợp đồng"

**Comment by hydrangea8604** [comment]
@minhtridn2001 Mới chỉ validate trên server, dưới client chưa làm được, sẽ làm sau.

**Comment by trungdq88** [comment]
Anh có thể validate bằng regex: `^\w.+$` ý nghĩa: ít nhất phải bắt đầu bằng 1 ký tự là [a-z0-9].

**Comment by hydrangea8604** [comment]
Cảm ơn @trungdq88 đã giúp, đúng là não của thiên tài khác não của mấy thằng ngu như mình.
@minhtridn2001 Nếu lỡ review rồi thì review lại dùm với nha

**Comment by phucnguyen60749** [comment]
@hydrangea8604 bên chổ customer của P cancel contract có bắt nhập khoảng trắng đó kha!

**Comment by hydrangea8604** [comment]
Làm theo cách của Trung được rồi, cách của P cũng có đọc qua, toàn dùng JQuery, mất công quá

**Comment by minhtridn2001** [comment]
Đã review :+1:
