### ISSUE TITLE
<Customer> contract-detail.jsp: Chỉnh sửa giao diện cho phù hợp.

### ISSUE THREAD

**Issue by hydrangea8604** [trungdq88/insurance-card#193]
![image](https://cloud.githubusercontent.com/assets/12366868/8407880/30205510-1e95-11e5-8d08-31548649b5ba.png)
Mã hợp đồng nên tô đậm, thu gọn column lại cho fix với content. Hai dòng thời gian nên có thêm chữ "lúc" để đọc hiểu tốt hơn.
![image](https://cloud.githubusercontent.com/assets/12366868/8407899/5a64920a-1e95-11e5-88db-f69400c19861.png)
Thông tin xe có 11 cái mà, sao đây còn có 8. Giá trị trong field Nhãn hiệu sai, "LX" là số loại. Sắp xếp lại thứ tự hiển thị các field, cho đồng bộ với t và Trí. Đây là thông tin xe của hợp đồng cùng mã số hiển thị bên Staff.
![image](https://cloud.githubusercontent.com/assets/12366868/8407958/0b28e776-1e96-11e5-9dce-6bca13ece8f5.png)

**Comment by phucnguyen60749** [comment]
@hydrangea8604  review dùm

**Comment by hydrangea8604** [comment]
Đưa 2 tấm hình mà, sao chỉ sửa có 1. Cái trên không sửa hay thế nào?

**Comment by phucnguyen60749** [comment]
cái trên có thể để từ từ fix đồng bộ nha @hydrangea8604

**Comment by hydrangea8604** [comment]
Cái trên thì có đồng bộ gì đâu? Thôi close.

**Comment by trungdq88** [comment]
Tại sao lại close?

**Comment by hydrangea8604** [comment]
@trungdq88 Phần dưới xong rồi, phần trên chỉ là đề xuất thôi, không sửa cũng không sao, nên close.
