### ISSUE TITLE
Xử lý concurrency cho các thao tác gia hạn, chỉnh sửa thông tin hợp đồng.

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#194]
https://www.facebook.com/groups/insurancecard/permalink/877590342276574/
[Bug]
HIện tại system mình chưa xử lý trường hợp sau:
- Tại một thời điểm nhiều staff có thể chỉnh sữa một hợp đồng 
- Tại một thời điểm customer và staff có thể cùng gia hạn một hợp đồng!
Đề xuất :thêm filed ~~`IsLock`~~ `last_modified` vào bảng contract để cập nhật và kiểm tra khi có một transaction cho contract đó!

Một số test case:

- Guest Register quan trang public > Thanh toán | Cùng lúc đó staff ở trang contract detail thanh toán cùng contract Pending.
- Customer Gia hạn hợp đồng | Cùng lúc đó staff cũng gia hạn hợp đồng
- Customer Send cancel request | Cùng lúc đó staff gia hạn hoặc huỷ

**Comment by minhtridn2001** [comment]
@trungdq88 isLock chứ không phải lastModified hả em? a thấy nếu dùng isLock sẽ có thể dẫn đến tình trạng deadlock khi chưa trả lại giá trị cho isLock đc

**Comment by trungdq88** [comment]
Phải là lastModified chứ, cái trên chỉ là em copy từ nội dung gốc để reference thôi.

**Comment by trungdq88** [comment]
Sẽ close issue này sau #217, #218, #219.

**Comment by trungdq88** [comment]
Đã hoàn thành concurrency check cho Staff #217, Customer #219 và Public #218.
Anh @phucnguyen60749 review cẩn thận lại nhé. Tự đặt thêm một số trường hợp đặc biệt để test.

**Comment by phucnguyen60749** [comment]
@trungdq88 đã test chạy đúng như như mô tả! nhưng vẫn còn confuse khi system không notify lúc do vì sao không thực hiện được action đó! 
Cái nữa tại cùng một thời đểm nếu cả hai người đều thực hiện nút submit thì a ko test dc!

**Comment by trungdq88** [comment]
@phucnguyen60749 system có thông báo lý do không thực hiện được action mà?
![screenshot 2015-07-01 23 59 02](https://cloud.githubusercontent.com/assets/4214509/8460232/2e09dff8-204d-11e5-9463-3d0323000f80.png)

Phần test cùng thời điểm đã confirm ở facebook group chat.

**Comment by phucnguyen60749** [comment]
ok đã review!

**Comment by phucnguyen60749** [comment]
@trungdq88 khi staff cancel contract rồi customer cũng cancel contract! nên bỏ câu thông báo "vui lòng thực hiện lại thao tác"
![untitled](https://cloud.githubusercontent.com/assets/12363394/8460702/0ae78b98-2051-11e5-9904-4ce9c419c1a8.png)

**Comment by trungdq88** [comment]
Lỗi concurrency có thể xảy ra nhiều trường hợp, thông báo này là dùng chung trong tất cả các trường hợp đó, ví dụ:
- Staff gia hạn, customer huỷ hợp đồng => câu thông báo đúng và có ý nghĩa
- Staff đổi thông tin hợp đồng, customer huỷ hợp đồng => câu thông báo đúng và có ý nghĩa
- Staff huỷ hợp đồng, customer huỷ hợp đồng => là trường hợp mà anh đưa ra: câu thông báo vẫn có ý nghĩa, khi thấy hợp đồng bị huỷ và thông báo trên thì người dùng sẽ hiểu là đã có người khác huỷ trước rồi, không cần thực hiện lại thao tác nữa.

Vậy nên câu trên là đúng và không cần thay đổi.
Tuy nhiên một số trường hợp như thanh toán, renew thì câu thông báo có sự khác biệt, em đã đổi.

**Comment by phucnguyen60749** [comment]
@trungdq88  ok vậy a close issue này!
