### ISSUE TITLE
<Staff> Cancel contract ko được

### ISSUE THREAD

**Issue by minhtridn2001** [trungdq88/insurance-card#196]
Vô tình gặp trường hợp này thì cancel contract ko được nè:
![image](https://cloud.githubusercontent.com/assets/12363317/8410024/ee340852-1ea5-11e5-965b-b0a7933191e0.png)

**Comment by hydrangea8604** [comment]
Đó (lại) là do dummy database. Đáng lẽ là request cancel thì lý do hủy phải khác empty.
