### ISSUE TITLE
Fix lại chỗ thanh toán cho hợp đồng Pending và trạng thái hợp đồng sau khi thanh toán

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#197]
- Lúc thanh toán, nếu ngày bắt đầu của hợp đồng vẫn chưa tới thì trạng thái phải là Pending.
- Thanh toán xong phải gán lại startDate và expiredDate.

Các chỗ cần chỉnh sửa:
- [x] Public Register
- [x] Customer thanh toán cho hợp đồng Pending
- [x] Staff thanh toán cho hợp đồng Pending

**Comment by minhtridn2001** [comment]
@trungdq88  em review lại xem nhé

**Comment by trungdq88** [comment]
Thanks. Đã review :white_check_mark:

**Comment by trungdq88** [comment]
Thanks. Đã review :white_check_mark:
