### ISSUE TITLE
<Customer> thông tin hợp đồng hiển thị ngày còn lại của hợp đồng sai

### ISSUE THREAD

**Issue by minhtridn2001** [trungdq88/insurance-card#198]
![image](https://cloud.githubusercontent.com/assets/12363317/8410954/7d7239b2-1eab-11e5-97c6-67a297117bcb.png)

**Comment by trungdq88** [comment]
Còn nữa, chỗ field "Hợp đồng còn" tại sao lại là input nhỉ? Nếu dùng chuột click vào thì có thể đổi được giá trị. 

Đây không phải lần đầu gặp cái vụ "đáng lẽ là label mà cuối cùng lại là input", anh @phucnguyen60749 có đang nhầm lần cái gì không vậy?

![screenshot 2015-06-29 22 13 17](https://cloud.githubusercontent.com/assets/4214509/8411058/15efbfc0-1eac-11e5-9a9c-94f618261ce1.png)

**Comment by phucnguyen60749** [comment]
@hydrangea8604  review dum

**Comment by hydrangea8604** [comment]
![image](https://cloud.githubusercontent.com/assets/12366868/8411593/08e7bc4e-1eaf-11e5-89f5-8b6ac3fdb557.png)
Không còn edit được nhưng số vẫn sai.
![image](https://cloud.githubusercontent.com/assets/12366868/8411609/1b81aad6-1eaf-11e5-9561-4ad8a2e959df.png)
Đã cầu hủy?? Sao không chỉnh lại nhìn cho dễ.
Trong trang chi tiết hợp đồng, class của label trạng thái Ready có thêm chữ fa ngay đầu, khác với mấy cái label khác.

**Comment by trungdq88** [comment]
Anh @phucnguyen60749 nhớ pull về trước khi code tiếp chỗ này, em có sửa title của các field.

**Comment by phucnguyen60749** [comment]
@hydrangea8604  có thể view hình chổ tính sai ngày ko kha

**Comment by hydrangea8604** [comment]
Tấm hình to đùng ở trên đó, hợp đồng đã hủy nhưng số còn 363 ngày kìa.

**Comment by hydrangea8604** [comment]
![image](https://cloud.githubusercontent.com/assets/12366868/8411909/a35dcc18-1eb0-11e5-9fc1-706beb8970f7.png)
Để cái dấu &times chỗ alert chi vậy, lỡ người dùng click vào thông báo mất đi thì phải refresh lại. Cũng đâu cần phải cho phép tắt alert làm gì.
@phucnguyen60749 Sẵn tiện xử lý cái này luôn, khỏi phải tạo issue mới

**Comment by phucnguyen60749** [comment]
@hydrangea8604  đã bỏ cái dấu kia!
còn cái ngày còn lại! nêu hợp đồng vẫn còn deadline nhưng vì một lí do nào đó staff hủy nó thì sao!

**Comment by hydrangea8604** [comment]
Cho dù có lỡ tay thì cũng thành Cancelled rồi, mà đã là Cancelled thì không có giá trị, đã không có giá trị thì sao lại còn thời hạn.

**Comment by phucnguyen60749** [comment]
@trungdq88 có thể confirm lại tr hợp này không?

**Comment by trungdq88** [comment]
Anh Kha review đúng. Nếu hợp đồng đã huỷ thì có thể hiện số 0 hoặc chữ "đã huỷ"

**Comment by phucnguyen60749** [comment]
@hydrangea8604  review dùm

**Comment by trungdq88** [comment]
Anh đừng để comment message kiểu "fix XXX" nha:
1. Không rõ làm gì trong comment. Từ đầu mình đã thống nhất là ghi message có ý nghĩa, hạn chế ghi message vắn tắt thế này.
2. Nếu message có format là "fix XXX" thì nó tự động close issue, trong khi đó mình còn bước review nên chưa close issue liền được.

Để ý giùm em.

**Comment by phucnguyen60749** [comment]
ok

**Comment by hydrangea8604** [comment]
Hợp đồng trạng thái Pending lại thành "Chưa kích hoạt"

**Comment by trungdq88** [comment]
@hydrangea8604  Vụ "Chưa kích hoạt": #197
