### ISSUE TITLE
<Customer> Renew contract chưa validate bên server

### ISSUE THREAD

**Issue by minhtridn2001** [trungdq88/insurance-card#199]
Renew contract chưa validate bên server @@ Cái button f12 sửa lại bỏ disable đi thì vẫn submit được bình thường.

**Comment by hydrangea8604** [comment]
Issue này trùng rồi, kiểm tra trước khi tạo mới chứ.
#179 <Customer> Kiểm tra ràng buộc khi gia hạn hợp đồng: thời gian còn lại phải ít hơn 2 tháng.

**Comment by trungdq88** [comment]
Trùng #179

**Comment by minhtridn2001** [comment]
@hydrangea8604  @trungdq88  Bên đó là kiểm tra ràng buộc 2 tháng mà. Cái này là thiếu cả validate bên server luôn. Bao gồm startDate, expiedDate,...

**Comment by trungdq88** [comment]
Phần gia hạn của customer đâu có nhập gì vào đâu mà phải validate nhỉ? Chỉ có validate cái ràng buộc 2 tháng thôi chứ?

**Comment by minhtridn2001** [comment]
Ừ P lấy thẳng bên client vào mà

**Comment by trungdq88** [comment]
Em không thấy chỗ đó, anh có thể copy đoạn đó ra đây không?

**Comment by minhtridn2001** [comment]
Ah a nhầm. Tại thấy bên jsp có input startDate với expiredDate mà controller ko dùng.
