### ISSUE TITLE
Lỗi font trong email.

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#200]
![image](https://cloud.githubusercontent.com/assets/12363317/8412536/aa8e30aa-1eb4-11e5-8014-89ef46555888.png)

**Comment by trungdq88** [comment]
Anh @minhtridn2001 confirm lại giúp em cái này luôn nha.

**Comment by minhtridn2001** [comment]
Nội dung thì OK nhưng title mail thì vẫn bị lỗi em ơi.
![image](https://cloud.githubusercontent.com/assets/12363317/8510421/b45c9f62-230b-11e5-8d78-a4ed378e5823.png)

**Comment by trungdq88** [comment]
Ok, review một lần nữa nha. Em nghĩ chắc ok rồi đó.

**Comment by minhtridn2001** [comment]
Yahoo mail bị lỗi ko hiện đầy đủ Title. Gmail thì OK.
