### ISSUE TITLE
Improve paypal payment.

### ISSUE THREAD

**Issue by minhtridn2001** [trungdq88/insurance-card#201]
Làm lại quá trình process paypal payment bảo mật hơn.

**Comment by trungdq88** [comment]
Một số tip để phát hiện lỗi bảo mật:
- Người dùng có thể thay đổi những thứ trên URL để khiến hệ thống chạy sai hay không? (GET request attack)
- Người dùng có thể thay đổi giá trị trong các form (bằng F12) để khiến hệ thống chạy sai hay không? (POST request attack)
- Trong một quy trình thực hiện một chức năng, thử dừng lại ở **bất kỳ** bước nào (tắt trình duyệt / huỷ session / bấm nút back...), hệ thống có còn chạy đúng hay không?
- Trong một quy trình thực hiện một chức năng, người dùng có quyền truy cập thẳng vào bước thứ `n`  nào đó hay không? (thông qua đường dẫn URL)

Lỗi bảo mật tuy nghiêm trọng, nhưng những lỗi cao siêu quá thì có thể chúng ta "chưa cần" làm, lý do là sản phẩm trong capstone project không ai ngồi bắt lỗi bảo mật cả, hội đồng cũng chỉ tập trung business. Cho nên hãy bắt những lỗi rõ ràng và dễ thấy nhất trước.

**Comment by trungdq88** [comment]
Close.
