### ISSUE TITLE
Fix giao diện Login

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#202]

**Comment by trungdq88** [comment]
Đã đổi giao diện.
Anh @phucnguyen60749 review nhé.

**Comment by phucnguyen60749** [comment]
@trungdq88 câu thông báo nên là: email hoặc mật khẩu không chính xác! 
![untitled](https://cloud.githubusercontent.com/assets/12363394/8432568/0ffcc594-1f6b-11e5-8aa3-4d797066d1ff.png)
