### ISSUE TITLE
Những field trống tự động điền "Không có".

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#203]
Cần sửa ở những chỗ:
 - [x] Register page
 - [x] Contract detail ở staff
 - [x] Contract detail ở customer

Assignees: @minhtridn2001 @phucnguyen60749 @hydrangea8604 
Assign trước cho @minhtridn2001 làm xong thì assign lại cho người nào chưa làm nha.

**Comment by hydrangea8604** [comment]
@minhtridn2001 Đã review của Trí, Trí review lại dùm nha

**Comment by phucnguyen60749** [comment]
@hydrangea8604 vậy kha review  dùm tui nhé!

**Comment by hydrangea8604** [comment]
@phucnguyen60749 Review rồi, ngoại trừ không biết vì một lý do nào đó thêm css font-weight: 500 cho cái chữ "Không có" vô dụng lớn hơn mấy chữ khác ra thì không có vấn đề gì.

**Comment by minhtridn2001** [comment]
@hydrangea8604  Đã review của Kha. OK!

**Comment by minhtridn2001** [comment]
Phúc dùng chung style giống T vs Kha đi

**Comment by phucnguyen60749** [comment]
tui cũng dùng cái empty-value đó! mà tại tui sợ chữ mờ nên thêm cái css font-weight: 500
@hydrangea8604 nếu có cái style đó thì có vấn đề gì ko

**Comment by hydrangea8604** [comment]
@phucnguyen60749 Chữ "Không có" là không tồn tại, người dùng đâu quan tâm những thứ không tồn tại. Để to hơn nội dung cần thiết thì không nên thôi chứ có vấn đề gì.

**Comment by phucnguyen60749** [comment]
ok để chìu về tui xem lại
