### ISSUE TITLE
<Customer> Lựa chọn: nên làm mờ hay biến mất nút.

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#206]
Cần sửa ở:
- [x] Customer contract detail

Nhớ confirm kỹ tất cả các trạng thái + trương hợp không được gia hạn khi còn hạn hơn 2 tháng.

**Comment by phucnguyen60749** [comment]
@hydrangea8604 review dum nha

**Comment by hydrangea8604** [comment]
:white_check_mark: Đã review
