### ISSUE TITLE
Staff có quyền chỉnh các field ngày tháng trong giới hạn 1 tuần.

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#210]
Apply business 1 tuần giới hạn sửa cho staff.

- [x] Contract detail: renew contract: paid date, expired date
- [x] Contract cancel: cancel date
- [x] Contract pending payment: paid date
- [x] Create new contract: start date, paid date, expired date

Đổi use case specs.

**Comment by hydrangea8604** [comment]
@minhtridn2001 Review dùm nha Trí.

**Comment by minhtridn2001** [comment]
@hydrangea8604 
- Create contract: startDate min là trước 1 tuần, startDate max muộn nhất là 2 tháng. (Ko phải đều giới hạn 1 tuần hết hả?)
- Renew contract: 
   +paidDate max muộn nhất là 1 tháng(Ko phải 1 tuần như description issue sao?) 
   +ExpiredDate ko thấy cho sửa giới hạn 1 tuần như description.
- Cancel contract: cancel date min-max là 7 ngày - 1 tháng từ ngày current. Ko phải 7-7 như description sao?
- Contract pending payment: paid date: cũng là min-max 7-30.
Nếu bussiness là thế thì OK.

Và thiếu validate server side nữa Kha ơi.

**Comment by hydrangea8604** [comment]
Còn mấy cái vụ ngày tháng ở trên thì đâu có thống nhất đâu? Chỉ có cho Staff config, giờ đã tạo cái Constant chỉ cần sửa số trong đó là được thôi mà??? Sau này làm nó thành cái trang Configuration là được.
Validate server tạo issue mới.
#229 <Staff> Validate server-side theo staff configuration.

**Comment by trungdq88** [comment]
@hydrangea8604 Anh có thể liệt kê tất cả những giới hạn mà chúng ta chưa thống nhất không? Ví dụ create contract thì trễ nhất là bao lâu?

**Comment by hydrangea8604** [comment]
public static final int START_DATE_AFTER = 60;
        public static final int EXPIRED_DATE_AFTER = 1;
        public static final int PAID_DATE_AFTER = 30;
        public static final int CANCEL_DATE_AFTER = 30;

Đó, 4 cái này là chưa thống nhất, a tạo sẵn ra luôn thôi

**Comment by trungdq88** [comment]
:+1:
