### ISSUE TITLE
Thêm mục concurrency control vào algorithm.

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#212]

**Comment by trungdq88** [comment]
Đã thêm mục Concurrency control trong Algorithm.
Anh @phucnguyen60749 review nhé.

**Comment by phucnguyen60749** [comment]
@trungdq88  có một số ngữ pháp a sữa lại xíu e xem lại nhé (những chổ tô đậm và in nghiên) :
![modify](https://cloud.githubusercontent.com/assets/12363394/8446706/ad8954a4-1fd8-11e5-880f-819746ee03f5.png)

**Comment by trungdq88** [comment]
Đã sửa lại gramma ở những chỗ anh Phúc gợi ý, nhưng không giống với phần gợi ý của anh Phúc.
Em nghĩ document thì nên để thầy review sẽ hiệu quả hơn.
Em close issue này ở đây.
