### ISSUE TITLE
Implement scheduler

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#213]
Xem file `SchedulerJob.java`, phần code thao tác với DB sẽ đặt ở đây.

```java
public class SchedulerJob implements Job {

    @Override
    public void execute(final JobExecutionContext ctx)
            throws JobExecutionException {

        // Example
        System.out.println("Executing Job " + (new Date()));
        ContractDao contractDao = new ContractDao();
        Long count = contractDao.getAllContractCount();
        System.out.println("Count: " + count);

        // Should call business object's method here, only 1 line of code.

    }

}
```

Lưu ý: phải tạo 1 cái `SchedulerBusiness` và đặt toàn bộ code xử lý ở trong đó, trong hàm `execute` của `SchedulerJob` chỉ tạo object business và gọi hàm thôi.

Hiện tại scheduler sẽ chạy ngay sau khi deploy app và lặp lại sau mỗi 40s để phục vụ cho việc test. Cấu hình ở file `QuartzLisnter.java`
```java
            Trigger trigger = TriggerBuilder.newTrigger()
                    .withIdentity("simple", "group1")
                    .startNow()
                    .withSchedule(SimpleScheduleBuilder.simpleSchedule()
                            .withIntervalInSeconds(40)
                            .repeatForever())
                    .build();
```

Flow chart cho scheduler (cập nhật lần cuối: July 1, 9:13 PM)
![notify flow chart](https://cloud.githubusercontent.com/assets/4214509/8456509/18846a7a-2036-11e5-9f95-2b4aac03d231.jpg)

**Comment by trungdq88** [comment]
Các tác vụ cần làm trong 1 lần chạy Job:

![notify flow chart](https://cloud.githubusercontent.com/assets/4214509/8436275/3a57546a-1f81-11e5-8ee0-90cda1100368.jpg)

Các task notify thì để sau. Làm những cái liên quan tới status contract trước.

**Comment by trungdq88** [comment]
@minhtridn2001 đọc comment và implement nha :game_die:

**Comment by minhtridn2001** [comment]
@Trung A có ý kiến thêm như thế này em xem qua rồi confirm lại cho anh nhé:
- Is there new contract, compensation, request,..? Send notify to staff: Anh thấy nên thực hiện bước này ngay khi customer thực hiện những request chứ ko đợi đến cuối ngày nè.
- Flow chart em còn thiếu check Contract Pending đã thanh toán và đến ngày active.
- Renew due date và Payment due date mình thống nhất lại là bao nhiêu ngày.
- Và mới Payment due date thì mình cần có ngày đăng ký hợp đồng. Ở đây mình chỉ có startDate và expiredDate thì phải thêm ngày này vào đâu

**Comment by trungdq88** [comment]
> Is there new contract, compensation, request,..? Send notify to staff: Anh thấy nên thực hiện bước này ngay khi customer thực hiện những request chứ ko đợi đến cuối ngày nè.

Hợp lý. Bởi vậy em nói cái notification chưa làm.

> Flow chart em còn thiếu check Contract Pending đã thanh toán và đến ngày active.

À em gửi nhầm cái hình, lát em gửi lại hình mới.

> Renew due date và Payment due date mình thống nhất lại là bao nhiêu ngày.

Hiện tại anh có thể cho nó thành 7 ngày và đặt biến số 7 ở file `Constants`

> Và mới Payment due date thì mình cần có ngày đăng ký hợp đồng. Ở đây mình chỉ có startDate và expiredDate thì phải thêm ngày này vào đâu

Chắc là mình phải thêm một biến nữa là `created_date` vào bảng contract rồi.

**Comment by trungdq88** [comment]
Đã cập nhật lại file hình flow chart.

**Comment by minhtridn2001** [comment]
Em review qua cho anh đi Trung.
Tối a thêm cái created_date vào contract sau nhé. Vậy mình phải sửa lại nhiều document rồi.

**Comment by minhtridn2001** [comment]
@trungdq88 A làm xong 5 cái checking status của contract rồi. Em review nhé.

**Comment by trungdq88** [comment]
Em đã review, có 2 lỗi business:

- Các hợp đồng expired SẼ KHÔNG tự động chuyển qua Cancelled. (Flow chart bị sai, em sẽ đổi lại flow chart mới)
- Các hợp đồng Pending không thanh toán sau 7 ngày sẽ bị cancel, chỗ này phải cập nhật thêm lý do huỷ: Quá ngày thanh toán hợp đồng.

Ngoài ra, anh nên tách ra mỗi business làm một hàm, đừng để chung như vậy. Ví dụ ở đây mình có 5 business:

1. Notify khi có HĐ mới, compensation mới, accident mới, new card request, cancel request.
2. Notify khi HĐ sắp hết hạn
3. Đổi status và notify khi hết hạn
4. Đổi status và notify khi vượt quá ngày thanh toán cho HĐ Pending
5. Đổi status khi ngày có hiệu lực của hợp đồng Pending (đã thanh toán) bắt đầu.

Anh nên tách làm 5 hàm, comment và viết code cho mỗi hàm để tăng tính high cohesion cho code.

**Comment by trungdq88** [comment]
Đã cập nhật lại flow chart mới ở post đầu tiên.

**Comment by minhtridn2001** [comment]
Còn phần notify anh chưa làm, em review giúp a nhé.

**Comment by trungdq88** [comment]
Implement concurrency check. Chạy lại procedure nếu concurrency check fail.

**Comment by minhtridn2001** [comment]
Anh kiểm tra nếu có thay đổi thì lấy luôn giá trị của contract mới.

**Comment by trungdq88** [comment]
```java
        for (ContractEntity contractEntity : contractEntityList) {
            boolean isNotChanged = contractEntity.getLastModified().equals(contractDao.read(contractEntity.getContractCode()).getLastModified());
            do {
                if (isNotChanged) {
                    // check if contract is expired
                    if(!checkIfContractExpired(contractEntity)){
                        // if not, check if contract is nearly expired
                        if(!checkIfContractNearlyExpired(contractEntity)){
                            // if not, check if contract if exceeded payment due date
                            if(!checkIfContractExceedPaymentDueDate(contractEntity)){
                                // check if contract is started.
                                checkIfPendingContractStart(contractEntity);
                            }
                        }
                    }
                } else {
                    contractEntity = contractDao.read(contractEntity.getContractCode());
                    isNotChanged = contractEntity.getLastModified().equals(contractDao.read(contractEntity.getContractCode()).getLastModified());
                }
            } while (!isNotChanged);
        }
```

Đoạn code trên sai:

1. Phải kiểm tra concurrency ở mỗi hàm chứ không phải kiểm tra 1 lúc tất cả như vậy. Vì có trường hợp hàm a đổi status, lúc sang hàm b thì nó lấy biến entity từ cái list (mang giá trị cũ) => concurrency conflict.
2. Các hàm kiểm tra là void chứ không phải là boolean, nó là 1 procedure, không phải hàm kiểm tra hay gì cả mà phải trả về boolean làm gì.
3. Chỗ các vòng if lồng nhau: sai logic với flow chart: tại sao hàm a làm đúng (hoặc sai) thì mới làm hàm b? Nếu điều kiện đầu mà sai thì bỏ qua 3 hàm còn lại à? Why? Anh xem trong flow chart, dù đúng hay sai thì nó vẫn sẽ làm bước tiếp theo.

Ngoài ra, hàm `checkIfPendingContractStart`, dòng này tại sao lại có dấu not `!` ở câu if nhỉ? Anh kiểm tra lại xem đúng logic không nha:

```java
if (!(contractEntity.getStartDate().after(currentDate))) {
```

**Comment by minhtridn2001** [comment]
@trungdq88 
1. Anh đang phân ra theo từng Contract state: Đầu tiên là check nếu contract còn hiệu lực: No card, ready, cancel request. Sau đó mới check contract pending. Cho nên nếu 1 contract được update thì nó sẽ không gọi hàm sau nữa => concurrency ko bị ảnh hưởng(A muốn làm vậy thay vì gọi lần lượt 4 hàm để tăng performance)
2. Vì mục đích trên (1) nên anh đặt nó là boolean để check nếu succeed or not.
3.  Logic đó đúng mà em, a cũng test rồi. Nếu hàm trước trả về  false (contract ko update) thì thực hiện tiếp hàm sau. Nếu trả về true( update status contract) thì ko thực hiện tiếp hàm sau làm gì cả.
Anh để
```
if (!(contractEntity.getStartDate().after(currentDate)))
``` 
thay vì  phải gọi 2 hàm
```
if (contractEntity.getStartDate().equals(currentDate) || contractEntity.getStartDate().before(currentDate))
```

Em review lại nếu ko thấy ok thì anh sẽ làm lại gọi lần lượt 4 hàm như em nói .

**Comment by trungdq88** [comment]
1,2,3: Ok đó là một sự sắp đặt rất công phu để cho mọi thứ vẫn thực hiện đúng. Anh có thể giữ lại đoạn code như thế. Tuy nhiên đoạn code của anh em đánh giá là khó hiểu và khó maintain, nếu sau này xuất hiện thêm business mới thì phải rất đau đầu để biết được là thêm nó vào chỗ nào. Về performance thì em không rõ là nó hiệu quả hơn nhiều hay không.

Và mặc dù vậy, luồng xử lý của anh chỉ là "tương đương" với cái flow chart thôi, chứ không phải là làm theo flow chart (flow chart thể hiện luồng xử lý của code mà!)

Còn chỗ dấu `!`, em nhớ là nếu startDate mà **sau** ngày hiện tại thì sẽ thực hiện đổi status. Theo như câu lệnh `if (contractEntity.getStartDate().equals(currentDate) || contractEntity.getStartDate().before(currentDate))` thì em hiểu là nếu startDate **trước hoặc bằng** ngày  hiện tại thì đổi status. Có nhầm lẫn gì không nhỉ.

Em đang tìm cách để test black-box cái scheduler này với cả để demo luôn.

**Comment by minhtridn2001** [comment]
@trungdq88 Em nhầm rồi. Nếu startDate là sau ngày hiện tại. Nghĩa là ngày startDate chưa đến mà :P

**Comment by minhtridn2001** [comment]
Em giảm thời gian xuống còn 5 10s để test ak.

**Comment by trungdq88** [comment]
Có 2 câu hỏi để làm rõ cái vụ dấu `!`:
1. Ngày July 02 sau hay trước ngày July 03?
2. `"Jule 02".after("July 03")` trả về `true` hay `false`?

Em đổi thành nó chạy từng phút để test, anh xem file `QuartzListener.java`
```java
            Trigger trigger = TriggerBuilder.newTrigger()
                    .withIdentity("simple", "group1")
                    .startNow()
                    .withSchedule(SimpleScheduleBuilder
                            .repeatMinutelyForever())
                    .build();
```

**Comment by trungdq88** [comment]
Black-box test:

- [ ] Notify khi HĐ sắp hết hạn
- [ ] Đổi status và notify khi hết hạn
- [ ] Đổi status và notify khi vượt quá ngày thanh toán cho HĐ Pending
- [ ] Đổi status khi ngày có hiệu lực của hợp đồng Pending (đã thanh toán) bắt đầu.

**Comment by trungdq88** [comment]
Đã review :white_check_mark:
