### ISSUE TITLE
Business change: không quản lý giờ phút giây của startDate và expiredDate

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#214]
Kiểm tra lại ở database, fix nếu có sử dụng giờ phút giây.

- [x] Register: public @minhtridn2001 
- [x] Staff: Create, renew, cancel, complete payment @hydrangea8604 
- [x] Customer: Renew, Cancel request @phucnguyen60749

**Comment by phucnguyen60749** [comment]
@hydrangea8604  startDate và expiredDate vẫn còn giờ, phút, giây ở Renew Contract

**Comment by trungdq88** [comment]
@phucnguyen60749 cái này là task của anh chứ ko phải review đâu anh. Anh implement phần Customer: Renew, Cancel request: không quản lý giờ phút giây của startDate và expiredDate

**Comment by phucnguyen60749** [comment]
@trungdq88  a bít! tại nảy kha commit rồi nhưng mà vô bên staff vẫn thấy giờ phút giây thì notify cho kha thôi chứ a đã assign lại cho kha đâu! :)

**Comment by trungdq88** [comment]
Ok anh. Anh implement xong thì có thể assign lại cho em để em review.

**Comment by trungdq88** [comment]
@phucnguyen60749 anh gắn số vào commit message giùm em, nếu không thì anh copy link của commit trên trang này về paste vào comment giúp em. https://github.com/trungdq88/insurance-card/commits/master

**Comment by trungdq88** [comment]
Đã review :white_check_mark:
