### ISSUE TITLE
<Staff> Xử lý concurrency cho contract

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#217]
Các thao tác cần kiểm tra concurrency:

- [x] Gia hạn
- [x] Cancel
- [x] Thanh toán cho Pending

**Comment by trungdq88** [comment]
Đã xong. Anh @phucnguyen60749 review cái nhé.
Cách test: bật 2 trình duyệt, đăng nhập vào 2 tài khoản staff khác nhau và renew/cancel/complete payment cùng lúc.

**Comment by phucnguyen60749** [comment]
ok đã review (y)
