### ISSUE TITLE
<Public> Xử lý concurrency cho contract

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#219]
Các thao tác cần kiểm tra concurrency:

- [x] Thanh toán cho hợp đồng vừa tạo

**Comment by minhtridn2001** [comment]
@trungdq88 Em review cho a nhé Trung

**Comment by trungdq88** [comment]
Sửa lại: chỉ check concurrency ở những sự kiện có thay đổi contract.

**Comment by trungdq88** [comment]
Phải chờ #217, #218 làm xong mới review cùng lúc được.

**Comment by trungdq88** [comment]
Review ở #194. Close issue này.
