### ISSUE TITLE
<Staff> Lựa chọn: nên làm mờ hay biến mất nút.

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#220]
(Tách ra từ #206)

**Comment by hydrangea8604** [comment]
@minhtridn2001 Review dùm nha

**Comment by minhtridn2001** [comment]
@hydrangea8604 Kha làm cho nó đừng có hiện lên luôn được ko. Nhìn thấy nó hiện lên rồi biến mất cứ sao sao đó.

**Comment by hydrangea8604** [comment]
@minhtridn2001 Cũng nhận ra, để thử chuyển nó vào file .js xem, sợ là không được, bên này khác bên customer vài chỗ, không áp dụng nguyên si được mới đau.

**Comment by minhtridn2001** [comment]
@hydrangea8604  <c:if đó Kha

**Comment by trungdq88** [comment]
Cái nào dùng jsp xử lý được thì nên dùng chứ đừng có dùng JS nhiều quá. Anh Kha dùng cái `<c:if>` đi.

**Comment by hydrangea8604** [comment]
A lỡ hoàn thành bằng js rồi, giờ a commit lên luôn, còn vài task khác phải làm nữa, có để mai demo cho thầy trước. Cái file contract-detail.jsp cũng hơn 1000 dòng code rồi, vài hôm nữa a tách ra rồi mấy cái script a sẽ chuyển thành jstl luôn (những dòng có thể).

**Comment by trungdq88** [comment]
Ok vậy anh Trí xem xét close nếu ổn.

**Comment by hydrangea8604** [comment]
Ok, không còn vụ ẩn khi đang load nữa. @minhtridn2001 review lại dùm rồi close nha

**Comment by minhtridn2001** [comment]
Đã review :+1:
