### ISSUE TITLE
<Customer> Implement trang profile, chức năng đổi mật khẩu

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#221]

**Comment by phucnguyen60749** [comment]
@hydrangea8604  review dùm nha hiện tại chưa check độ mạnh yếu password

**Comment by hydrangea8604** [comment]
Độ dài mật khẩu có giới hạn mà.

**Comment by trungdq88** [comment]
Nghiêm trọng nè :warning:

```java
 if (customerEntity.getPassword().equalsIgnoreCase(dto.getCurrentPassword())) {
```

Mật khẩu lúc nào cũng phải PHÂN BIỆT HOA THƯỜNG, anh đừng có dùng `equalsIgnoreCase`.

**Comment by trungdq88** [comment]
Anh @hydrangea8604 review hết 1 lượt và liệt kê tất cả các bug để anh Phúc fix 1 lần luôn nha, đừng bắt lẻ tẻ.

**Comment by hydrangea8604** [comment]
Lúc a assign lại cho người khác tức là đã review xong rồi đó

**Comment by hydrangea8604** [comment]
À, suýt quên, lại dính dấu &times trên alert, sao lúc nào @phucnguyen60749 cũng bỏ cái dấu này vào vậy, đâu phải lúc nào cũng được close alert (hầu hết là không được)

**Comment by phucnguyen60749** [comment]
@trungdq88 và @hydrangea8604  vậy là bỏ cái dụ hoa, thường và bắt độ dài thoi đúng ko! ok

**Comment by phucnguyen60749** [comment]
@hydrangea8604 review lai dùm nua nha

**Comment by hydrangea8604** [comment]
Đã review, chiều dài của cái modal hơi rộng, sửa cũng được, không sửa cũng không sao.

**Comment by trungdq88** [comment]
Độ dài mật khẩu từ 6 đến 32 ký tự. Anh @phucnguyen60749 sửa lại nha.

**Comment by phucnguyen60749** [comment]
@trungdq88 ok em xem lại nhé !

**Comment by trungdq88** [comment]
Nghiêm trọng nè :warning: :warning: :warning: :-1: . File `personal-information.jsp`
```jsp
<input type="hidden" id="customerPass"
       value="${customer.password}"/>
```
Anh BẮT BUỘC phải kiểm tra mật khẩu ở phía server side. Để ở client như vậy là sai về nguyên tắc bảo mật.

Phần validate độ dài ok.

**Comment by trungdq88** [comment]
Cần bổ sung kiểm tra concurrency khi đổi mật khẩu (vì staff cũng có thể đổi mật khẩu hoặc thông tin cá nhân của người dùng).
Cách implement, tham khảo code ở trang staff: https://github.com/trungdq88/insurance-card/commit/53e472affa24200872fc19ce9471829d096b0d0a

**Comment by phucnguyen60749** [comment]
@trungdq88 a đã bỏ validate ở client chổ pass cũ! e xem lại nhé! close lun!

**Comment by trungdq88** [comment]
Ok.
Bỏ qua phần concurrency check vì không cân thiết.
