### ISSUE TITLE
<Customer> Renew: thêm thông tin startDate, expiredDate vào Payment

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#222]
Theo như report này: https://www.facebook.com/groups/insurancecard/permalink/877450318957243/

**Comment by phucnguyen60749** [comment]
@hydrangea8604  review dum nha tui sua trong customerbusiness phan renewContract

**Comment by minhtridn2001** [comment]
Để t review thay cho

**Comment by minhtridn2001** [comment]
Đã review :+1:
