### ISSUE TITLE
<Staff> Renew: thêm thông tin startDate, expiredDate vào Payment

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#223]
Theo như report này: https://www.facebook.com/groups/insurancecard/permalink/877450318957243/

**Comment by hydrangea8604** [comment]
@minhtridn2001 Review dùm nha trí. Hiện tại thì bảng payment ở trang contract-detail chưa hiển thị ngày bắt đầu và ngày kết thúc (không đủ diện tích, bỏ vào thì xấu) Cho nên t sẽ tạo issue mới để chỉnh sửa. Nếu review ngay thì ông tạm check trong database, không thì chờ issue kia hoàn thành nha

**Comment by hydrangea8604** [comment]
#224 Issue bổ sung

**Comment by minhtridn2001** [comment]
Đã review OK!
