### ISSUE TITLE
<Staff> contract-detail.jsp: Sửa lại thông tin hiển thị payment

### ISSUE THREAD

**Issue by hydrangea8604** [trungdq88/insurance-card#224]
Bỏ bớt cột trong bảng, tạo modal khi click vào paymentID sẽ hiển thị paymentDetailByID

**Comment by hydrangea8604** [comment]
Đã commit phần bỏ cột trong https://github.com/trungdq88/insurance-card/commit/246b7e1f963ad932412bfd5314fae9ab7602b99b
AJAX chưa làm được

**Comment by trungdq88** [comment]
Anh có thể gộp 2 cột người nhận và mã Paypal lại thành 1 cột cũng được: "Người nhận / Mã PayPal"

**Comment by hydrangea8604** [comment]
Đã hiển thị đầy đủ thông tin, commit lên để remove khỏi millestone. Mai có thời gian chỉnh lại cho đẹp sẽ close sau.

**Comment by hydrangea8604** [comment]
Đã commit kèm theo dummy data payment. @minhtridn2001 nếu thiếu data payment thì add nó vào để review nha. Trực tiếp thì không có paypal transaction id. Renew mới có ngày bắt đầu gia hạn và ngày kết thúc.

**Comment by minhtridn2001** [comment]
Kha ơi, hợp đồng PayPal vẫn hiện tên người nhận + thời gian trong Modal và trong table khác nhau.
![image](https://cloud.githubusercontent.com/assets/12363317/8479784/1efc9b7e-2104-11e5-9dbc-d94aad637231.png)

Hợp đông trực tiếp cũng bị sai thời gian:
![image](https://cloud.githubusercontent.com/assets/12363317/8479802/42132dbc-2104-11e5-81c5-b4261208cdbe.png)

**Comment by hydrangea8604** [comment]
@minhtridn2001 Gõ nhầm hàm getDate() thành getDay() :whale: Vụ người nhận thì luôn có, nếu nó trống là do database thiếu thôi.

**Comment by minhtridn2001** [comment]
@hydrangea8604  Mình đổi bussiness lúc nào vậy. Nếu là PayPal payment thì người nhận ko có mà.

**Comment by hydrangea8604** [comment]
Hồi chiều hôm qua t mới hỏi ông rõ ràng. Khi thanh toán PayPal có người nhận không, ông kêu có, người nhận là tài khoản PayPal của mình =.=!

**Comment by minhtridn2001** [comment]
Hôm qua ko biết là Kha hỏi trong bảng payment @@ Ý t là customer chuyển tiền vào tài khoản cty. 
Như vậy đâu có staff nào nhận đâu. Column receiver ở đây là staffCode mà.

**Comment by hydrangea8604** [comment]
@minhtridn2001 Đã commit sửa lại hiển thị người nhận rồi. :fireworks: :

**Comment by hydrangea8604** [comment]
Test thử reply bằng Outlook có được không :D

**Comment by minhtridn2001** [comment]
Done!
