### ISSUE TITLE
<Customer> Chỉnh sửa lại giao diện thông tin cá nhân.

### ISSUE THREAD

**Issue by hydrangea8604** [trungdq88/insurance-card#225]
![image](https://cloud.githubusercontent.com/assets/12366868/8448495/88eafc46-1ff2-11e5-8b63-946f33c81dba.png)

Chỉnh sửa các field cho fix với chiều dài của thông tin (fix content)

**Comment by phucnguyen60749** [comment]
@hydrangea8604 khi thu nhỏ màn hình giống màn hình máy chiếu thì các filed này sẽ tự co lại theo chiều dài chử mà

**Comment by hydrangea8604** [comment]
@phucnguyen60749 ảnh chụp trên màn hình chrome width=1000px đó

**Comment by trungdq88** [comment]
Anh @phucnguyen60749 : lúc ở chế độ xem thì nên để label chứ đừng dùng input và disable. Nhìn rất confuse.

**Comment by phucnguyen60749** [comment]
@hydrangea8604  review dùm nhé

**Comment by hydrangea8604** [comment]
![image](https://cloud.githubusercontent.com/assets/12366868/8458279/7738205c-2040-11e5-890a-4234da6406ec.png)
Không đọc comment trên của Trung hả?
Số điện thoại và hộ chiếu tối đa là 15, để dài như vậy làm gì.
Địa chỉ thì lại bị mất chữ, chiều dài của nó hình như tận 250 ký tự lận mà
Sao Ông Cứ Phải Viết Hoa Chữ Đầu Tiên Của Mọi Chữ Cái Vậy? Lần trước @trungdq88 có nhắc rồi mà.

**Comment by phucnguyen60749** [comment]
@hydrangea8604  pull về chưa vây! có pull về thì control F5! pull lại thử đi kha

**Comment by hydrangea8604** [comment]
Lần sau commit trước khi assign nha =.=!

**Comment by hydrangea8604** [comment]
Thì ông cũng là disable cái input đi thôi chứ có gì đâu, trừ lỗi đầu tiên, mấy cái lỗi khác vẫn còn mà

**Comment by phucnguyen60749** [comment]
@hydrangea8604  tui sữa cái viết hoa chử cái đầu tiên rồi! ông pull về nhé!

**Comment by hydrangea8604** [comment]
Commit thiếu số kìa

**Comment by hydrangea8604** [comment]
Khổ ông ghê, đã assign cho review, review báo lại vẫn không sửa, cái địa chỉ nó vẫn còn y nguyên kìa.

**Comment by phucnguyen60749** [comment]
@hydrangea8604  địa chỉ còn y nguyên là sao 
![untitled](https://cloud.githubusercontent.com/assets/12363394/8458971/59d20312-2044-11e5-8bab-fa69eef91e8e.png)

**Comment by hydrangea8604** [comment]
Sao có cái vấn đề nhỏ thôi mà ông cứ phải kéo ra hoài vậy ta. Mệt quá, địa chỉ tối đa 250 ký tự, nhập thử vào coi ra sao rồi tự quyết đi

**Comment by phucnguyen60749** [comment]
@hydrangea8604  ok ông close dùm nhé! địa chỉ tối đa 250 ký tự --> ong nói vay tui moi ko hieu nham chứ! hehe
