### ISSUE TITLE
Sửa database: Tạo column created_date bảng mic_contract

### ISSUE THREAD

**Issue by minhtridn2001** [trungdq88/insurance-card#226]
- [x] Tạo coumn created_date bảng mic_contract.
- [x] Sửa ContractEntity.

**Comment by trungdq88** [comment]
Field có tự sinh giá trị không anh @minhtridn2001 ? Có cần đổi lại code ở các chỗ tạo contract entity mới không?

**Comment by hydrangea8604** [comment]
Bên staff không cần thêm gì, mới test thử create new contract thì không có vấn đề,database có giá trị

**Comment by trungdq88** [comment]
:+1: Ok chính xác rồi. `created_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,`

**Comment by minhtridn2001** [comment]
Thêm cái này vào nữa thì nó ko bắt insert : @Column(name = "created_date", insertable=false)
