### ISSUE TITLE
<Customer> Thanh toán renew contract hiện Nội dung thanh toán sai

### ISSUE THREAD

**Issue by minhtridn2001** [trungdq88/insurance-card#227]
startDate và expiredDate lúc gia hạn thì đúng rồi. Mà cái payment description sai thôi
![image](https://cloud.githubusercontent.com/assets/12363317/8455924/40bfdc4e-2032-11e5-81e3-44bc6dd72e7c.png)

**Comment by phucnguyen60749** [comment]
@minhtridn2001  sai chổ nào trí ơi! hihi

**Comment by minhtridn2001** [comment]
Đáng lẽ description phải là từ ngày new startDate - new expiredDate. Mà đây lại là old expiredDate - new expiredDate.

**Comment by phucnguyen60749** [comment]
@minhtridn2001  cái này trí review lại dùm cho nhanh nha

**Comment by minhtridn2001** [comment]
OK!
