### ISSUE TITLE
<Staff> Sửa lại tất cả use case specification dựa trên thay đổi trong quá trình làm

### ISSUE THREAD

**Issue by hydrangea8604** [trungdq88/insurance-card#228]
- [x] Resolve new card request
- [x] Resolve compensation request
- [x] View customer information
- [x] Create new customer
- [x] Create new contract
- [x] Renew contract
- [x] Cancel contract
- [x] Update contract information
- [x] Update compensation history
- [x] Update punishment history
- [x] Update accident history
- [x] View cards information

Bổ sung thêm khi tìm thấy lỗi ở use case specs khác.

**Comment by trungdq88** [comment]
Issue gì mà chung chung quá vậy anh?

**Comment by hydrangea8604** [comment]
Thì cứ mò vào thấy chỗ nào khác vào đây update lại description thôi, chứ giờ làm sao a biết cái use case nào bị sai.

**Comment by trungdq88** [comment]
Ok, :+1: thanks vì đã re-view document thường xuyên.

**Comment by trungdq88** [comment]
Nếu anh có thể liệt kê cụ thể các phần cần chỉnh sửa thì mình có thể tách issue này ra để cùng làm chung. Có vẻ nhiều.

**Comment by hydrangea8604** [comment]
### WS03
##### Change
- *lost card* to **old card**
- *date of request in descending order* to **resolved date in ascending order**
- *card or customer faster* to **card faster by its id**

##### Deletion
- *and auto-change based on staff’s selection*
- *Staff can select how many requests should be displayed in user view, default is 10 requests.*
- *A notification will be sent to request customer after the process is completed.*

### WS04
##### Addition
- **Compensation created date: text**
- **Compensation status: text**
- **Address of the observer: text**
- **Compensation attachment: link to attachment detai**
- **Staff send resolve this compensation request command**
- **Resolve compensation request view is shown with following labels and fields**
- **Resolve date: date time input, required**
- **Đã giải quyết, Chưa giải quyết**
- **Compensation resolved date must be restrict in the limit by configuration of the administrator.**

##### Change
- *Request’s code* to **Compensation code**
- *Get request date* to **Request created date**
- *Request solved date* to **Request status**
- Move *Compensation note, decision* from step 3 to step 4
- *no unsolved compensation* to **no compensation**
- *get request date in descending order* to **compensation request resolved date and created date in ascending order**
- *three status is* to **following status**

##### Deletion
- *Status of compensation: select one of the options.*
- *, included decision, description and request’s status*
- *Đang xử lý, Hoàn tất, Hủy bỏ*
- *and auto-change based on staff’s selection*
- *Staff can select how many requests should be displayed in user view, default is 10 requests.*
- *A notification will be sent to request customer after the process is completed.*

**Comment by trungdq88** [comment]
:+1:

**Comment by hydrangea8604** [comment]
### WS04
##### Addition
- **A notification will be sent to request customer after the process is completed.**
- **and select one from two decision** to step 4

##### Change
- *three decision is* to **following decision**
- *Note for compensation from staff: free text input* to **Note for compensation: free text input, length 1 – 2000**

##### Deletion
- *Chưa quyết định*
- *Decision: select one of the options*

### WS05
##### Change
- *Customer’s NFC card ID: link to card detail* to **Customer’s email address: text**

##### Deletion
- *Customer’s contract code: link to contract detail*
- *Customer’s full name: text* to **Customer’s code: link to customer detail**
- *List of customer’s card:*
-	*Customer’s NFC card ID: link to card detail.*
-	*Card’s activated date: text*
-	*Card’s most recent access date: text*
-	*Card’s access history: link to card access history.*
- *Contract’s expired date: text*
- *Staff can view all customer’s card and each card’s access history*
- *and auto-change based on staff’s selection*
- *Staff can select how many requests should be displayed in user view, default is 10 requests.*

**Comment by hydrangea8604** [comment]
### WS07
##### Addition
- **Exception 4**
- **Entered email is existed in the system**
- **Show message notify entered email is existed**

### WS08
##### Addition
- **List of contract’s type must be loaded from the system**
- **Contract’s fee is calculated by the following formula, with price per year is loaded from the system belongs to selected contract type:**
- **contract fee =  price per year/12  × contract term**
- **Contract’s term will be rounded up to nearest month, for example: 2 months 18 days is 3 months**

##### Change
- *length 6* to **length 6 – 10**
- *No Card* to **No card**
- *exceed 1 year* to *exceed contract's default term*
- *is 1 year* *is set up by the configuration of administrator*
- *Contract’s start date must not be earlier than create contract date* to **Contract’s start date, expired date, paid date must be restricted in the limit by configuration of the administrator**

##### Deletion
- *Contract’s type must be one of the following values:*
-	*“Xe trên 50cc có BH cho người trên xe”*
- *“Xe trên 50cc không có BH cho người trên xe”*
- *“Xe dưới 50cc có BH cho người trên xe”*
- *“Xe dưới 50cc không có BH cho người trên xe”*
- *“Xe mô tô ba bánh, xe gắn máy và các loại xe tương tự”*

### WS09
##### Addition
- **The contract type belongs to this contract is NOT deactivated yet.**
- **Contract remaining days must NOT exceed the limit in administrator’s configuration.**
- **Contract’s fee is calculated by the following formula, with price per year is loaded from the system belongs to current contract type:**
- **contract fee =  price per year/12  × contract term**
- **Contract’s term will be rounded up to nearest month, for example: 2 months 18 days is 3 months**
- **Contract’s code: text**
- **Contract’s status: text**
- **Contract’s type: text**
- **Contract’s status: text**
- **Contract’s expired date: text**
- **Request for new card: free text input
- **New card fee: text**
- **Delivery new card: free text input**
- **Delivery new card fee: text**
- **New card fee & delivery card fee must by loaded from the system.**
- **User only can request for new card if this contract owns an activating card.**


##### Change
- *No Card* to **No card**
- *exceed 1 year* to *exceed contract's default term*
- *is 1 year* *is set up by the configuration of administrator*
- *Contract’s start date must not be earlier than create contract date* to **Contract’s new expired date, paid date must be restricted in the limit by configuration of the administrator**

##### Deletion
- *The payment process for renew contract was completed*
- *Payment information:*

**Comment by hydrangea8604** [comment]
### WS10
##### Addition
-	**Contract’s status must be “Pending”, “No card” or “Ready”.**
- **While contract cancelled successfully, there are no notification would be sent to the customer who own this contract**
- **Contract’s cancel date must be restricted in the limit by configuration of the administrator**

##### Change
- *Request cancel* to **Pending**

##### Deletion
-	*Contract’s status must not be “Cancelled” or “Expired”.*
-	*The expired date is less than 2 months.*
-	*The compensation for breach of contract was completed.*
-	*No notification will be sends to user when a staff cancel a contract*

### WS10
##### Addition
- **Contract general information**
- **Contract’s code: text**
- **Contract’s status: text**
- **Contract’s type: text**
- **Contract’s expired date: text**
- ****
- ****

##### Change
- ** to ****

##### Deletion
- *or “Expired”*
- *Personal information*
-	*Name: free text input, required, length 3 – 80.*
-	*Address: free text input, required, length 3 – 250.*
-	*Email: free text input, required, length 3 – 250.*
-	*Phone number: free text input, required, length 8 – 15.*
-	*Personal ID: free text input, length 15.*
- *Contract information (all information below are required)*
-	*Contract’s type: select one from the options.*
-	*Start date: date time input*
-	*Expired date: date time input*

**Comment by hydrangea8604** [comment]
### WS12
##### Addition
-	**Contract code: free text input, required, length 6 – 10**
-	**Staff can search and select a contract from available contract in the system**
-	**Created date must not exceed current date.**
-	**Accident date must not exceed created date.**
-	**If the compensation request has not been resolved yet, it would not have resolve date, decision and resolve note.**

### WS13
##### Addition
- **If contract status is “Expired” or “Cancelled”, must not exceed update contract due date has been set up in the administrator’s configuration.**

### WS14
##### Addition
- **If contract status is “Expired” or “Cancelled”, must not exceed update contract due date has been set up in the administrator’s configuration.**

##### Change
-	*Contract of the accident* to **Accident**

### WS15
##### Addition
-	**Contract code: link to contract detail**
-	**Activated date: text**
- **Access history:**
-	**Access date: text**
-	**Device: text**
-	**Request service: text**
-	**Responde result: text**
**Published history**
-	**Contract code: link to contract detail**
-	**Activated date: text**
-	**Deactivated date: text**

##### Change
-	*text link to card detail* to **link to card detail**
-	*Card owner: text* to **Card owner: link to customer detail**

##### Deletion
-	*Last access time: text*
-	*History of access*

**Comment by hydrangea8604** [comment]
@trungdq88 Review lại dùm nha, cảm ơn nhiều

**Comment by trungdq88** [comment]
:+1: Very well documented. Có một số lỗi anh fix nhé.

- [ ] Những chỗ "01" thì ghi là "1" thôi. VD: WS03 / Preconditions / gạch đầu dòng thứ 2 (và một số chỗ khác nữa)
- [ ] WS03 / Preconditions / bị thừa "-	The payment process for new card was completed."
- [ ] WS09 / Business rule: bỏ 2 gạch đầu dòng cuối, lý do là cần tách biệt giữa renew và yêu cầu thẻ mới ra chứ ko để gộp như vậy.
- [ ] WS12 / Preconditions: thiếu điều kiện 30 ngày bổ sung sau khi hủy.
- [ ] WS12 / Business rule: lỗi nhỏ, tiện tay fix luôn: "exeed"

**Comment by hydrangea8604** [comment]
@trungdq88 Đã sửa những lỗi trên, cảm ơn Trung :+1:

**Comment by trungdq88** [comment]
Done.
