### ISSUE TITLE
<Staff> Validate server-side theo staff configuration.

### ISSUE THREAD

**Issue by hydrangea8604** [trungdq88/insurance-card#229]
- [x] Create new contract
- [x] Renew contract: config
- [x] Cancel contract
- [x] Complete payment

**Comment by hydrangea8604** [comment]
@minhtridn2001 gelato :shaved_ice:

**Comment by minhtridn2001** [comment]
@hydrangea8604 
- [ ] Thêm vào 2 cái default term như đã nói.
- [ ]  expiredDateMax hiện tại chỉ lấy LocalTime + defaultTerm thôi. Trường hợp ng dùng chọn startDate < LocalTime thì expiredDate bị sai.

**Comment by trungdq88** [comment]
Task này nằm trong #344, nhưng phải xong ở milestone 9.1.

**Comment by hydrangea8604** [comment]
@minhtridn2001 :sob:

**Comment by minhtridn2001** [comment]
@hydrangea8604  Còn bên renewContract nữa ng đẹp

**Comment by minhtridn2001** [comment]
Thôi để sửa cho

**Comment by minhtridn2001** [comment]
OK!
