### ISSUE TITLE
New card request: implement chức năng cấp thẻ mới ở trang renew.

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#231]

**Comment by trungdq88** [comment]
Chức năng yêu cầu thẻ mới đã xong: #238
Anh có thể tạo thêm yêu cầu request nếu staff chọn checkbox "Cấp thẻ mới" bây giờ được rồi.

**Comment by trungdq88** [comment]
@hydrangea8604 : quên mất, issue này phải làm trong milestone này.

**Comment by trungdq88** [comment]
@hydrangea8604 có làm kịp không anh, hôm trước thầy nhắc issue này rồi, đợt này mà chưa làm nữa thì không trả bài được :(

**Comment by hydrangea8604** [comment]
A làm từ chiều giờ mà vẫn chưa xong @@ Mò mãi cái tính tiền rồi bỏ qua, giờ đang làm cái core

**Comment by trungdq88** [comment]
Tính tiền thì cứ + thêm phí cấp thẻ mới vào phí gia hạn là được rồi. Sau đó thì tạo new card request và gửi notification, tìm trong business của customer/new card request.

**Comment by hydrangea8604** [comment]
Ok, back-end đã xong, front-end xong được 1 nửa.

**Comment by hydrangea8604** [comment]
@minhtridn2001 review lại dùm nha

**Comment by minhtridn2001** [comment]
Đã review :+1:
