### ISSUE TITLE
<Staff> 3-steps create new contract

### ISSUE THREAD

**Issue by hydrangea8604** [trungdq88/insurance-card#232]
- [x] Create new contract: implement select/search customer, load customer's information and update the order of fields.
- [x] Review: implements review page.
- [x] Success: change the way display created contract (doesn't use table to display 1 item)

**Comment by hydrangea8604** [comment]
Phần chọn khách hàng để sau, làm AJAX mò lâu quá

**Comment by hydrangea8604** [comment]
Phát hiện bug, để tự sửa

**Comment by hydrangea8604** [comment]
@minhtridn2001 đã sửa, có thể review

**Comment by minhtridn2001** [comment]
- [ ] Validate server side Thời điểm hết hiệu lực lúc Create Contract bị sai.

**Comment by hydrangea8604** [comment]
@minhtridn2001 Đã validate server, client sẽ làm tại issue #344

**Comment by minhtridn2001** [comment]
OK!
