### ISSUE TITLE
<Staff> List/View/Add/Edit compensation

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#233]
- [x] List all
- [x] List by contract
- [x] Add
- [x] View detail
- [x] Resolve
- [x] Edit

**Comment by hydrangea8604** [comment]
@minhtridn2001 Đã implement và commit 3 chức năng trên, Trí xem rồi review dần nhà, cái này phải nhập nhiều lắm đó.

**Comment by minhtridn2001** [comment]
@hydrangea8604 Ngày xảy ra phải trước ngày gửi yêu cầu. Cái link Biên bản có implement luôn chưa hay để sau Kha

**Comment by hydrangea8604** [comment]
Ngày xảy ra tai nạn cùng ngày với ngày gởi yêu cầu cũng được. Sáng bị tai nạn chiều ra báo :+1: Còn link biên bản thì để sau đi, giờ Form Reader cũng chưa có upload file.

**Comment by minhtridn2001** [comment]
Uk ngày xảy ra tai nạn phải trước hoặc cùng ngày gửi yêu cầu :D

**Comment by hydrangea8604** [comment]
Đã implement resolve và edit compensation. Phần edit chưa tìm được cách điền giá trị trả về khi validate fail nên nó sẽ load lại giá trị cũ.

**Comment by trungdq88** [comment]
:+1: cho phần resolve.

**Comment by minhtridn2001** [comment]
Review OK :+1:  Nhưng có điều này là ko nên sort danh sách bồi thường theo hợp đồng. Vì khi staff giải quyết thì phải ưu tiên giải quyết những Yêu cầu buồi thường được tạo sớm hơn.
Kha xem có nên sort nó theo Trạng thái ( resolve date) và created date để ưu tiên những hợp đồng tạo trước và chưa đc giải quyết lên trên được ko nhé.
@hydrangea8604 Xong thì Kha tự close nhé.

**Comment by hydrangea8604** [comment]
#258 Add, edit
