### ISSUE TITLE
<Staff> List/View/Add/Edit punishment

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#234]
- [x] List by contract
- [x] Add
- [x] Edit

**Comment by hydrangea8604** [comment]
@minhtridn2001 Review dùm nha. Cái này y chang accident nên nếu 1 cái sai code hoặc sai business thì cả hai đều sai, còn nếu 1 cái đúng thì chỉ cần review giao diện + chữ viết là được. Cảm ơn :+1:

**Comment by minhtridn2001** [comment]
@hydrangea8604 Trang edit link trở về hợp đồng bị sai giống accident

**Comment by hydrangea8604** [comment]
#258 Implement File Upload for FormReader
