### ISSUE TITLE
<Staff> List/View/Add/Edit accident

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#235]
- [x] List by contract
- [x] Create
- [x] Edit

**Comment by hydrangea8604** [comment]
Implements edit an accident	7f4bebe

**Comment by hydrangea8604** [comment]
@minhtridn2001 Review dùm nha Trí

**Comment by minhtridn2001** [comment]
@hydrangea8604 Trang edit link trở về hợp đồng bị sai nha.
Phần đính kèm có nên giới hạn định dạng file ko? Hoặc khi nào implement thì sửa cũng đc.

**Comment by trungdq88** [comment]
Phần upload file hiện tại milestone này chưa cần làm nha.
