### ISSUE TITLE
<Staff> View new card requests

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#236]

**Comment by minhtridn2001** [comment]
Trang card detail chưa làm nên a để tạm cái link # nhé

**Comment by trungdq88** [comment]
:+1: Ok, chỉ có một vấn đề nhỏ, anh format lại ngày tháng thành định dạng `dd/MM/yyyy` ở 2 cột Thời gian và Ngày cấp mới nhé.
Sửa xong anh có thể tự close.
