### ISSUE TITLE
Implement notification

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#237]
### 1. Definition
Notification is a feature of MIC Web application to notify stakeholders when important events occurs.

### 2. Notification methods
- Send email
- Show notification icon on web interface

### 3. Notification use cases
Type | Trigger send notify | Receiver | Notify method | Close notify trigger
------- | ------------------------ | ------------ | ------------------- | --------------------
1 | Customer creates new contract | All staff | Web | Mark as read
2 | Customer sends compensation request | All staff | Web | Staff resolves compensation
3 | Customer sends new card request | All staff | Web | Staff prints new card
4.1 | Contract is nearly expired (send first) | Customer | (by scheduler) Web, Email | Customer or Staff renew the contract
4.2 | Contract is nearly expired (send 2nd time) | Customer | (by scheduler) Web, Email | Customer or Staff renew the contract
4.3 | Contract is nearly expired (send 3rd time) | Customer | (by scheduler) Web, Email | Customer or Staff renew the contract
5 | Contract is expired | Customer | (by scheduler) Web, Email | Customer or Staff renew the contract
6 | Customer sends request cancel | All staff | Web | Staff resolves request cancel or Customer rejects the request cancel
7 | Contract is cancelled because payment due date exceed | Customer | (by scheduler) Web (Staff and Customer), Email (Customer) | Mark as read
8 | Paid Pending Contract start date come | Customer | (by scheduler) Web | Mark as read

* For staffs, every notification has "status" to show that if the notification not resolved or when the notification is resolved and by whom. Except Type 1 notification has no status.
* All the notification can be handedly turned off by clicking Mark as read button
* When a notification is sended to all the staff, each staff has their own "Read" status. That's mean if staff A mark the status as read but staff B still see it as not read.

#### 4.1. Table `mic_notification`
This table contains all the notifications sent in the system

Field name | Type | Description
--------------- | ------ | ---------------
id | `int` | Auto increments unique ID
content | `varchar(2000)` | Content of the notification
type | `int` | Type of the notification
extra_data | `varchar(2000)` `nullable` | Custom data for each type, ex: type 1 will store `contract_code`
receiver | `varchar(250)` | Regex pattern. All the user have the code match this pattern will receive the notification
method | `int` | Value `1` for web, `2` for email and `0` for both (this use bitwise operator as flag variable)
created_date | `datetime` | When the notification is sent
resolved_date | `datetime` `nullable` | When this notification is resolved, `null` if not resolved, equals to `created_date` if don't need to be resolved.
resolved_staff | `varchar(10)` `nullable` Foreign `staff.id`| Who resolved this notification, `null` if not resolved or don't need to be resolved.

```sql
CREATE TABLE `mic_data`.`mic_notification` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(2000) NOT NULL,
  `receiver` VARCHAR(250) NOT NULL,
  `method` INT NOT NULL,
  `type` INT NOT NULL,
  `extra_data` VARCHAR(2000) NULL,
  `created_date` DATETIME NOT NULL,
  `resolved_date` DATETIME NULL,
  `resolved_staff` VARCHAR(10) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_resolved_staff_staff_code_idx` (`resolved_staff` ASC),
  CONSTRAINT `fk_resolved_staff_staff_code`
    FOREIGN KEY (`resolved_staff`)
    REFERENCES `mic_data`.`mic_staff` (`staff_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
```

#### 4.2 Table `mic_notification_read`
This table describes who read which notification

Field name | Type | Description
--------------- | ------ | ---------------
id | `int` | Auto increments unique ID
code | `varchar(10)` | User code, could be staff code or customer code
is_read | `int` | Has value `1` if the user read the notification or mark the notification as read

```sql
CREATE TABLE `mic_data`.`mic_notification_read` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_code` VARCHAR(10) NOT NULL,
  `is_read` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uq_user_code_is_read` (`user_code` ASC, `is_read` ASC));
```

**Comment by trungdq88** [comment]
Commit: https://github.com/trungdq88/insurance-card/commit/e99fa37dac037385edfefdbde9e3826a524527f5 Add database.

**Comment by trungdq88** [comment]
Các trigger cần implement:
- [ ] Customer creates new contract	
- [ ] Customer sends compensation request	
- [ ] Customer sends new card request	
- [ ] Contract is nearly expired (send first)	
- [ ] Contract is nearly expired (send 2nd time)	
- [ ] Contract is nearly expired (send 3rd time)	
- [ ] Contract is expired	
- [ ] Customer sends request cancel	
- [ ] Contract is cancelled because payment due date exceed	
- [ ] Paid Pending Contract start date come

**Comment by trungdq88** [comment]
Đã implement xong notification cơ bản. Vì issue này khá lớn cho nên mọi người ai **đã làm xong task của mình** thì vào review giúp em nhé. Có bug thì report ngay trong issue này nha.

@minhtridn2001 @hydrangea8604 @phucnguyen60749 

Các trigger cần test:
- [ ] 1. Customer creates new contract (public page and customer page) :white_check_mark: web
- [ ] 2. Customer sends compensation request	:white_check_mark: web
- [ ] 3. Customer sends new card request	:white_check_mark: web
- [ ] 4.1. Contract is nearly expired (send first) (scheduler)	:white_check_mark: web :white_check_mark: email
- [ ] 4.2. Contract is nearly expired (send 2nd time) (scheduler)	:white_check_mark: web :white_check_mark: email
- [ ] 4.3. Contract is nearly expired (send 3rd time) (scheduler)	:white_check_mark: web :white_check_mark: email
- [ ] 5. Contract is expired  (scheduler)	:white_check_mark: web :white_check_mark: email
- [ ] 6. Customer sends request cancel	:white_check_mark: web
- [ ] 7. Contract is cancelled because payment due date exceed  (scheduler)	:white_check_mark: web :white_check_mark: email
- [ ] 8. Paid Pending Contract start date come (scheduler) :white_check_mark: web

**Comment by minhtridn2001** [comment]
@hydrangea8604 Kha review phụ phần này nha. T review trên xuống. Kha từ dưới lên nhé

**Comment by minhtridn2001** [comment]
Đã test 1,2,3. OK. Đã test với 2 staff cùng đăng nhập. Nhưng có điều là cho notification tự hiện mà ko cần chờ F5 ko em? Với lại chức năng đánh dấu chưa đọc notification, a thấy nó ko ổn định. Lúc được lúc ko, đặc biệt khi đã read hết notification rồi thì đánh dấu chưa đọc ko được(F5 lại mất).

**Comment by hydrangea8604** [comment]
- [ ] Hợp đồng đang Pending, không có thông tin payment, bị scheduler update thành No card.

**Comment by trungdq88** [comment]
@hydrangea8604 em không tái tạo được lỗi, điều kiện ngày tháng thế nào anh?
Phần này thuộc về scheduler, anh @minhtridn2001 double check lại các trường hợp của scheduler thử nha.

**Comment by minhtridn2001** [comment]
@hydrangea8604 Vậy TH này database của Kha bị sai rồi. Kha kiểm tra giúp t xem nếu hợp đồng pending thì startDate và expiredDate có bằng nhau ko nha.

**Comment by hydrangea8604** [comment]
Vậy là do chỉnh sửa database để test sai đó. Tại vì bên staff, hợp đồng Pending mà không có payment thì là chưa thanh toán, còn đã có payment thì là chưa kích hoạt, không quan tâm ngày tháng.

**Comment by trungdq88** [comment]
Ok vậy còn lỗi nào khác nữa không anh. Trường hợp này thì sao nhỉ:

> Với lại chức năng đánh dấu chưa đọc notification, a thấy nó ko ổn định. Lúc được lúc ko, đặc biệt khi đã read hết notification rồi thì đánh dấu chưa đọc ko được(F5 lại mất).

**Comment by hydrangea8604** [comment]
Hồi sáng a chỉ test 1 customer, 1 staff, mỗi cái ở 2 trình duyệt thì ổn, không có vấn đề. 2 staff ở 2 trình duyệt thì chưa kịp thử.

**Comment by trungdq88** [comment]
Vẫn còn các trường hợp 4.1, 4.2, 4.3, 7, 8. Ai rảnh thì review giúp để em close issue.
@phucnguyen60749 @hydrangea8604

**Comment by phucnguyen60749** [comment]
Contract is nearly expired (send first) (scheduler) đã review ok

**Comment by hydrangea8604** [comment]
7. Contract is cancelled because payment due date exceed (scheduler)
Web staff/customer đều có notification nhưng lại không có email. Đã check lại email chính xác, trước đó có test số 5 vẫn nhận được email.
![image](https://cloud.githubusercontent.com/assets/12366868/8526918/babc1d96-2433-11e5-9047-fe06b3485a72.png)

**Comment by hydrangea8604** [comment]
Số 8 Paid Pending Contract start date come không hiểu rõ test như thế nào.
A test với hợp đồng này:
![image](https://cloud.githubusercontent.com/assets/12366868/8527156/50d4b9b8-2435-11e5-9c7e-05fa21a4680d.png)
Giờ hệ thống đang đúng thì không thấy notification gì cả.

**Comment by hydrangea8604** [comment]
Update lại contract
![image](https://cloud.githubusercontent.com/assets/12366868/8527252/ed3f840e-2435-11e5-89c9-a2c574ec474d.png)
Chỉnh ngày hệ thống lại thành ngày 9 tháng 7 cũng không thấy gì

**Comment by trungdq88** [comment]
> Số 8 Paid Pending Contract start date come không hiểu rõ test như thế nào.

Do dữ liệu trong database bị sai. startDate = expiredDate thì scheduler xem như là chưa thanh toán cho nên ko có notification.

**Comment by trungdq88** [comment]
Close.
