### ISSUE TITLE
<Customer> New card request

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#238]

**Comment by minhtridn2001** [comment]
- [x] New card request page
- [ ] Validate input client + server side + giới hạn chỉ not expired contract mới đc phép yêu cầu
- [ x] Payment

**Comment by trungdq88** [comment]
**Lỗi nghiêm trọng:**

Khi một request new card được thêm vào thì **Thêm một record vào `mic_new_card_request`, field old_card chứa card_id của card cũ**

Khi một thẻ mới được cấp dựa trên new_card_request thì **thêm một record vào `mic_card`, field `new_card_request_id` chứa id của cái `mic_new_card_request` record.**

Hiện tại ở bảng `mic_card`, field `new_card_request_id` lại lưu id của record `mic_new_card_request` (hoàn toàn vô nghĩa)

**Comment by trungdq88** [comment]
Các lỗi khác:
- [ ] Khi nhấn nút Yêu cầu thẻ mới thì nên gửi request GET (hiện tại đang gửi POST)

**Comment by trungdq88** [comment]
### Lỗi nghiêm trọng:

- Khi một request new card được thêm vào thì **Thêm một record vào `mic_new_card_request`, field old_card chứa card_id của card cũ**. KHÔNG ĐƯỢC SỬA BẤT CỨ GÌ TRONG BẢNG `mic_card`
- Khi một thẻ mới được cấp dựa trên new_card_request thì **thêm một record vào `mic_card`, field `new_card_request_id` chứa id của cái `mic_new_card_request` record.**

**Hiện tại đang làm sai:**
- Bảng `mic_card`, field `new_card_request_id` lại lưu id của record `mic_new_card_request` (hoàn toàn vô nghĩa) 
- Bảng  `mic_card`, field `deactivated_date` có giá trị được gán (SAI), card sẽ bị deactive khi thẻ mới được cấp, không deactive ở bước này.

### Các lỗi khác:
- [ ] Khi nhấn nút Yêu cầu thẻ mới thì nên gửi request GET (hiện tại đang gửi POST)
- [ ] Code của anh lúc nào cũng dùng rất nhiều vòng if lồng nhau, tạo nên logic rất khó hiểu và khó maintain, em khuyến khích anh nên viết lại theo kiểu làm từng bước. Hạn chế if lồng nhau.
- [ ] Câu query này sai:

```java
        String hql = "SELECT ca FROM CardEntity ca WHERE ca.contractCode = :contractCode " +
                "AND ca.deactivatedDate = NULL";
```

Anh lưu ý là tại một thời điểm 1 hợp đồng có thể có NHIỀU THẺ BỊ DEACTIVE. Cộng thêm theo như lỗi bên trên (không deactive card cũ khi gửi request) thì câu query này cũng sai.

- [ ] Lúc gửi request xong mà thanh toán trực tiếp thì nên chuyển về trang message.jsp chứ đừng hiện message ở trang contract detail như vậy

**Comment by minhtridn2001** [comment]
@trungdq88 OK. a tưởng ngày xưa mình thống nhất nếu báo mất thẻ thì phải deactive thẻ cũ tránh sử dụng.

**Comment by minhtridn2001** [comment]
Em review lại xem Trung.

**Comment by minhtridn2001** [comment]
Nếu 1 hợp đồng đã được phát hành thẻ. Thì luôn luôn lúc nào cũng có 1 thẻ hiệu lực với hợp đồng đó. Thẻ cũ chỉ bị deactive khi được cấp thẻ mới. Ko còn trường hợp hết hạn hay ntn khác phải ko Trung?

**Comment by trungdq88** [comment]
> Nếu 1 hợp đồng đã được phát hành thẻ. Thì luôn luôn lúc nào cũng có 1 thẻ hiệu lực với hợp đồng đó. Thẻ cũ chỉ bị deactive khi được cấp thẻ mới. Ko còn trường hợp hết hạn hay ntn khác phải ko Trung?
Đúng rồi anh, vì chức năng đó tên là "Cấp thẻ mới", có thể mình sẽ có thêm 1 nút deactive thẻ trong trang card detail. (sẽ xem xét sau).

**Comment by trungdq88** [comment]
Em nhớ là có một trang hiển thị tất cả các yêu cầu cấp thẻ mới ở trang customer, sao giờ không thấy nhỉ?

Cần phải có chỗ để customer biết mình đang có những new card request nào. Anh implement thêm trang đó luôn nha.

**Comment by minhtridn2001** [comment]
OK em
