### ISSUE TITLE
<Customer> List/View/Add compensation

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#239]

**Comment by phucnguyen60749** [comment]
@hydrangea8604  review dum nha

**Comment by hydrangea8604** [comment]
Vừa vào trang detail đã chuyển qua tab compensation?
Trang tạo mới mã hợp đồng và tên khách hàng cần thiết? Khách hàng login vào tài khoản của mình, thông tin đương nhiên phải là của mình. Mà cho dù có cần thì nó cũng chưa được gắn link.
Copy lại bên staff đi, bên đó mới sửa vài chỗ, dưới cái button gởi yêu cầu có 1 cái br. Copy mà cũng thiếu.
![image](https://cloud.githubusercontent.com/assets/12366868/8507491/9ffac87e-226f-11e5-9429-3482a769eeb5.png)
Không tự review trước khi commit?

**Comment by phucnguyen60749** [comment]
@hydrangea8604  
chuyển qua bên tab compensation là để cho dễ test! 
ông tạo compensation mới có insert dc vô db ko đó là result và test! 
ông test như thế nào vậy!????
mã hợp đồng và tên khách hàng là của thằng customer chứ! thông tin bên customer sao giống bên staff dc!  
cái ngày tạo và ngày giải quyết đâu cần đưa vô để làm gì! quá dư thứa!
đã test kĩ chưa mà kêu chưa review!

**Comment by hydrangea8604** [comment]
Ông có nhìn thấy cái hình to đùng không? Còn sót code giả nguyên như vậy mà còn kêu đã tự review?
Việc tạo + insert vào database không nói gì tức là tạo được.
Làm quái gì có cái ngày giải quyết nào? Đó là ngày xảy ra tai nạn của người ta cũng đem đi bỏ. Bên customer thì ngày tạo ẩn đi, nhưng ngày tai nạn vẫn phải có, và nó không được phép sau ngày hiện tại.
Mã hợp đồng và tên khách hàng là của customer, cho nên customer chẳng lẽ không biết thông tin của mình? Đưa vào đó có cần thiết không? Nếu cần thiết thì sửa lại nó thành cái link. Chỉ vậy thôi, giống Staff cái gì? Bên Staff đâu có cái đó.

**Comment by phucnguyen60749** [comment]
@hydrangea8604 code giả chổ nào!
ông có view source code ko mà nói code giã! hay ông pull bị gì!
ông kiểm tra coi có ${sessionScope.userDto.userEntity.name} ngay chổ tên khách hàng ko mà nói giả!
lần sau test! 
- lỗi gì (giao diện, business), mức độ, solution (nếu có), demo lỗi
- đừng nói linh tinh vậy! 
- nên tham khảo cách @trungdq88  review

**Comment by hydrangea8604** [comment]
Bực mình ghê, đọc lại coi chỗ nào nói mã hợp đồng và tên khách hàng là giả? T nói là nó chưa được gắn link và hỏi nó có cần thiết không.
Pull bị quái gì, mới pull lại, mới redeploy lại để check. Cái tấm hình đó là ở trang create compensation, thấy cái alert màu xanh không? Nó là ở trang create compensation. Cái chữ COM348 + label đang giải quyết không phải là giả thì là cái gì?
Ok, lần sau để @trungdq88 review của ông.

**Comment by phucnguyen60749** [comment]
@hydrangea8604 có vẽ tui vs ông chưa hiểu nhau lắm!
 nhưng mà ong gi bug thì ngắn gọn và xúc tích thôi
 lỗi gì (giao diện, business), mức độ, solution (nếu có), demo lỗi
- ok! với lại mỗi lần tui commit đương nhiên tui phải tự review tới mức mình ko phát hiện nữa thì mới đưa ông review chứ! 
- ông review có problem ok assign lại cho tui! xong

**Comment by trungdq88** [comment]
Em sẽ review issue này. Các issue khác vẫn theo vòng review cũ.

**Comment by trungdq88** [comment]
- [ ] Ở trang nhập thông tin, mã hợp đồng và tên khách hàng hiện tại đang link tới trang .html, sửa link lại cho đúng trang.
- [ ] Ở trang nhập thông tin, sửa lại tiêu đề, hiện tại lúc nào cũng hiện "Yêu cầu bồi thường COM384", bỏ luôn cái label "Đang giải quyết" màu vàng bên cạnh.
- [ ] Ở trang nhập thông tin mới chỉ hiện mỗi một legend là "Thông tin hợp đồng", còn thiếu 1 legend là "Thông tin yêu cầu bồi thường", xem lai prototype customer => YeuCauBoiThuong.html.
- [ ] Lúc tạo xong Compensation thì phải hiện thông báo "Yêu cầu bồi thường của bạn đã được gửi đi, vui lòng chờ giải quyết từ nhân viên công ty"
- [ ] Trang detail bị thiếu tiêu đề lớn ở trên "Yêu cầu bồi thươngf BTXXXX", xem lại prototype.
- [ ] "Có 1 Vụ Bồi Thường" => "Có 1 vụ bồi thường", "Yêu Cầu Bồi Thường" => "Yêu cầu bồi thường"
- [ ] Trang hiện danh sách, cột Ngày bồi thường: nếu chưa giải quyết thì hiện label: "Đang giải quyết", mã hợp đồng thì gắn link vào giống như prototype lúc trước đã làm. Có thể bỏ cột "Tên khách hàng" đi vì đây là trang customer. (Cột này còn đang hiện nhầm sang "Tên người lái xe", nhưng dù sao cũng bỏ đi rồi)
<img width="798" alt="screenshot 2015-07-04 21 17 51" src="https://cloud.githubusercontent.com/assets/4214509/8508220/2ebd076c-2292-11e5-915e-c38ceb385746.png">
- [ ] Nút Yêu cầu bồi thường cho hở cái bảng ra 1 xíu, hiện tại nó đang dính liền, nhìn xấu.
<img width="406" alt="screenshot 2015-07-04 21 19 58" src="https://cloud.githubusercontent.com/assets/4214509/8508227/817df04c-2292-11e5-91cd-03f68b313a5f.png">

**Comment by trungdq88** [comment]
Em không thế test thêm được bug nào nữa. Khá nhiều lỗi, anh fix rồi assign lại, em sẽ confirm và close.
Cố gắng review thật kỹ giúp em, đừng để bị reopen nhiều lần.

Phần code chỗ này vì anh @hydrangea8604  làm trước nên đã code cái DTO, giao diện jsp, kèm theo hàng loạt các hàm validate server và validate client rồi, phần của anh có thể nói là đỡ mất công hơn rất nhiều, anh nên tận dụng khoảng thời gian dư ra đó thật tốt.

**Comment by phucnguyen60749** [comment]
@trungdq88 review lại dùm nhé

**Comment by trungdq88** [comment]
"Yêu cầu bồi thường của bạn đã được gửi đi, vui lòng chờ giải quyết từ nhân viên công ty" - câu này chỉ hiện sau khi tạo compensation thôi, anh lại làm nó lúc nào cũng hiển thị ở trang detail thì đâu có đúng.

**Comment by phucnguyen60749** [comment]
@trungdq88  ac a có close đâu sao e bảo a close!

**Comment by trungdq88** [comment]
à ý em là re-assign lại để review.

**Comment by phucnguyen60749** [comment]
@trungdq88  thì a re-assign lại cho e là đúng mà! a chỉ fix cái checkbox đầu tien thoi nha!

**Comment by trungdq88** [comment]
Ah trời ơi, sao chưa làm xong mà assign cho em chi. Em cũng còn task của em nữa, anh làm hết một lượt rồi assign luôn chứ ai rảnh đâu mà review từng cái :disappointed:

**Comment by phucnguyen60749** [comment]
eo ơi e hok thấy a tick hết mất cái của e review rồi a moi assign lai mà! a chỉ fix cái checkbox đầu tien thoi nha confirm cái

**Comment by trungdq88** [comment]
À rồi, em hiểu rồi. Sorry anh.
Ok anh chỉ cần fix cái này thôi:

> "Yêu cầu bồi thường của bạn đã được gửi đi, vui lòng chờ giải quyết từ nhân viên công ty" - câu này chỉ hiện sau khi tạo compensation thôi, anh lại làm nó lúc nào cũng hiển thị ở trang detail thì đâu có đúng.

**Comment by phucnguyen60749** [comment]
@trungdq88  em xem lai cái nua nha!

**Comment by trungdq88** [comment]
<img width="931" alt="screenshot 2015-07-06 02 58 10" src="https://cloud.githubusercontent.com/assets/4214509/8513194/e97a7578-238a-11e5-8300-c74a37dd80fc.png">

**Comment by phucnguyen60749** [comment]
chà chổ náy! đang bị bí tại ko thể dùng session

**Comment by trungdq88** [comment]
Bí tại sao không hỏi mà im lặng re-assign lại cho em vậy? Anh có chạy thử trước chưa? Lỗi hiển nhiên như vậy không thể nào không thấy được!

**Comment by phucnguyen60749** [comment]
ok cái này ẩu! sr nhé! nhưng mà sao làm cái này vay!

**Comment by trungdq88** [comment]
Em sửa rồi, anh coi cách sử ở đây: https://github.com/trungdq88/insurance-card/commit/ee341c1536b0af741cb364cfe9192c00242fce95

Close issue.
