### ISSUE TITLE
<Customer> List/View/Add punishment

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#240]

**Comment by phucnguyen60749** [comment]
@hydrangea8604  review dùm nha! lúc tạo thêm 1 punishment thì nó sẽ reload lại trang contract-detail và bên tab của punishment cái record mới tạo sẽ lên đầu! paging chưa search đc

**Comment by hydrangea8604** [comment]
Nút thêm vi phạm sai chính tả.
Ngày gởi thông tin chứ không phải ngày vi phạm, có cho người ta nhập ngày vi phạm đâu.
Nút thêm vi phạm, thêm yêu cầu bồi thường, xác nhận là tạo mới, Phải là btn-success chứ sao lại là btn-primary.
Title chỉ có 250 ký tự, để cái textarea như vậy là quá lớn.
Để text center vào nội dung vi phạm làm gì, nó là chữ mà.
Vẫn Tiếp Tục Kiểu Viết Như Thế Này Ở Label.
@trungdq88 có nói là bây giờ chưa cần implement search và pagination. Nếu thích thì làm pagination là đủ. Thông tin này cũng ít, không (chưa) cần implement search cũng được.
dto.setCreateDate(DateUtils.currentDateWithoutTime()); Code này không được để ở Controller.
Nếu nó là ngày hiện tại thì set trong hàm getCreatedDate ở DTO. Mà bên này khác bên tạo hợp đồng, bên kia không quản lý thời gian để dễ làm việc, nhưng cái này không xử lý gì với nó. Nên để cả thời gian vào cho dữ liệu nó đúng đắn về mặt ngữ nghĩa.

**Comment by phucnguyen60749** [comment]
@hydrangea8604  review lại dùm nha! 
cái Title  để free text có confirm vs Trung
cái ngày gởi là lấy ngày mặc định hiện tại nên tui măc định lun

**Comment by hydrangea8604** [comment]
Trong modal, cả Nội dung vi phạm và Đính kèm đều là bắt buộc nên thêm dấu * như vầy:
![image](https://cloud.githubusercontent.com/assets/12366868/8512043/174cf62a-235d-11e5-825d-03b3a7bf72f2.png)
![image](https://cloud.githubusercontent.com/assets/12366868/8512068/dda7318c-235d-11e5-8799-14920f45737b.png)
Không cần đánh số thứ tự đâu, hiển thị punishmentId là được rồi. Mấy cái table khác như accident, compensation thấy header màu xanh nhạt, cho cái này giống thế luôn đi cho đồng bộ.
Cái chữ Ngày gởi thông báo quá dài thì sửa thành Ngày gởi đi, cho nó không thành 2 dòng

**Comment by phucnguyen60749** [comment]
@hydrangea8604  review lại dùm nha! :)

**Comment by hydrangea8604** [comment]
Ok, đã review
