### ISSUE TITLE
<Customer> List/View/Add accident

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#241]

**Comment by phucnguyen60749** [comment]
@hydrangea8604  kha oi review giúp! copy giong ben staff

**Comment by hydrangea8604** [comment]
Mà bên customer phần này không copy bên staff được đâu. Bởi "Ngày gởi thông báo" bên customer là mặc định ngày hiện tại, còn Staff được phép chỉnh sửa.
Cái giao diện thì làm giống customer - punishment, còn phần core có thể lấy hàm và DTO của Staff.
https://docs.jboss.org/hibernate/validator/4.0.1/reference/en/html_single/#table-builtin-constraints
@NotEmpty: Check if the string is not null nor empty.
Check empty là check null rồi, không cần check cả 2 cái đâu.

**Comment by phucnguyen60749** [comment]
@hydrangea8604 cái giao diện chỉ cần bỏ ngày đi thôi dc rồi đúng hok

**Comment by hydrangea8604** [comment]
=.=! Uhm

**Comment by phucnguyen60749** [comment]
@hydrangea8604  tui cho nó hide đi nhé! tại vì nều set mặc định ko dc set ở controller mà set ở Dto thì lại ko dc vì staff có thể thay đổi! ok

**Comment by phucnguyen60749** [comment]
@hydrangea8604  review lại dùm nha
