### ISSUE TITLE
<Customer> View payment history

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#242]

**Comment by phucnguyen60749** [comment]
@hydrangea8604  review dùm nhé! :)

**Comment by hydrangea8604** [comment]
Hình như cái issue này là implement trang: http://localhost:8080/customer/payment chứ nhỉ?
![image](https://cloud.githubusercontent.com/assets/12366868/8509516/bdb7560e-22d1-11e5-86fc-39502b263270.png)
Tên cột thì có thể để class text-center nhưng nội dung trong tag td thì không nên khi dữ liệu nhiều, đặc biệt là PayPal Id dài làm giao diện trông xấu đi.
Nếu có thể thì nên bỏ bớt một vài cột rồi dùng AJAX để hiển thị chi tiết giao dịch trong một modal. Có thể để click vào mã giao dịch hoặc thêm nút "Chi tiết" để gọi modal.
![image](https://cloud.githubusercontent.com/assets/12366868/8509521/18403ec4-22d2-11e5-80c2-73f0bf13f6d2.png)
![image](https://cloud.githubusercontent.com/assets/12366868/8509525/268216ec-22d2-11e5-8352-f562dc9497f2.png)
![image](https://cloud.githubusercontent.com/assets/12366868/8509537/5a115c66-22d2-11e5-97b9-a3fc4b734424.png)

**Comment by trungdq88** [comment]
Anh Phúc kiểm tra lại nhé, issue này là implement cho **http://localhost:8080/customer/payment** chứ không phải thêm tab mới trong trang contract.

**Comment by phucnguyen60749** [comment]
@hydrangea8604  review lại dùm nhe! 
 tui chỉ mới show ra cái list thôi! còn modal tui sẽ bổ sung sau nha!

**Comment by hydrangea8604** [comment]
:white_check_mark: Ok, đã hiển thị lên. Để làm tiếp detail rồi close, khỏi tạo issue mới chi cho mất công

**Comment by trungdq88** [comment]
@phucnguyen60749 anh đừng để chữ "fix" ở đầu commit message, vì khi github nó gặp chuỗi "fix #ABC" thì nó tự close. Rất phiền.

**Comment by phucnguyen60749** [comment]
@trungdq88  ok cái đó a ko bít

**Comment by phucnguyen60749** [comment]
@hydrangea8604  review dum nhe

**Comment by trungdq88** [comment]
- [ ] Ở trang danh sách bỏ cột "Người nhận" đi, vì trường hợp nếu thanh toán = PayPal thì ko có người nhận, nó sẽ bị trống.
- [ ] Ở popup chi tiết, nếu là thanh toán trực tiếp thì ẩn field "Mã PayPal" đi.
- [ ] Ở popup chi tiết, một vài field bị lệch, sửa lại cho ngay hàng thẳng lối.
<img width="611" alt="screenshot 2015-07-06 03 32 37" src="https://cloud.githubusercontent.com/assets/4214509/8513314/cc2d8c80-238f-11e5-907b-9d8f0f2ac0cc.png">

**Comment by phucnguyen60749** [comment]
@trungdq88  check lại dùm a nhé!

**Comment by trungdq88** [comment]
Done. :heavy_check_mark:
