### ISSUE TITLE
<Admin> manage staff

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#243]

**Comment by minhtridn2001** [comment]
- [ ] Admin home page : list all staff
- [ ] View staff detail page
- [ ] Create staff page
- [ ] Delete staff
... update later

**Comment by minhtridn2001** [comment]
@trungdq88  Em review giúp anh nhé. Cái chỗ password. Vì Admin cấp nên a quyết định show luôn :D Nếu cần sửa thì a sửa lại

**Comment by trungdq88** [comment]
- [ ] Địa chỉ trang admin nên là `/admin` (hiện tại là `/admin/home`).
- [ ] Mã nhân viên thì nên để nó tự sinh, dùng hàm `StaffDao.getIncrementId` ấy.
- [ ] Đưa field email lên đầu tiên, bỏ field Tên đăng nhập đi (tên đăng nhập = mã nv = tự sinh)
- [ ] Sau khi tạo xong thì hiện trang detail của nhân viên đó, highlight cái mã NV lên.

Lúc trước mình để mã NV tuỳ ý, nhưng em nghĩ giờ để là tự sinh thì tốt hơn.

**Comment by trungdq88** [comment]
Híc cái này review rồi 1 ngày trước rồi mà quên assign cho anh hả ta :disappointed: 
Anh @minhtridn2001 kiểm tra nha.

**Comment by minhtridn2001** [comment]
OK cám ơn em

**Comment by minhtridn2001** [comment]
Anh sửa theo review rồi em xem qua nhé @trungdq88

**Comment by trungdq88** [comment]
:+1: Đã review
