### ISSUE TITLE
<Checker App> Add punishment information

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#244]

**Comment by trungdq88** [comment]
Đã implement.

**Comment by trungdq88** [comment]
Đây là link tải app mobile mới: https://www.facebook.com/groups/insurancecard/880665665302375/
Anh Phúc review chức năng thêm Vi phạm nhé.

**Comment by phucnguyen60749** [comment]
@trungdq88 chụp ảnh ko lưu ảnh nên không thêm vi phạm được!

**Comment by trungdq88** [comment]
À quên nói, cái chức năng upload trên web mình chưa hỗ trợ nên em chỉ gửi 1 string lên thay cho cái ảnh thôi. Anh chụp hình và điền vi phạm vào app là có thể gửi được.

**Comment by phucnguyen60749** [comment]
Ý a là trong cái app chụp xong không lưu hình lại được!

**Comment by trungdq88** [comment]
Ok vậy để sáng mai em coi trên máy của anh thử.
Trên máy ảo chạy được bình thường.

**Comment by phucnguyen60749** [comment]
ok! vậy a close cái náy!

**Comment by trungdq88** [comment]
Chưa confirm được trên máy thật mà sao close.
Mai em kiếm máy thật chạy thử.

**Comment by trungdq88** [comment]
@phucnguyen60749 Em đã thử trên máy thật, chạy bình thường.
Anh kiểm tra lại lần nữa nhé:
- Nhập mã thẻ hợp lệ, nhấn Kiểm tra.
- Nhấn nút dấu cộng, thêm vi phạm.
- Nhập mô tả
- Click phần dưới để chụp hình camera.
- Gửi vi phạm.

Hình ảnh:
![abvksavmr7ncdkz6a_iuyx6utg516wgbww4nfn5i5hw](https://cloud.githubusercontent.com/assets/4214509/8518891/892ff53a-23f8-11e5-99f4-8c1be63b80ca.png)

![wcocjfbmcngj9xnfcmhkkvydtff2i6nstrwcb9na04s](https://cloud.githubusercontent.com/assets/4214509/8518905/954b7bd2-23f8-11e5-9b15-22504ab75abe.png)


<img width="937" alt="screenshot 2015-07-06 16 02 19" src="https://cloud.githubusercontent.com/assets/4214509/8518887/832cd3a6-23f8-11e5-8d0a-e556d86a4b68.png">


Trên máy của anh làm được đến bước nào? Có lỗi gì không? Chụp hình lại cho em nha.

**Comment by phucnguyen60749** [comment]
@trungdq88  a down cái bản mới nhất của e về điện thoại! a chụp hình và ảnh cũng không lưu lại để gởi thông tin vi phạm được! ????

**Comment by trungdq88** [comment]
Có báo lỗi gì không? Làm được đến bước nào? Chụp hình lại cho em được không?

**Comment by phucnguyen60749** [comment]
![image201507060001](https://cloud.githubusercontent.com/assets/12363394/8523525/1950084a-2420-11e5-95df-76ead0dcf9d6.jpg)

**Comment by phucnguyen60749** [comment]
làm được tới bước đó! nhưng mà chụp hình thì nó không lưu lại!

**Comment by trungdq88** [comment]
Ok vậy để mai sau khi gặp thầy em debug trên máy của anh thử.
Em close issue này. Tạo bug #267.
