### ISSUE TITLE
<Customer> Create new contract

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#245]

**Comment by minhtridn2001** [comment]
@trungdq88 Review giúp anh nha

**Comment by trungdq88** [comment]
- [ ] Trang review anh nên hiện thông báo: "Vui lòng kiểm tra lại các thông tin hợp đồng, nhấn nút Xác nhận để hoàn tất tạo hợp đồng".
- [ ] Lỗi concurrency: sau khi tạo hợp đồng, ở bước thanh toán dừng lại rồi bật tab mới, vào trang customer để thanh toán thông qua nút hoàn tất thanh toán của hợp đồng Pending => khi làm vậy thì cả 2 bên đều thanh toán được => tạo 2 record payment. Thỉnh thoảng có 1 bên lại báo thanh toán thành công nhưng status và expiredDate không có dấu hiệu thay đổi... Nói chung rất bất ổn (có thể là do xung độ về các biến payment trong session). Đề xuất chỗ này: sau khi taọ hợp đồng xong thì anh cho redirect sang trang contract detail luôn, lúc này trang detail sẽ hiện thông báo yêu cầu người dùng hoàn tất thanh toán cho hợp đồng Pending (đã implement trước đó), người dùng có thể thanh toán thông qua đó luôn cho tiện.

Anh pull code về trước khi fix, em có sửa 1 chỗ nhỏ trong customer/contract-detail.jsp.

**Comment by minhtridn2001** [comment]
Thanks em

**Comment by minhtridn2001** [comment]
@trungdq88  Hic cuối cùng cũng tìm ra lỗi. Là do lúc em sửa check concurrency lại của anh bị sai sót chỗ này:
```
Timestamp startModifyTime =(Timestamp) session.getAttribute("CHECKOUT:START_MODIFY_TIME");
            session.removeAttribute("CHECKOUT:START_MODIFY_TIME");
            String contractCode = (String) session.getAttribute("CONTRACT_CODE");
            concurrencyDto.setStartModifyTime(startModifyTime);
            concurrencyDto.setContractLastModified(contractBusiness.getContract(contractCode).getLastModified());
            // Gọi hàm validate ở đây
            List errors = r.ead.validate(concurrencyDto);
            // Nếu có lỗi khi validate
            if (errors.size() > 0) {
                // Gửi lỗi về trang JSP
                r.equest.setAttribute("error", errors.get(0));
                return new JspPage("public/error.jsp"); // chỗ này phải return trang error.jsp thì mới ko thanh toán nữa
            }
```

code hiện tại sau khi em sửa thì trả về trang return.jsp => tiếp tục thực hiện thanh toán.
```
// Check concurrency
            String returnUrl = "public/return.jsp";
            ....
            List errors = r.ead.validate(concurrencyDto);
            if (errors.size() > 0) {

                StringBuilder message = new StringBuilder();
                for (Object error : errors) {
                    message.append((String) error).append("<br/>");
                }

                r.equest.setAttribute("message", message);
                return new JspPage(returnUrl);  // tiếp tục thực hiện thanh toán ở đây
            }
```

**Comment by trungdq88** [comment]
Chỗ đó em muốn nó trả về trang return.jsp để hiện thông tin PayPal Transaction ID với cả số tiền thanh toán, nhưng message là nội dung thông báo lỗi. Không phải trang `return.jsp` là trang kết thúc quá trình thanh toán sao? Anh ghi "tiếp tục thực hiện thanh toán" là sao nhỉ?

**Comment by minhtridn2001** [comment]
Ah anh mới ghi vào comment chỗ đó cho em biết. Nếu có lỗi thì sẽ không thực hiện giao dịch. Nên sẽ ko có PayPal TransID

**Comment by trungdq88** [comment]
Ủa lỗi này là lỗi concurrency của hệ thống mình thôi chứ quá trình payment bên PayPal vẫn hàon thành mà đúng ko? Người dùng đã mất tiền rồi?

**Comment by minhtridn2001** [comment]
Ko em. Chưa chạy đến trang return.jsp là chưa thực hiện thanh toán!

**Comment by minhtridn2001** [comment]
Check concurrency chạy ok. Chỉ sai chỗ gửi trả về trang return.jsp thay vì error thôi em.

**Comment by minhtridn2001** [comment]
Đầu óc anh lú lẫn quá. Đi ngủ nghĩ lại mới thấy đúng như em nói rồi.
Cái trang thực hiện payment là lightboxreturn chứ ko phải trang return.jsp. Trang return.jsp chỉ để thông báo thôi.
Sáng a sửa lại nhé.

**Comment by minhtridn2001** [comment]
@trungdq88 Lỗi thanh toán 2 bên thành công là do hàm paymentContract()  bị sai, chưa update startDate và ExpiredDate đó em

**Comment by minhtridn2001** [comment]
@trungdq88  A sửa lại check concurrency ngay trước khi payment rồi. (Thêm vào lightboxreturn controller)
Còn việc thanh toán cùng lúc nhiều contract bị lỗi là do sung đột biến session. Trong issue Improve paypal payment. #201  anh sửa lại nhé

**Comment by trungdq88** [comment]
Đã review ✅
