### ISSUE TITLE
<Admin> Tạo trang config business rules.

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#246]

**Comment by minhtridn2001** [comment]
- [ ] Create table mic_business_rules
- [ ] Tạo entity
- [ ] Tạo trang edit business config rules 
- [ ] Validate client and server side

**Comment by minhtridn2001** [comment]
@trungdq88  Em review giúp anh qua. 
-Anh còn sửa lại giao diện nữa nên em review anh cái core thôi.
-Anh tạo bảo mic_business_rules rồi. Vì nó yêu cầu PK nên anh tạo cột id và mặc định sử dụng trong app là lấy id=1 nhé.
- Anh chưa apply vào sử dụng thay thế Constants nha.

**Comment by trungdq88** [comment]
@minhtridn2001 Anh kiểm tra giúp em xem đã commit đủ chưa, hiện tại em chỉ thấy Database và Entity của business rule, trong package admin chỉ thấy ManageController. Có bị thiếu gì không anh?

**Comment by minhtridn2001** [comment]
Anh có commit file AdminBusiness nữa mà. Em vào trang /admin có mục thiết lập ak.

**Comment by minhtridn2001** [comment]
Ủa
Push chưa đc

**Comment by trungdq88** [comment]
- [ ] ManageController nên tách ra làm StaffController và BusinessController.
- [ ] Chưa validate server side
- [ ] Các validate message trong DTO anh chịu khó ghi rõ ra là field nào: "Xin điền đầy đủ giá trị ABC" hoặc đổi lại thành "ABC không được để trống" cho hay, đừng có để giống nhau nếu không lúc báo lỗi server validate sẽ hiện message nào cũng giống nhau.
- [ ] Lúc nhấn nút Cập nhật thì phải gửi POST request.

**Nghiêm trọng:**

- [ ] Nhấn nút lưu nhưng giá trị không thay đổi, database có đúng giá trị nhưng trên trang detail vẫn hiện giá trị cũ. Refresh lại thì lúc hiện đúng lúc hiện sai, rất lạ?! Anh debug lại chỗ này thử.

**Comment by trungdq88** [comment]
Thêm một số comment về giao diện:

- [ ] Tách ra làm từng group riêng, mỗi group có nhiều biến. Hiện tại mỗi biến config anh cho luôn thành 1 group không có đẹp. Mình có các group config sau: 

1. Giới hạn chỉnh sửa ngày cho nhân viên
2. Các giới hạn ngày theo chính sách của công ty
3. Các khoản phí

Tham khảo bảng bên dưới, em đã nhóm các biến lại:

Tên tiếng Việt của các biến (em gợi ý):

Config | Tên tiếng Việt | Đơn vị
---------|--------------------|-----------
--------- | **Các giới hạn ngày theo chính sách của công ty**
        PAYMENT_DUE_DATE | Thời hạn thanh toán hợp đồng mới | Ngày
        NEARLY_EXCEED_EXPIRED_1 | Thời gian thông báo hợp đồng sắp hết hạn: lần 1 | Trước X ngày
        NEARLY_EXCEED_EXPIRED_2 | Thời gian thông báo hợp đồng sắp hết hạn: lần 2 | Trước X ngày
        NEARLY_EXCEED_EXPIRED_3 | Thời gian thông báo hợp đồng sắp hết hạn: lần 3 | Trước X ngày
        CONTRACT_DEFAULT_TERM | Thời hạn mặc định của hợp đồng | Tháng
EXPIRED_DATE_AFTER | Thời hạn tối thiểu của hợp đồng | Tháng
--------- | **Giới hạn chỉnh sửa ngày cho nhân viên**
        START_DATE_BEFORE | Ngày bắt đầu hợp đồng | X ngày trước ngày hiện tại
        START_DATE_AFTER | Ngày bắt đầu hợp đồng | X ngày sau ngày hiện tại
        PAID_DATE_BEFORE | Ngày thanh toán hợp đồng | X ngày trước ngày hiện tại
        PAID_DATE_AFTER | Ngày thanh toán hợp đồng | X ngày sau ngày hiện tại
        CANCEL_DATE_BEFORE | Ngày huỷ hợp đồng | X ngày trước ngày hiện tại
        CANCEL_DATE_AFTER  | Ngày huỷ hợp đồng | X ngày sau ngày hiện tại
--------- | **Các loại chi phí**
        NEW_CARD_REQUEST_FEE | Phí làm thẻ mới | VNĐ
        DELIVERY_FEE | Phí vận chuyển thẻ | VNĐ

Anh @hydrangea8604 vào kiểm tra xem thiếu thừa sai sót hay chỉnh sửa tiếng Việt gì không nhé.

**Comment by hydrangea8604** [comment]
Ok, sửa EXPIRED_DATE_AFTER thành CONTRACT_MIN_TERM là được.
Đơn vị của NEARLY_EXCEED_EXPIRED nên ghi rõ "X ngày trước ngày hết hạn"

**Comment by trungdq88** [comment]
Đã sửa lại bảng :heavy_check_mark:

**Comment by minhtridn2001** [comment]
@trungdq88 Em xem lại nhé. A fix theo review với làm lại cái bảng như của em.

**Comment by trungdq88** [comment]
Híc, cái bảng chỉ là em làm để liệt kê ra cho dễ theo dõi thôi, chứ giao diện thì anh vẫn làm như cũ mới đẹp chứ...
Anh chia mỗi group thành một <legend>, rồi trong đó có nhiều field.

Với lại cái lỗi nghiêm trọng vẫn còn:
1. Vào trang config
2. Sửa field đầu tiên thành 1, nhấn Cập nhật: **Vẫn hiện Thời hạn thanh toán hợp đồng mới: 7 ngày**
3. Click vào link "Thiết lập", trang được refresh lại:  **Thời hạn thanh toán hợp đồng mới: 7 ngày**
4. Click vào link "Thiết lập" lần nữa, trang được refresh lại:  **Thời hạn thanh toán hợp đồng mới: 1 ngày**
5. Click vào link "Thiết lập" lần nữa, trang được refresh lại:  **Thời hạn thanh toán hợp đồng mới: 7 ngày**
6 ...

Nó cứ bị thay đổi sau mỗi lần refresh đó anh.

**Comment by minhtridn2001** [comment]
Anh up giao diện mới lên trc nha. Còn cái bug em nói a tìm ko ra :D

**Comment by hydrangea8604** [comment]
Thời hạn mặc định của hợp đồng: đơn vị (tháng)
Thêm br trước và sau nút cập nhật, giờ nó đang dính sát vào lề.
![image](https://cloud.githubusercontent.com/assets/12366868/8512668/e65f7c66-2377-11e5-932d-2c191d2c005a.png)
Cái phần này nhìn choáng quá, có thể làm cho nó rõ ràng hơn được không?
Lướt qua thì thấy vậy, chờ Trung review kỹ hơn.

**Comment by minhtridn2001** [comment]
Thanks Kha

**Comment by trungdq88** [comment]
Great. Đã hết lỗi. :+1:
