### ISSUE TITLE
<Customer> Đổi mật khẩu, chỉ hỏi lần đầu tiên, nếu hủy bỏ thì thôi.

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#247]

**Comment by trungdq88** [comment]
@phucnguyen60749 cái này anh fix thêm 1 bug nữa là đổi mật khẩu thì pass mới phải khác với pass cũ nha. Fix vào issue này luôn.

**Comment by phucnguyen60749** [comment]
@hydrangea8604  review dùm nhé! co fix lổi của trung lun

**Comment by hydrangea8604** [comment]
- [ ] Cái modal chiều ngang hơi rộng, khoảng trắng nhiều quá, nên thu gọn lại nhìn cho đẹp.
- [ ] 3 label nên thêm dấu *, bởi vì cả 3 đều là bắt buộc phải nhập.
- [ ] Bổ sung dòng thông báo nhắc nhở người dùng nên thay đổi mật khẩu (giống ý thầy Khánh nói hôm rồi)
Còn lại đã Ok

**Comment by trungdq88** [comment]
@phucnguyen60749 sao close vậy anh? Đã review lại chưa nhỉ?

**Comment by phucnguyen60749** [comment]
@trungdq88 cái này giao diện thôi mà! 
@hydrangea8604  vẫy kha review lại dùm nha

**Comment by hydrangea8604** [comment]
Commit chưa, chắc lại quên đánh số rồi, copy cái mã commit vào đây để dễ theo dõi

**Comment by hydrangea8604** [comment]
![image](https://cloud.githubusercontent.com/assets/12366868/8512023/d7048124-235b-11e5-88d2-72457f46a594.png)
- [ ] Sai lỗi chính tả câu thông báo
- [ ] Thêm dấu * là thêm như vầy nè
![image](https://cloud.githubusercontent.com/assets/12366868/8512026/0711c804-235c-11e5-9620-b3a32cf6e73e.png)
- [ ] Chiều ngang của cái modal vẫn chưa được thu ngắn lại

**Comment by phucnguyen60749** [comment]
@hydrangea8604  cái textbox tui để (col-sm-3) lun đó , review lại dùm nha

**Comment by hydrangea8604** [comment]
- [ ] Sai lỗi chính tả câu thông báo
- [ ] Chiều ngang của cái modal vẫn chưa được thu ngắn lại

**Comment by trungdq88** [comment]
@phucnguyen60749 chiều ngang của modal là đường màu đỏ. Em thấy anh cứ thu nhỏ cái textbox (đường màu xanh) không à. Anh thu nhỏ cái chiều ngang của **modal** đường em đánh dấu màu đỏ ấy nha.
<img width="981" alt="screenshot 2015-07-05 22 51 47" src="https://cloud.githubusercontent.com/assets/4214509/8512354/bc5630fe-2368-11e5-95fb-708b0b49db13.png">

**Comment by phucnguyen60749** [comment]
@hydrangea8604  Chiều ngang của cái modal vẫn chưa được thu ngắn lại tui không bít cách fix

**Comment by trungdq88** [comment]
Anh @hydrangea8604 review giúp 1 lần nữa nhé.

**Comment by hydrangea8604** [comment]
:heavy_check_mark: Đã review
