### ISSUE TITLE
<Staff> Implement staff view, edit profile & change password

### ISSUE THREAD

**Issue by hydrangea8604** [trungdq88/insurance-card#248]
- [x] View profile
- [x] Edit profile
- [x] Change password

**Comment by minhtridn2001** [comment]
Review plz! :love_letter:

**Comment by trungdq88** [comment]
Review ok. Có vấn đề nhỏ: đổi lại thứ tự các field cho giống nhau ở trang hiển thị và trang edit.
![screenshot 2015-07-16 15 26 44](https://cloud.githubusercontent.com/assets/4214509/8718586/a7f6799c-2bcf-11e5-80bb-03107c3fbc74.jpg)

Sửa xong có thể tự close.
