### ISSUE TITLE
Bug: validate biển số xe bị trùng đối với hợp đồng Pending.

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#252]
Hợp đồng Pending bây giờ có 2 trường hợp là Pending đã thanh toán và Pending chưa thanh toán. Khi validate biển số xe thì chỉ báo lỗi với trường hợp Pending đã thanh toán, còn nếu pending chưa thanh toán thì vẫn cho đăng ký.

Lỗi hiện tại: hợp đồng pending đã thanh toán nhưng vẫn đăng ký hợp đồng mới với biển số trùng được.
Các chỗ cần sửa:
- [x] Public/Register
- [x] Customer/Create contract
- [x] Staff/Create contract

P/S: chỉ cần sửa lại hàm `contractDao.isExistByPlate(plate);` là được.

**Comment by minhtridn2001** [comment]
Ah anh đúng rồi. Thanks em

**Comment by minhtridn2001** [comment]
Fixed!
