### ISSUE TITLE
<Staff> Kiểm tra lại hiển thị của các nút Gia Hạn và Huỷ hợp đồng trong trường hợp Pending

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#254]
<img width="920" alt="screenshot 2015-07-03 10 03 39" src="https://cloud.githubusercontent.com/assets/4214509/8491874/cf379d34-216a-11e5-9631-fbac4744bd52.png">

<img width="925" alt="screenshot 2015-07-03 10 04 06" src="https://cloud.githubusercontent.com/assets/4214509/8491879/db1d7bfa-216a-11e5-873a-005dc83fc536.png">

**Comment by hydrangea8604** [comment]
@trungdq88 Gỡ ra để test mà quên gắn vào lại :sheep: 
@minhtridn2001 Review lại dùm nha.

**Comment by trungdq88** [comment]
Làm cẩn thận nha anh, càng về sau càng nhiều module. Làm cái mới mà lỗi cái cũ là fix hoài không xong luôn đó.

**Comment by minhtridn2001** [comment]
Review OK. Nhưng còn điểm này. Hợp đồng Pending đã thanh toán + sắp hết hạn có cho gia hạn ko ?
![image](https://cloud.githubusercontent.com/assets/12363317/8492892/d7145202-217b-11e5-82e7-d2fb8e0b9528.png)

**Comment by hydrangea8604** [comment]
Trong document ghi chỉ có 3 trạng thái ‘No card’, ‘Ready’ và ‘Expired’ là được phép gia hạn. Trường hợp pending, đã thanh toán mà sắp hết hạn thì chỉ có vụ hợp đồng của khách hàng có thời hạn vô cùng ngắn, chưa tới ngày có hiệu lực mà đã dưới 2 tháng. Họ có thể chờ tới lúc hợp đồng có hiệu lực là có thể gia hạn.
