### ISSUE TITLE
<Customer> View new card request

### ISSUE THREAD

**Issue by minhtridn2001** [trungdq88/insurance-card#256]

**Comment by trungdq88** [comment]
- [ ] Format ngày tháng 2 cột Thời gian và Ngày cấp mới thành dd/MM/yyyy
- [ ] Thêm cột "Hợp đồng" và hiện mã hợp đồng (kèm link) vào đó. (bên staff thì hiện chủ thẻ, bên customer này thì nên hiện Hợp đồng vì trang này liệt kê tất cả request từ tất cả hợp đồng).

**Comment by minhtridn2001** [comment]
Đã fixed theo review của em.

**Comment by trungdq88** [comment]
Đã review :white_check_mark:
