### ISSUE TITLE
New Card Request bỏ quan hệ với customer (and/or contract)

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#262]
Hiện tại: gắn với Customer.
Cần sửa lại: bỏ quan hệ đi.

Các chỗ cần sửa:
- Database
- Hibernate entity
- Code ở các chỗ request new card.

**Comment by trungdq88** [comment]
Mới cập nhật lại description. Bỏ quan hệ.

**Comment by minhtridn2001** [comment]
Done! Em review giúp anh nhé.

**Comment by trungdq88** [comment]
:+1: Đã review.
