### ISSUE TITLE
Checker app: add punishment: hình chụp không lưu lại được.

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#267]

**Comment by trungdq88** [comment]
Vẫn chưa có cơ hội debug thử trên máy của anh, nhưng anh thử chạy app mới này xem có hết lỗi chưa nhé.

App mới: https://www.facebook.com/groups/insurancecard/882706731764935/

**Comment by phucnguyen60749** [comment]
ok đã review
