### ISSUE TITLE
Customer request new card: Phí vận chuyển cho phép người dùng chọn checkbox

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#272]
Thanh toán bằng Paypal vẫn có thể tới cty nhận thẻ.

Nếu chọn thanh toán trực tiếp thì:
- New card request sẽ được tạo.
- Ở trang staff phải có chỗ nhập thanh toán. #273

**Comment by minhtridn2001** [comment]
@trungdq88 Theo anh như vậy mình cần phải thêm vào 2 column:
- Yêu cầu thẻ mới có yêu cầu vận chuyển ko: thêm column is_delivery_requested (something like this) vào bảng mic_new_card_request.
- New card request đã được thanh toán hay chưa: thêm column is_paid vào bảng mic_new_card_request.
Vì đây liên quan đến thay đổi database nên em confirm lại cho anh nha.

**Comment by trungdq88** [comment]
Ok, hợp lý. Vậy anh làm như vậy nha.

**Comment by minhtridn2001** [comment]
OK em

**Comment by trungdq88** [comment]
Review chung với #274. Close.
