### ISSUE TITLE
<Staff> Thêm thanh toán mới.

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#273]
Thêm thanh toán bằng tay trong các trường hợp customer đến thanh toán trực tiếp.

**Comment by hydrangea8604** [comment]
@minhtridn2001 Khỏe thì review dùm t, ko thì assign cho Trung hoặc Phúc nha, đừng cố.

**Comment by minhtridn2001** [comment]
@hydrangea8604 T review thấy cái core thì OK rồi. Nhưng Kha xem cái thời gian thanh toán có cần chính xác thời gian giờ phút ko. Vì nếu ko cần thì bỏ đi 00:00:00 luôn.
- Validate client side: không cho viết hoa đầu câu:
![image](https://cloud.githubusercontent.com/assets/12363317/8544319/90804ff2-24ce-11e5-90fb-758a6d29c358.png)
- Validate server side: lỗi như trong hình:
![image](https://cloud.githubusercontent.com/assets/12363317/8544384/055e6976-24cf-11e5-8193-2c5100e93bea.png)

**Comment by hydrangea8604** [comment]
Nhập số tiền bao nhiêu để ra cái exception thế Trí?

**Comment by minhtridn2001** [comment]
Ủa Kha ko bị hả. T nhập kiểu gì cũng bị luôn. Bỏ validate đi thì chạy bình thường

**Comment by hydrangea8604** [comment]
@minhtridn2001 Thời gian thanh toán có 00:00:00 là ở trong modal khi bấm vào nút Chi tiết đúng không? Nhớ là checkout bằng PayPal nó có giờ phút giây. Trí confirm lại dùm, nếu bên đó cũng không có thì t bỏ.
Ngày nộp chắc là có giới hạn, không được sau ngày hiện tại, trước ngày hiện tại 7 ngày? @trungdq88 được không Trung?

**Comment by minhtridn2001** [comment]
Ý t là lúc Staff thanh toán thì cũng nên lưu giờ phút chính xác luôn. Thay vì lúc xem lại thì thấy 00:00:00. Trừ mấy ngày startDate- expiredDate của hợp đồng thì những ngày khác t đang để giờ phút hết.

**Comment by minhtridn2001** [comment]
Còn giới hạn ngày nộp thì theo bảng business_rules ấy Kha. Mà chưa biết nên load trực tiếp từ database hay là mỗi ngày sẽ cập nhật 1 lần vào app nữa. Hỏi lại Trung :D

**Comment by hydrangea8604** [comment]
Nếu staff chọn ngày khác thì giờ phút giây nó cũng là 00:00:00. Nếu muốn lấy giờ chính xác thì chỉ lấy giờ hiện tại thôi. Ok?

**Comment by minhtridn2001** [comment]
Ờ nhỉ. Cái vụ chọn ngày này phiền quá

**Comment by trungdq88** [comment]
> Còn giới hạn ngày nộp thì theo bảng business_rules ấy Kha

:+1: , hiện tại chưa kết hợp các biến trong bảng business_rule mà vẫn dùng file Constants, do đó anh Kha dùng tạm biết trong Constants cũng được.

> Nếu staff chọn ngày khác thì giờ phút giây nó cũng là 00:00:00. Nếu muốn lấy giờ chính xác thì chỉ lấy giờ hiện tại thôi. Ok?

:+1: Hợp lý.

**Comment by hydrangea8604** [comment]
@minhtridn2001 Ok, đã sửa lại. Có validate ngày cả server và client. Nếu là ngày hiện tại thì có giờ chính xác, còn ngày khác thì vẫn là 00:00:00
