### ISSUE TITLE
<Customer> Request New Card: thêm nút báo mất thẻ.

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#274]
Khi nhập thông tin yêu cầu thẻ mới có thêm 1 checkbox "Thẻ cũ đã bị mất", nếu người dùng check vào đây thì sẽ tự động deactive thẻ cũ khi gửi yêu cầu.

**Comment by trungdq88** [comment]
- [ ] Thêm <label> vào cho các radio button và checkbox để click vào chữ thì nó cũng check được
- [ ] Nếu nhận thẻ tại công ty thì phí vận chuyển = 0.
- [ ] Xác nhận mật khẩu và ghi chú là bắt buộc, thêm dấu * vào.
- [ ] Nếu thanh toán trực tiếp thì biến `is_paid` khi nào sẽ được đánh dấu thành 1?

**Comment by minhtridn2001** [comment]
@trungdq88 Xong rồi em ơi. Review thêm lần nữa nhé :)

**Comment by trungdq88** [comment]
:+1: Đã review.
