### ISSUE TITLE
<Customer> Contract detail: tính ngày còn lại bi sai.

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#278]
(trường hợp sai như trong lúc demo sáng July 07): Quá hạn 366 ngày.
Chỗ này đã bị report lỗi tới 2 - 3 lần, trước đây từng lỗi và fix nhưng giờ lại bị lỗi lại. Anh cần kiểm tra lại code cho thật cẩn thận, tốt nhất nên tính toán ngày tháng ở server side.

Anh có thể ghi cách tính toán của anh (kèm theo code) lên đây để em review. Đây là cách tốt nhất để sau này không còn bug chỗ này.

**Comment by phucnguyen60749** [comment]
@trungdq88  close cái này!
<Staff> Contract detail: tính ngày còn lại bi sai! #288
