### ISSUE TITLE
<Staff> Implement file upload

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#281]
Cách implement file upload:
https://github.com/trungdq88/insurance-card/wiki/T%C3%ADch-h%E1%BB%A3p-file-Upload

Các chỗ cần implement:
- [ ] Compensation
- [x] Accident
- [x] Punishment

**Comment by hydrangea8604** [comment]
@minhtridn2001 review dùm nha.

**Comment by minhtridn2001** [comment]
Lỗi đã nói qua fb
![image](https://cloud.githubusercontent.com/assets/12363317/8568471/03f8355c-2598-11e5-854c-c4cc97244a4e.png)

**Comment by hydrangea8604** [comment]
Đã fix

**Comment by minhtridn2001** [comment]
:+1:  Đã review
