### ISSUE TITLE
<Customer> Implement file upload

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#282]
Cách implement file upload:
https://github.com/trungdq88/insurance-card/wiki/T%C3%ADch-h%E1%BB%A3p-file-Upload

Các chỗ cần implement:
- [x] Compensation
- [x] Accident
- [x] Punishment

**Comment by phucnguyen60749** [comment]
@hydrangea8604 review dùm nha

**Comment by hydrangea8604** [comment]
Accident: Thêm vi phạm là modal, click vào Pick File nó hiện lên cái popup để upload file, lúc này modal biến mất. Upload xong phải nhấn lại nút thêm vi phạm để gởi.
Punishment: Ok
Compensation: Thiếu ngày xảy ra tai nạn (accidentDate). "Biên bản của cơ quan CA" là "Yêu cầu bồi thường", "Văn bản đính kèm" là "Biên bản của cơ quan CA" mới đúng.
Thêm br dưới button gởi yêu cầu bồi thường, nó đang bị dính vào lề

**Comment by phucnguyen60749** [comment]
@hydrangea8604  kha ơi cho hỏi cái! Accident bên staff đâu có modal đâu!

**Comment by hydrangea8604** [comment]
Ừ, accident bên staff không dùng modal nên không có vấn đề với cái File Picker. Sao?

**Comment by hydrangea8604** [comment]
À, hiểu rồi

**Comment by phucnguyen60749** [comment]
vậy vấn đề của punishment là gì!

**Comment by hydrangea8604** [comment]
Đọc lại comment ở trên.

**Comment by phucnguyen60749** [comment]
đọc rồi hình như ông đang mô tả lại ! tui chưa hiểu ý ông

**Comment by phucnguyen60749** [comment]
với lại cái ngày xảy ra tai nạn bên compensation là ngày mặc đinh customer không được phép sữa! vậy có nên hiện ra không?

**Comment by hydrangea8604** [comment]
Ai nói ngày xảy ra tai nạn bên compensation là ngày mặc định? Ngày tạo (createdDate) mới là ngày mặc định.

**Comment by hydrangea8604** [comment]
Còn punishment thì nó là mô tả mà. Có lúc bấm vào cái File Picker cái modal phía sau nó tự mất đi, phải click lại nút Thêm vi phạm nó mới hiện lên

**Comment by phucnguyen60749** [comment]
click vào thêm vi phạm --> chọn up file -> popup up file hiện ra --> modal biến mất --> sau khi up load xong thì modal sẽ hiện lại để nhấn nút gửi

**Comment by hydrangea8604** [comment]
Có chữ "Có lúc" kìa, có lúc cái modal nó sẽ hiện trở lại, có lúc nó không hiện. Lần đầu tiên vào sẽ bị, thử một trình duyệt khác xem.

**Comment by phucnguyen60749** [comment]
ok để tui thử tại tui chưa tái tạo dc lỗi đó

**Comment by phucnguyen60749** [comment]
@hydrangea8604  cái compensation tui đã fix!  còn cái punishment kia tui ko tái tạo dc lỗi! ông có thể control + F5

**Comment by hydrangea8604** [comment]
![image](https://cloud.githubusercontent.com/assets/12366868/8571767/cd78e006-25b2-11e5-88f4-685618e60d77.png)

Validate server lỗi thì nó hiện vầy.

**Comment by phucnguyen60749** [comment]
cái contract code đó mà mặc định lun mà! ông bỏ hết mấy cái ${contractCode} bên create-compensation.jsp thì nó báo vậy!

**Comment by phucnguyen60749** [comment]
à rồi!

**Comment by phucnguyen60749** [comment]
ok hết bug roi đó @hydrangea8604

**Comment by hydrangea8604** [comment]
Đã review

**Comment by trungdq88** [comment]
Ủa khoan, tại sao thêm vi phạm bên customer lại là modal vậy? Làm gì có chỗ nào modal đâu? anh @phucnguyen60749 ?

**Comment by phucnguyen60749** [comment]
milestone sau sẽ improve! close cái này

**Comment by trungdq88** [comment]
#289
