### ISSUE TITLE
Trang danh sách yêu cầu thẻ mới: hiện trạng thái thanh toán. Thêm nút thanh toán nếu chưa thanh toán.

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#283]
Trường hợp KH đến cty để thanh toán và nhận thẻ thì sẽ dùng nút thanh toán trên trang này để cập nhật thông tin thanh toán vào hợp đồng.

Nút thanh toán có thể dùng lại từ code của task #273

**Comment by minhtridn2001** [comment]
@trungdq88 Nút thanh toán nếu giống như task #273 thì nội dung và số tiền phải nhập bằng tay hả em.

**Comment by trungdq88** [comment]
Nội dung và số tiền ở trang này thì fix cứng chứ không nhập bằng tay anh. Chỉ sửa lại chỗ đó thôi.
À với lại trong cái modal có phần "Thông tin hợp đồng" hơi thừa, có thể bỏ đi.

**Comment by hydrangea8604** [comment]
Phần thông tin hợp đồng đó include vào bằng jsp:include, chỉ cần search rồi xóa dòng đó là được.

**Comment by trungdq88** [comment]
> Phần thông tin hợp đồng đó include vào bằng jsp:include, chỉ cần search rồi xóa dòng đó là được.
:+1: +1 for low coupling code.

**Comment by minhtridn2001** [comment]
@trungdq88 Nếu thêm cái button mở modal thanh toán vào mỗi row. Thì làm cách nào fix cứng nội dung + số tiền vào cái modal đó bây giờ em :-???

**Comment by hydrangea8604** [comment]
Thêm parameter vào link gắn với button mỗi row, vào modal check nếu parameter not empty thì disable input, gắn giá trị cứng để hiển thị cho người dùng biết và thêm input hidden để truyền về server.

**Comment by minhtridn2001** [comment]
Anh có đề xuất thế này: Mình cho hiện trạng thái thanh toán trên list thôi. Vào trang detail để hoàn tất thanh toán giống như bên hợp đồng vậy có được không?

**Comment by minhtridn2001** [comment]
```
<button id="btnPayment" type="button" class="btn btn-success hide"
                                                data-toggle="modal" data-target="#add-payment-modal">
                                            <i class="fa fa-plus"></i> Thêm thông tin thanh 
</button>
```
Mình thêm link vào ntn Kha

**Comment by trungdq88** [comment]
Giải quyết được chưa anh?

**Comment by minhtridn2001** [comment]
Được rồi em :D

**Comment by trungdq88** [comment]
Vậy xong chưa? Assign em review luôn.

**Comment by minhtridn2001** [comment]
Làm đc rồi nhưng sắp xong thôi :D

**Comment by trungdq88** [comment]
**Nghiêm trọng:**
- [ ] Nếu cấp thẻ trước, rồi thanh toán sau thì sẽ bị exception:
<img width="888" alt="screenshot 2015-07-09 00 04 12" src="https://cloud.githubusercontent.com/assets/4214509/8576719/15c7ac96-25ce-11e5-9904-ced74d97ab7e.png">
Vì anh dùng hàm `newCardRequestDao.getUnresolveRequestByContractCode(contractCode);` mà request đã in thẻ thì nó đã được resolve. Nên đổi lại thành get `UnpaidRequestByContractCode` (lấy request chưa được thanh toán).

- [ ] Cho nút thanh toán nhỏ lại, `class="btn btn-success btn-xs"`
- [ ] Trong modal, 2 field dịch vụ và số tiền thì không được phép sửa. (Vì có sửa cũng đâu có tác dụng?)

**Comment by minhtridn2001** [comment]
Done! Em review lại giúp anh lần nữa nhé

**Comment by trungdq88** [comment]
Đã review :white_check_mark:
