### ISSUE TITLE
<Customer> Implement trang thông tin thẻ

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#285]

**Comment by minhtridn2001** [comment]
Em review giúp anh trang này nha

**Comment by trungdq88** [comment]
:+1: Đã review. Có 2 lỗi nhỏ:

- [ ] Sửa tiêu đề của trang lại thành "Các thẻ đang sở hữu" (hiện tại là "Thẻ đã phát hành" - cái này bên staff, bên customer không phù hợp lắm)
- [ ] Trong trang detail của thẻ "Ngưng hoạt động" bỏ field thẻ mới đi.

Sửa xong có thể tự close.

P/S: nếu anh có thể comment vào các hàm để mô tả chức năng của hàm đó thì rất tốt.

**Comment by minhtridn2001** [comment]
OK a sẽ thêm vào comment
