### ISSUE TITLE
<Staff> Bugs ở các trang thẻ

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#286]
Một số lỗi bây giờ mới phát hiện ra.

- [x] Trang danh sách Yêu cầu thẻ mới: cột Mã thẻ cũ và Thẻ mới cấp chưa gắn link
- [x] Trang chi tiết thẻ: các thẻ đã bị deactive: field Mã thẻ mới được cấp lúc nào cũng hiện "Chưa có".

**Comment by hydrangea8604** [comment]
@minhtridn2001 Trang yêu cầu thẻ mới là Trí làm, giờ t gắn link vào luôn nha? Còn 2 cái hàm mapping chạy ok chưa? T lấy gắn vào trang detail

**Comment by minhtridn2001** [comment]
Ừa trang yêu cầu thẻ mới t chưa gắn link gắn Link. Bây giờ T gắn hay Kha gắn.
2 hàm mapping bên trang yêu cầu thẻ hả? Vẫn ok mà.

**Comment by hydrangea8604** [comment]
Hôm nọ kêu chỉnh sửa gì đó =.=! Ok, để t gắn cho, dù sao cũng đưa ông review

**Comment by minhtridn2001** [comment]
T ko nhớ :D ko sửa gì hết. Ah cái mapping lấy new card id hả

**Comment by hydrangea8604** [comment]
Uhm, chưa biết có lấy được không, tại thấy phải truyền vào new card request Id

**Comment by minhtridn2001** [comment]
Ừ cái map ấy key = new_card_request_id mà có oldCardId là thẻ deactive, value = id thẻ mới

**Comment by hydrangea8604** [comment]
Chuyển giao cho @minhtridn2001

**Comment by minhtridn2001** [comment]
Done!

**Comment by trungdq88** [comment]
Nó vẫn hiện là chưa có anh ơi.

<img width="845" alt="screenshot 2015-07-08 21 12 52" src="https://cloud.githubusercontent.com/assets/4214509/8572328/27463018-25b6-11e5-9afd-43318b170cae.png">

Nhưng mà field này trong prototype mình đâu có đâu, cũng không cần thiết lắm. Em nghĩ là nên bỏ luôn đi nha.

**Comment by hydrangea8604** [comment]
Ừ, bỏ cũng được, a thêm vào cho thông tin nó đầy đủ thôi, mà nếu khó lấy quá thì bỏ cũng không sao

**Comment by trungdq88** [comment]
Sorry review bị lỗi. Chỗ đó đã hiện thẻ mới. Nhưng mà nói chung không cần thiết và không liên quan lắm. Bỏ luôn nha.
