### ISSUE TITLE
<Staff> Compensation (create & edit) Reordering fields

### ISSUE THREAD

**Issue by hydrangea8604** [trungdq88/insurance-card#287]
Sắp xếp lại các field cho hợp lý và hạn chế khoảng trắng tối đa có thể. (Theo yêu cầu của thầy Khánh KT)

**Comment by hydrangea8604** [comment]
@minhtridn2001 Review dùm

**Comment by minhtridn2001** [comment]
T thấy OK. Gọn hơn cái cũ. Nhưng ko biết ý Thầy ntn :D
