### ISSUE TITLE
<Staff> Contract detail: tính ngày còn lại bi sai! 

### ISSUE THREAD

**Issue by phucnguyen60749** [trungdq88/insurance-card#288]
Trong trường hợp đổi ngày hệ thống logout --> login vào lại "Thời gian đến ngày hết hạn" không tính lại thời gian!

**Comment by hydrangea8604** [comment]
Khi đổi giờ Windows, Chrome nó cần thời gian để biết được hệ thống đã thay đổi giờ. Lúc đó cái hàm new Date() nó mới thay đổi theo. Lúc đó F5 lại là ngày sẽ tính lại. Thử đổi giờ hệ thống, chờ một chút login lại, hoặc login vào rồi một lát sau F5 sẽ tính lại ngày.

**Comment by trungdq88** [comment]
> Chrome nó cần thời gian để biết được hệ thống đã thay đổi giờ

Cái này có đúng không anh? Chắn chắn chứ?

**Comment by phucnguyen60749** [comment]
sao khi đổi giờ ngay tức khắc load lại mấy trang khác! github chẳng hạn! trình duyệt liền báo lỗi license ngay tức khắc

**Comment by hydrangea8604** [comment]
![image](https://cloud.githubusercontent.com/assets/12366868/8573761/89223c94-25bd-11e5-8eb0-ed39d2a78293.png)

Ngay sau khi vừa đổi giờ, new Date lại nó vẫn là ngày cũ.

Khoảng 30s sau new Date lại nó mới thành ngày đã đổi.

![image](https://cloud.githubusercontent.com/assets/12366868/8573776/9988533e-25bd-11e5-9752-39c18f526748.png)

**Comment by hydrangea8604** [comment]
GitHub dùng HTTPS, cái đó là cetificate chứ license gì.
http://superuser.com/questions/760208/getting-ssl-certificate-error-after-changing-computer-date
http://security.stackexchange.com/questions/24704/system-time-and-certificates

**Comment by phucnguyen60749** [comment]
cái này là lỗi license host mà
![untitled](https://cloud.githubusercontent.com/assets/12363394/8573923/483ff54e-25be-11e5-9848-f10cc787c929.png)

**Comment by trungdq88** [comment]
:+1: +1 cho phát hiện. Mình có thể sử dụng luận điểm này lúc bảo vệ. Suy ra bug #278 không cần sửa nữa.

**Comment by trungdq88** [comment]
Anh @phucnguyen60749 confirm lại xem có chính xác không nha, sau khi đổi ngày tháng khoảng 30s thì giá trị "Thời gian đến ngày hết hạn" sẽ chính xác.

**Comment by phucnguyen60749** [comment]
ok đã confirm sau 1 khoảng thời gian
