### ISSUE TITLE
Sửa document cho phần Recycle Card 

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#295]
- Conceptual diagram
- ERD
- Class diagram
- Physical Diagram, Data dictionary

**Comment by trungdq88** [comment]
- [x] 4. Conceptual Diagram: đổi hình conceptual diagram, thêm CardInstance trong data dictionary
- [ ] 4. Class Diagram: đổi hình
- [x] 4.2 Class explanation: Thay đổi 4.2.2. Card, thêm mục 4.2.3. CardInstance.
- [x] 4. Class Diagram: thêm CardInstance trong Class dictionary
- [x] 6.1. Entity Relationship Diagram: đổi hình ERD
- [x] 6.2. Entity Dictionary: thêm CardInstance.
- [x] 2. Database Relationship Diagram, 2.2. Data dictionary: thêm bảng mic_card_instance trong data table dictionnary và attribute dictionary.

Anh trí giúp em làm lại cái hình cho Class Diagram nhé, chú ý: có relationship giữa Payment và Staff (cái này mới thêm vào gần đây nhưng quên chưa cập nhật)
<img width="303" alt="screenshot 2015-07-10 14 59 41" src="https://cloud.githubusercontent.com/assets/4214509/8614492/53a68856-2714-11e5-9d86-9a83fda33f98.png">

**Comment by minhtridn2001** [comment]
@trungdq88  Anh commit class diagram mới rồi đó em. Mà ghi nhầm update database :D

**Comment by trungdq88** [comment]
:+1: Great, thanks.

**Comment by trungdq88** [comment]
TODO: Thêm startdate, expireddate vào entity payment:
- [ ] Entity
- [ ] Entity dictionary

**Comment by trungdq88** [comment]
Anh @phucnguyen60749 review lại các chỗ thay đổi xem có thiếu sót gì không nhé.

**Comment by phucnguyen60749** [comment]
review ok
