### ISSUE TITLE
Chỉnh document

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#296]
- [ ] Delete test white-box
- [ ] Storage: ghi trên dữ liệu có thật, tính toán các field trong record tốn bao nhiêu dung lượng, ước lượng hệ thống trong 1 năm sẽ sinh ra bao nhiêu record. Tính tổng lại để ghi vào Test Environment trên server. (Sửa ở minimum system requirement và ở Performance Measures)
- [ ] Test pages: viết lại bảng, ghi rõ cụ thể các trang trong Staff, Customer.
- [ ] Bổ sung cấu hình cơ bản và yêu cầu của Client khi check (Mobile)
- [ ] Component Interface API thiếu 1 hàm.
- [ ] Bổ sung exception (những try-catch có trong code). Thêm cột exception phía sau Output
- [ ] Json string List of contract: Ghi rõ các thuộc tính có trong entity của Contract (Thêm cột output format)
- [ ] Kiểm tra lại tất cả các mục trong non-functional requirement đã có chỗ mô tả test chưa? (Test các thứ đã ghi trong SRS) Ghi ra một bảng excel.

**Comment by hydrangea8604** [comment]
E.	System Implementation & Test
1.	Introduction
1.2.	Test Approach
•	Method: delete "white-box testing"
3.	Performance Measures
3.1.	Web application page load speed
3.1.2.	Test environment
-	Storage: edit 20 GB to 40 GB
3.1.3.	Test cases
Test pages: edit table
3.2.	Mobile application API load speed
3.2.2.	Test environment
Client: add minimum & recommend requirement
D.	Software Design Description
5.	Interface
5.1.	Component Interface
5.1.1.	Web Service Interface
Table 49 Web Services Interfaces
- Add function: getCheckConnection
- Add Output Format, Exception column.
Add Table 50 Entity description, Table 51 Exception description
