### ISSUE TITLE
Nhờ review ERD và database.

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#297]

**Comment by trungdq88** [comment]
Review của thầy tài:
- Trong bảng contract nên có thêm field để biết card_instance hiện tại (sẽ bị trùng lắp dữ liệu nhưng tăng nhanh performance)
- Xem lại quan hệ giữa new_card_request và card_instance:
    - Mỗi request chỉ được cấp mới 1 thẻ (card instance), tại sao ký hiệu trong db lại là 0..*.
    - Mỗi card instance chỉ được yêu cầu cấp 1 lần, tại sao ký hiệu trong db lại là 0..*.
- Notification có trong Use case thì phải có trong ERD, chỗ receiver của notification thì sẽ làm không nối với staff hay customer mà sẽ nối tới 1 abstract entity "User", staff và customer sẽ thừa kế lại User.

**Comment by trungdq88** [comment]
Kế hoạch chỉnh sửa:
- [ ] Thêm field trong bảng contract, nhưng không cần đổi code, chỉ thêm để bảo vệ trước hội đồng tốt hơn.
- [ ] Thêm entity User trong ERD, customer và staff thừa kế vào.
- [ ] Thêm các note vào physical database.
- [ ] (còn nữa, cập nhật sau)

**Comment by trungdq88** [comment]
Đã commit và chỉnh sửa lại document. Database mới file 20150716.sql

Anh @phucnguyen60749 review nhé :tada:

**Comment by phucnguyen60749** [comment]
ok thông rồi!
