### ISSUE TITLE
Chỉnh lại border, placeholder và input text color rõ hơn trên máy chiếu.

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#298]

**Comment by trungdq88** [comment]
Please review.
Nhớ F5 một vài lần để cập nhật lại cache cho các file CSS.

<img width="995" alt="screenshot 2015-07-10 14 09 36" src="https://cloud.githubusercontent.com/assets/4214509/8613816/52eae508-270d-11e5-8da4-7af8bff7c788.png">

**Comment by phucnguyen60749** [comment]
border, placeholder thì ok
- input text color đậm hơn placeholder

**Comment by trungdq88** [comment]
> input text color đậm hơn placeholder

Hiện tại đã là đang đậm hơn rồi, nhưng em vừa chỉnh cho nó thành màu đen pure luôn.
Anh review lại lần nữa nhé.

**Comment by phucnguyen60749** [comment]
ok đã review
