### ISSUE TITLE
Business rule: ghi lại lịch sử

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#299]
Business rules, thêm field start date, mỗi lần lưu lại một cấu hình thì thêm 1 record. Ngày bắt đầu của record này là ngày kết thúc của record trước. Để hệ thống có thể flexible, sau này có thể rollback trở lại một record nào đó trước đây.

**Comment by minhtridn2001** [comment]
Em xem như vậy đã được chưa?

**Comment by trungdq88** [comment]
- [ ] Bỏ cột mã cấu hình, chỉ cần cột STT và ngày bắt đầu, link thì gắn vào cột ngày bắt đầu.
- [ ] Format lại ngày tháng thành dd/MM/yyyy cho cột ngày bắt đầu.
- [ ] Lúc xem chi tiết cấu hình thì hiển thị ngày bắt đầu và kết thúc của cấu hình đó, thêm nút back.

**Comment by minhtridn2001** [comment]
Đã fix theo review @trungdq88

**Comment by trungdq88** [comment]
:+1: Done.
