### ISSUE TITLE
Customer new card request: improve lại flow PayPal payment

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#300]
Đến khi nào hoàn thành payment thì mới tạo request.

**Comment by minhtridn2001** [comment]
Lần trước a nhầm. Thanh toán xong mới tạo request a sửa hồi trước rồi. Bây giờ a đổi lại tạo payment record trước, new card request record sau.

**Comment by trungdq88** [comment]
Ủa tạo Payment record trước là sao nhỉ? Không phải lúc nào payment rồi mới tạo record sao??

**Comment by minhtridn2001** [comment]
@trungdq88 Ah hồi trước anh để tạo request bên trong lightboxreturn ( ngay trước bước thanh toán). Mà anh chuyển lại qua hàm getActiveCreateNewCardRequest(nếu thanh toán xong succeed) lúc nào rồi :D Hôm bữa em hỏi a ko nhớ

**Comment by trungdq88** [comment]
Ok. Em close issue này.
