### ISSUE TITLE
<Customer> Detail hợp đồng: thêm chỗ để hiện các thẻ đã gắn với hợp đồng đó.

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#301]

**Comment by phucnguyen60749** [comment]
@hydrangea8604  review dùm nhé! thêm card active cho contract đó!

**Comment by hydrangea8604** [comment]
Tiêu đề @trungdq88 ghi là "đã gắn với hợp đồng đó" thì tức là bao gồm cả thẻ đang active và cả những thẻ đã deactivate chứ nhỉ?

**Comment by phucnguyen60749** [comment]
à wen chưa nói với ông! có confirm vs trung! issue ghinhầm! chỉ hien card active thôi!

**Comment by hydrangea8604** [comment]
Done
