### ISSUE TITLE
<Staff> Detail hợp đồng: thêm chỗ để hiện các thẻ đã gắn với hợp đồng đó.

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#302]

**Comment by hydrangea8604** [comment]
@minhtridn2001 Review dùm nha :fireworks:

**Comment by minhtridn2001** [comment]
Đã review!

**Comment by trungdq88** [comment]
Link gắn bị sai. Phải là `cardID=..` mới đúng.
Lỗi hiển nhiên vậy mà ko ai phát hiện ra. Review kỹ tý nha mấy anh.

<img width="521" alt="screenshot 2015-07-10 13 24 07" src="https://cloud.githubusercontent.com/assets/4214509/8613247/12fa5678-2707-11e5-90a3-588bb4c90919.png">

**Comment by hydrangea8604** [comment]
Đã fix, @minhtridn2001 review lại dùm t nha :new:

**Comment by minhtridn2001** [comment]
OK sorry :D
