### ISSUE TITLE
Implement access log

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#303]

**Comment by trungdq88** [comment]
Anh nhớ kiểm tra các trường hợp thẻ trả về kết quả khác nhau (hợp lệ / không hợp lệ / sắp hết hạn...)
Ngoài ra nhớ test cả trường hợp thêm vi phạm cũng được ghi vào access log.
<img width="944" alt="screenshot 2015-07-10 13 54 57" src="https://cloud.githubusercontent.com/assets/4214509/8613624/48457be2-270b-11e5-8665-23dd4c2e234b.png">

**Comment by phucnguyen60749** [comment]
review ok!
