### ISSUE TITLE
<Customer> Bug: customer chỉ xem được thẻ đã được active của customer đó

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#305]
2 điều kiện để hiển thị detail card:
- Trạng thái phải là "Hoạt động"
- Thẻ (Card Instance) phải thuộc về hợp đồng của customer đang login.

Nếu không thoả mãn thì redirect về /error/404

**Comment by minhtridn2001** [comment]
Review giúp a nhé Trung

**Comment by trungdq88** [comment]
:white_check_mark: Đã review.
