### ISSUE TITLE
Thêm trang 404

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#306]

**Comment by trungdq88** [comment]
Review please.

**Comment by phucnguyen60749** [comment]
a nghĩ nên cho cái hình hay gì đó vào! :)
![404-header-d7548](https://cloud.githubusercontent.com/assets/12363394/8614728/d72a758c-2716-11e5-8724-69d91c815072.png)

**Comment by trungdq88** [comment]
:white_check_mark: Đã thêm hình cho sinh động.

**Comment by phucnguyen60749** [comment]
ok see :+1:
