### ISSUE TITLE
<Customer> edit profile

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#307]

**Comment by phucnguyen60749** [comment]
@hydrangea8604  review dùm mình

**Comment by hydrangea8604** [comment]
Khi F5, các text box bị lóa lên sau đó mới ẩn đi, nhìn xấu
![image](https://cloud.githubusercontent.com/assets/12366868/8614904/84d19494-2718-11e5-8ac6-cd8d3e533ebe.png)
Thông Tin Cá Nhân = Thông tin cá nhân
Chỉnh sữa thông tin = Chỉnh sửa thông tin
![image](https://cloud.githubusercontent.com/assets/12366868/8614779/4efb839e-2717-11e5-87b3-38ac730330c4.png)
Số đện thoại = Số điện thoại
3 field này là bắt buộc, phải có dấu * (như hình sau)
![image](https://cloud.githubusercontent.com/assets/12366868/8614795/71f0100e-2717-11e5-9019-097ba2286d99.png)
Số CMND/Hộ chiếu là không bắt buộc
![image](https://cloud.githubusercontent.com/assets/12366868/8614937/b7a9c26a-2718-11e5-9a96-0c7f0ac322b5.png)
![image](https://cloud.githubusercontent.com/assets/12366868/8614951/c41a4f92-2718-11e5-8742-8fda3e1d47b2.png)
Vì không kiểm tra email trùng, cho nên văng ra exception
http://pastebin.com/tiv31upX
![image](https://cloud.githubusercontent.com/assets/12366868/8615010/58401cba-2719-11e5-8d9c-c8e2e4eee3e8.png)
Placeholder là "Ví dụ" người dùng nên nhập cái gì vào
![image](https://cloud.githubusercontent.com/assets/12366868/8615021/7104afc2-2719-11e5-9aec-12d5f9126add.png)
Không hiểu tại sao nó không validate chiều dài ký tự ở client trước mà gởi lên server luôn.
![image](https://cloud.githubusercontent.com/assets/12366868/8615038/8b6c2552-2719-11e5-8b19-78ed3f6afb5b.png)

**Comment by trungdq88** [comment]
Em edit comment của anh Kha, thêm các check box để tiện theo dõi.

**Comment by phucnguyen60749** [comment]
- email trùng ? customer họ không edi email mà chỉ edit nữa filed khác thì sao! với lại lỗi không thay đổi email --> trùng email --> exception tui ko tái tạo lại dc lỗi!
- "không validate chiều dài ký tự ở client trước mà gởi lên server luôn" bên P có validate ở client mà
![untitled](https://cloud.githubusercontent.com/assets/12363394/8625052/6e2398fc-2766-11e5-9ce9-411113ccddc8.png)

**Comment by hydrangea8604** [comment]
Test case:
- [ ] Trùng email: trong bảng hệ thống có ít nhất 2 customer, edit customer 1, điền email customer 1 giống email customer 2, submit.
Solution:
    @AssertTrue(message = "Email đã được đăng ký bởi người dùng khác")
    public boolean isValidEmail(){
        CustomerDao customerDao = new CustomerDao();
        return !customerDao.isExistByEmail(email);
    }
- [ ] Không validate __"chiều dài ký tự"__ ở client: điền chuỗi dưới 8 ký tự vào. VD: "222"
Reason: thiếu minlength
![image](https://cloud.githubusercontent.com/assets/12366868/8625754/eac08510-276a-11e5-92e6-5d5359ca2a2a.png)
Solution: Thêm minlength="8"

**Comment by phucnguyen60749** [comment]
ok thanh Kha nhé!

**Comment by hydrangea8604** [comment]
Dưới bảng database thấy có cột last_modified mà trên này mấy phần đều không thấy xử lý concurrency, phần này bỏ qua không cần xử lý hả?

**Comment by phucnguyen60749** [comment]
ý ong là tui wen update last_modified khi edit hả! !_!

**Comment by hydrangea8604** [comment]
Không biết, đọc code không thấy xử lý concurrency thì hỏi tại sao thôi. Nếu không xử lý thì update làm gì

**Comment by phucnguyen60749** [comment]
vậy là có! vì lỡ thằng staff cũng thay đổi thông tin customer cùng luc thì sao!

**Comment by phucnguyen60749** [comment]
ok het bug roi kha! :)

**Comment by hydrangea8604** [comment]
Vẫn không thấy code xử lý concurrency? Nếu chỉ update cái last_modified thì làm được gì đâu

**Comment by phucnguyen60749** [comment]
thì mỗi lần nó edit thì cập nhật lại last_modified đó là thời điểm để check mà!

**Comment by hydrangea8604** [comment]
Vậy code nào để check là thông tin khách hàng đó đã bị thay đổi bởi ai đó khác khi họ đang thực hiện việc thay đổi thông tin?

**Comment by phucnguyen60749** [comment]
chổ check currency đó tui kiếm chưa ra! can you help me!

**Comment by hydrangea8604** [comment]
Dùng dto thì có thể tham khảo RenewContractDto, trong đó có code, sửa lại contract thành customer là được

**Comment by phucnguyen60749** [comment]
ok check lai dum tui cai nua nha

**Comment by hydrangea8604** [comment]
Done

**Comment by trungdq88** [comment]
@phucnguyen60749 anh gắn số vào commit message giùm em nha.

**Comment by trungdq88** [comment]
Lỗi concurrency, không thể update được information.
Các bước check concurrency của anh thiếu 1 bước: gán ngày last_modified vào session khi view profile.

Hiện tại thì không update được information. Xem lại nha.
<img width="765" alt="screenshot 2015-07-11 15 13 18" src="https://cloud.githubusercontent.com/assets/4214509/8633006/614e21d2-27df-11e5-8b5c-212bb60983e1.png">

**Comment by hydrangea8604** [comment]
Xin lỗi @trungdq88, a đọc code nhầm file, cứ nhè vào cái ContractController đọc, quên mất phải đọc ở PersonalController mới đúng. Đầu óc bị gì rồi :confused:

**Comment by phucnguyen60749** [comment]
@hydrangea8604  xem lai dum nhe!

**Comment by hydrangea8604** [comment]
Đã review phần concurrency
