### ISSUE TITLE
Sau khi huỷ hợp đồng thì tự động deactive luôn thẻ gắn với hợp đồng đó.

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#313]

**Comment by hydrangea8604** [comment]
Review dùm nha @minhtridn2001

**Comment by minhtridn2001** [comment]
Review OK. Nhưng deactive instance rồi có đổi status của card lại thành available ko? @hydrangea8604 @trungdq88

**Comment by hydrangea8604** [comment]
Hôm qua lúc review nghe @trungdq88 nói với thầy là việc đó Staff phải làm bằng tay. Vậy ở bước này có cần làm tự động không thì không biết. Chờ Trung trả lời đi.

**Comment by trungdq88** [comment]
Không đổi status thành AVAILABLE, việc này staff phải làm bằng tay. Lý do là tránh trường hợp staff in nhầm thẻ đã bị deactive mà không biết.

**Comment by minhtridn2001** [comment]
OK!
