### ISSUE TITLE
Đối với hợp đồng REQUEST_CANCEL: thêm nút để không huỷ hợp đồng.

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#314]
Hiện tại lúc nhấn vào nút giải quyết thì chỉ có 1 option duy nhất cho staff là giải quyết huỷ hợp đồng, cần thêm một nút là "Tiếp tục duy trì hợp đồng", nhấn nút này tương đương với nhấn nút "Huỷ yêu cầu" bên customer.

You got the idea.

**Comment by hydrangea8604** [comment]
@minhtridn2001 Review dùm nha, bấm vào giải quyết sẽ hiện modal lựa chọn phương án, nếu chọn hủy hợp đồng thì modal hủy hợp đồng sẽ hiện, cho phép Staff nhập cancel note. Nếu chọn tiếp tục duy trì hợp đồng thì sẽ trực tiếp thực hiện luôn.

**Comment by minhtridn2001** [comment]
@hydrangea8604 Cái chỗ chọn phương án giải quyết đó Kha đặt label cho cái radio button để click vào chữ cũng được đi. Mà sao Kha ko thêm button từ chối yêu cầu luôn. Làm chi cực vậy :-/

Mà có business chỗ này cần hỏi @trungdq88 là từ chối yêu cầu có cần phải cho customer biết lý do hay là notification gì ko?

**Comment by trungdq88** [comment]
Vẫn chưa click vào chữ được mà? Anh @minhtridn2001 review kỹ giùm em anh ơi.
Với lại anh Kha đừng có làm 2 modal như thế này, rất bất tiện. Lúc click vào giải quyết thì staff phải thấy ngay được lý do yêu cầu huỷ của customer đã ghi.
Em biết để 2 modal như vậy thì đỡ phải code hơn nhưng đây là phần nằm trong core flow, nên anh chịu khó chút. Những phần phụ thì có thể sơ xài nhưng phần chính thì chăm chút 1 xíu, anh làm select box như lúc mình nói chuyện với nhau em thấy là hợp lý nhất đó.

**Comment by hydrangea8604** [comment]
Ok, để a làm lại

**Comment by minhtridn2001** [comment]
hmm. Click vào chữ được rồi mà

**Comment by trungdq88** [comment]
> hmm. Click vào chữ được rồi mà

Ok em xin lỗi, lúc commit cách thời điểm em comment có 5 phút nên chưa có xem code mới. Xác nhận là đã click vào chữ được.

**Comment by hydrangea8604** [comment]
@minhtridn2001 review dùm nha :whale:

**Comment by minhtridn2001** [comment]
OK rồi Kha :+1: @trungdq88 Trung có review lại ko? Với cái notification khi Staff từ chối yêu cầu hủy thì lại thông báo đến người customer là hợp đồng đã bắt đầu có hiệu lực. Do dùng chung hàm ?

**Comment by trungdq88** [comment]
Đã review ok rồi anh.

> Với cái notification khi Staff từ chối yêu cầu hủy thì lại thông báo đến người customer là hợp đồng đã bắt đầu có hiệu lực

Khi staff từ chối yêu cầu huỷ thì đâu có notification nào tới user đâu anh, trong requirement của mình không có cái đó. Có sự trùng hợp?

**Comment by hydrangea8604** [comment]
Chắc là bị dính hàm chỗ nào đó, chứ trong code của a ko có NotificationBuilder nào, a đang review lại

**Comment by minhtridn2001** [comment]
Close issue này nhé. Check rồi mà ko thấy cái hàm nào notify hết. Có gì mở issue khác sau.
