### ISSUE TITLE
<Customer> Bug: không thể gửi yêu cầu huỷ hợp đồng được.

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#315]
Tự nhiên bây giờ test lại thì không thể huỷ. Kèm theo rất nhiều lỗi như check 1 lúc được nhiều radio button, popup gia hạn không hiển thị ngày gia hạn đến, v...v...
<img width="1190" alt="screenshot 2015-07-10 20 16 48" src="https://cloud.githubusercontent.com/assets/4214509/8619353/b2a142fc-2740-11e5-86f7-ed29efe13a45.png">
<img width="970" alt="screenshot 2015-07-10 20 17 42" src="https://cloud.githubusercontent.com/assets/4214509/8619358/bbf1ba44-2740-11e5-9d1b-8a89ee444379.png">
<img width="959" alt="screenshot 2015-07-10 20 17 56" src="https://cloud.githubusercontent.com/assets/4214509/8619361/c533ede8-2740-11e5-9c6a-fa873cb7d7f1.png">

Ngoài việc fix, anh ghi rõ lý do vì sao lại bị như vậy lên đây cho em biết nha.
Trong lúc code cố gắng để ý, đừng làm bể chức năng cũ, tỷ lệ bug mà cao thế này thì càng về cuối đồ án rủi ro bug xuất hiện ngẫu nhiên rất là cao!

**Comment by trungdq88** [comment]
> Ngoài việc fix, anh ghi rõ lý do vì sao lại bị như vậy lên đây cho em biết nha.

**Comment by phucnguyen60749** [comment]
- them initialize() vào đầu trang customer.js làm các hàm trong customer.js không chạy! đã khắc phục

**Comment by trungdq88** [comment]
Đã khắc phục bằng cách nào vậy anh

**Comment by phucnguyen60749** [comment]
các function bị conflict! a bỏ initialize() wa bên trang personnal-information!
