### ISSUE TITLE
<Staff> Không thể chỉnh sữa nội dung punishment và accident 

### ISSUE THREAD

**Issue by phucnguyen60749** [trungdq88/insurance-card#316]

**Comment by hydrangea8604** [comment]
Lần sau có báo bug thì ghi rõ ra một chút, không thể chỉnh sửa là exception hay là như thế nào.
Lần này có phải là mọi thứ đều chỉnh sửa được, nhưng mã hợp đồng thì lại không thay đổi, đúng không? Hay một trường hợp nào khác?

**Comment by phucnguyen60749** [comment]
không edit đuoc thi báo là ko edit đc vào là thấy liền mà

**Comment by minhtridn2001** [comment]
Phúc nói rõ lỗi hơn được ko? Chứ trước đó vẫn edit đc mà. Cái mã hợp đồng t thấy ko nên cho sửa là đúng rồi, vì nó của contract hiện tại mình đang xem mà

**Comment by trungdq88** [comment]
Đã tái tạo được bug chưa anh?
P/S: Mã hợp đồng tất nhiên không được đổi.

**Comment by minhtridn2001** [comment]
Chưa em. Đang đợi Phúc confirm xem có phải lỗi sửa mã hợp đồng ko hay lỗi nào.

**Comment by hydrangea8604** [comment]
Với punishment và accident mà, lỡ Staff nhập accident & punishment nhầm hợp đồng thì họ có thể edit được?

**Comment by trungdq88** [comment]
Em vừa xem lại chỗ punishment và accident, có vẻ như không có vấn đề gì cả. Lúc trước em không edit được, nhưng giờ thì edit được rồi.
Chỉ có một vấn đề là anh đừng có để cái nút "Cập nhật lại thông tin" nó ẩn đi, nên để nó hiện ngay từ đầu luôn.

**Comment by hydrangea8604** [comment]
Đã cho nút "Cập nhật lại thông tin" hiện ngay từ đầu.

**Comment by minhtridn2001** [comment]
OK. Vậy close issue này nhé.
