### ISSUE TITLE
Liên kết staff configuration với bảng business rule

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#317]

**Comment by hydrangea8604** [comment]
@minhtridn2001 gelato :ice_cream:

**Comment by minhtridn2001** [comment]
:+1: :kiss:

**Comment by trungdq88** [comment]
Somehow, các loại phí vẫn chưa hoạt động đúng. Em chưa kiểm tra các rule khác. Anh @hydrangea8604 kiểm tra lại nhé.

<img width="852" alt="screenshot 2015-07-16 23 10 58" src="https://cloud.githubusercontent.com/assets/4214509/8728576/17c86448-2c10-11e5-9438-80ebabd06b31.png">
<img width="728" alt="screenshot 2015-07-16 23 11 05" src="https://cloud.githubusercontent.com/assets/4214509/8728580/1d6d005c-2c10-11e5-984d-b76b873fd185.png">

**Comment by minhtridn2001** [comment]
@trungdq88 A tưởng cái này là Liên kết staff configuration với bảng business rule (Nghĩa là có chỗ để lấy ra thôi). Chứ chưa thay đổi hết những gì implement mà?

**Comment by trungdq88** [comment]
Đâu phải.
Lúc trước code là dùng rule trong StaffConfiguration (file Constants), bây giờ mình liên kết cái StaffConfiguration đó vào database thì các rule sẽ cập nhật theo như trong database chứ? Không lẽ chỗ này là lấy những con số 50.000 VND, 10.000 VND ở một nơi nào khác?

**Comment by hydrangea8604** [comment]
Phần đó là bên customer mà, a chỉ implement vào phần staff thôi. Mấy con số 50, 10 đó vẫn là lấy từ constant

**Comment by minhtridn2001** [comment]
Ah cái chỗ đó anh lấy từ Constant.

**Comment by trungdq88** [comment]
Quy tắc là không bao giờ lấy thẳng số từ Constant mà phải thông qua ConfigUtils. Chính vì cái này mà hôm trước họp em mới hỏi là "có chỗ nào dùng thẳng biến từ Constants hay không". Vậy có những chỗ nào đang xài rule từ Constants anh liệt kê ra và implement luôn được không?

**Comment by hydrangea8604** [comment]
Phần bên Staff, những cái nào lấy từ Staff Config a đều đã lấy từ BusinessInfoDao và Entity. Còn bên Customer thì a ko biết =.=!

**Comment by minhtridn2001** [comment]
Chỉ có FEE thôi. Để anh implement

**Comment by trungdq88** [comment]
@hydrangea8604 anh làm như vậy nè: **chỉ được lấy các rule thông qua ConfigUtils và chỉ có ConfigUtils thôi**. Không được lấy thẳng từ Constants (nhưng bây giờ thì rule trong constants ko xài nữa rồi, ko nói), cũng **không được lấy bằng cách tự tạo BusinessRuleDao mới**.

Nhớ, lúc nào cũng lấy từ ConfigUtils. Lấy từ 1 nguồn thì sau này có chuyển đổi hay refactor sẽ dễ hơn.

**Comment by hydrangea8604** [comment]
Ừ, a đang làm đúng như e nói mà? ConfigUtils khởi tạo BusinessRulesDao, BusinessRulesEntity entity = dao.getLastActiveBusinessRule();
Các field trong ConfigUtils cũng đều tính toán trong get set. A đâu còn dùng cái Constant nữa

**Comment by trungdq88** [comment]
@hydrangea8604 ok, ý em là ở các chỗ DTO, validate hoặc trong các business, anh cũng đừng có tạo BusinessRulesDao mà phải gọi hàm từ ConfigUtils.

Nếu hiện tại đang như vậy thì tốt rồi.

**Comment by minhtridn2001** [comment]
#229

**Comment by minhtridn2001** [comment]
Hoàn thành xong #229 thì close cái này

**Comment by trungdq88** [comment]
Task này coi như là liên kết ConfigUtils và bảng BusinessRule. Phần implement sẽ thực hiện ở task #344. Task #229 là một phần của task #334.

Close :ok_hand:
