### ISSUE TITLE
<Admin> Implement manage Contract Type

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#318]

**Comment by minhtridn2001** [comment]
@trungdq88 Em review giúp a nhé: /admin/contractType
Em xem bên em có bị lỗi font truyền param Tiếng Việt khi Thêm contract type ko?

**Comment by trungdq88** [comment]
- [ ] Mấy cái form anh cho thêm placeholder và cách ra 1 chút. Giờ nó hiện sát nhau quá.
<img width="772" alt="screenshot 2015-07-15 14 04 39" src="https://cloud.githubusercontent.com/assets/4214509/8692665/b2196e96-2afa-11e5-96c8-5996cc2dc39a.png">

- [ ] Có bị lỗi font. Cách fix: anh đừng truyền message qua url, dùng errorCode = 123 rồi trong jsp if else đi.
<img width="546" alt="screenshot 2015-07-15 14 04 51" src="https://cloud.githubusercontent.com/assets/4214509/8692675/c7ee5d94-2afa-11e5-8d75-2bf36a39f849.png">

- [ ] Bỏ dấu $
<img width="243" alt="screenshot 2015-07-15 14 04 37" src="https://cloud.githubusercontent.com/assets/4214509/8692681/ce51aa42-2afa-11e5-8344-478f23222336.png">

- [ ] Lúc xoá thì phải confirm "Bạn có chắc chắn?"

- [ ] Nếu không xoá được hợp đồng thì phải ghi rõ lý do: "Đang có hợp đồng sử dụng loại hợp đồng này."

**Comment by minhtridn2001** [comment]
@trungdq88 Em review lại nhé :yellow_heart:

**Comment by trungdq88** [comment]
Đã review :white_check_mark:
