### ISSUE TITLE
<Staff> Chỉnh sửa profile customer

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#321]

**Comment by minhtridn2001** [comment]
Done!

**Comment by hydrangea8604** [comment]
Nhìn lướt qua (do bên contract detail cũng dùng trang này - include) thì thấy nhiều vấn đề quá, chắc Trí lấy xuống xem lại.
Nút chỉnh sửa có sẵn format rồi, sửa lại thành tag a + href để send request get chứ đừng sửa class và icon font-awesome.
Mấy cái title thiếu dấu *
Số CMND / Hộ chiếu bị xuống hàng.
Địa chỉ chưa có geolocation
Nút trở về và cập nhật nên cùng để vào class text-center. Trở về ở trên, cập nhật ở dưới.
Nút trở về là navigation nên phải là btn-default. Nút cập nhật phải là btn-primary (có thể sửa thành chữ "Cập nhật thông tin khách hàng")

**Comment by minhtridn2001** [comment]
Ba-Ba-Ba, Ba-Ba-Na-Na :sob:

**Comment by trungdq88** [comment]
Em tổng hợp lại review của em và anh Kha bên trên:
- [ ] Dùng nút chỉnh sửa này nha, đừng có đổi nút kia, nhìn xấu.
<img width="143" alt="screenshot 2015-07-16 15 21 14" src="https://cloud.githubusercontent.com/assets/4214509/8718395/5a358ffa-2bce-11e5-8473-a83aa019ade3.png">

- [ ] Mấy cái title thiếu dấu *
- [ ] Label Số CMND / Hộ chiếu bị xuống hàng.
<img width="405" alt="screenshot 2015-07-16 15 22 12" src="https://cloud.githubusercontent.com/assets/4214509/8718415/73550f9c-2bce-11e5-85fe-c2fecb733f77.png">

- [ ] Địa chỉ chưa có geolocation
- [ ] Nút trở về để màu trắng (default), nút cập nhật để màu xanh dương (primary)

**Comment by minhtridn2001** [comment]
Đã fix theo review của 2 bạn. Trung review lại giúp a nha. Mạng chậm quá check ko đc mấy cái checkbox kia :sob:

**Comment by trungdq88** [comment]
CMND / Hộ chiếu không bắt buộc, bỏ dấu * đi.
<img width="479" alt="screenshot 2015-07-16 20 40 16" src="https://cloud.githubusercontent.com/assets/4214509/8724830/e96c3486-2bfa-11e5-8a62-b85e86338224.png">

Fix xong có thể tự close. :pencil2:
