### ISSUE TITLE
<Customer> Bug: Edit profile: lỗi concurrency

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#322]
1. Vào trang profile
2. Chỉnh sửa, nhập thông tin mới.
3. Nhấn nút "Lưu thay đổi", trang được load lại, thông tin thay đổi OK.
4. Ngay tại trang đó, nhấn nút "Chỉnh sửa thông tin"
5. Nhập thông tin mới, nhấn "Lưu thay đổi" > Hiện lỗi concurrency.

<img width="829" alt="screenshot 2015-07-13 21 22 06" src="https://cloud.githubusercontent.com/assets/4214509/8651782/3ba9877e-29a5-11e5-9b3f-1ba18c5414ba.png">

**Comment by phucnguyen60749** [comment]
@hydrangea8604  review dum

**Comment by hydrangea8604** [comment]
Đã review lại theo test case của Trung, OK
