### ISSUE TITLE
<Staff> Trang chi tiết hợp đồng: implement các nút chỉnh sửa.

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#324]

**Comment by hydrangea8604** [comment]
Chỉ có nút chỉnh sửa thông tin xe cơ giới thôi, @minhtridn2001 review dùm nha

**Comment by trungdq88** [comment]
Cái nút chỉnh sửa cũ nhìn nhỏ nhỏ đẹp đẹp mà, đổi chi thành cái nút bự chảng vậy. 💤
<img width="1005" alt="screenshot 2015-07-16 15 33 44" src="https://cloud.githubusercontent.com/assets/4214509/8718624/14b0c27c-2bd0-11e5-92c0-20b0342fc1ac.png">

**Comment by hydrangea8604** [comment]
Phần này dùng chung với trang customer-detail, @minhtridn2001 sửa bên kia nên bên này nó bị đổi theo. Còn bị hợp đồng Cancelled mà không hide đi nữa, a đã báo bên kia cho @minhtridn2001 sửa rồi

**Comment by minhtridn2001** [comment]
t sửa cái nút lại rồi ak :D đang review phần của Kha

**Comment by minhtridn2001** [comment]
Còn cái vụ hide khi hợp đồng Cancelled sao t ko thấy Kha nói lúc nào nhỉ?

**Comment by hydrangea8604** [comment]
=.=! Chỉ cần sửa tag button thành a và thêm href là nó sẽ không bị ảnh hưởng. Ông bỏ cái type=button đi mất rồi nên giờ nó bị, để t sửa cho.

**Comment by hydrangea8604** [comment]
Ok, đã sửa lại

**Comment by minhtridn2001** [comment]
Thanks Kha :kissing_closed_eyes:

**Comment by minhtridn2001** [comment]
Có 2 lỗi này: 
- [ ] Số người được phép chở: client validate là 1000, server lại 100. => sửa lại 100 hết.
- [ ] Khi validate server side fail, ko thấy lưu giữ giá trị đã submitted.
Mà Kha còn task để t sửa cho

**Comment by hydrangea8604** [comment]
Bởi vì value có sẵn, truyền về không biết làm sao xử lý nên hiện cái gì. Chỉ nghĩ ra cách ngu là dùng c:if, mà vậy thì phải copy mấy cái div.

**Comment by minhtridn2001** [comment]
T sửa rồi. Ban đầu gửi trả lại attribute CONTRACT luôn rồi if ở getEditVehicle() mà tại mấy trang include cũng phải xài ContractEntity cho nên là dùng <c:if ở chỗ value thôi :D

**Comment by hydrangea8604** [comment]
Ok, cảm ơn
