### ISSUE TITLE
<Customer> Trang contract detail: đưa bảng thẻ đang hoạt động vào cuối tab "Thông tin hợp đồng" luôn.

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#329]
Lý do là tại một thời điểm chỉ có 1 thẻ duy nhất được active, do đó không cần phải có 1 tab riêng như vậy.

**Comment by phucnguyen60749** [comment]
cái này ko phải bug mà là tag nhé!

**Comment by phucnguyen60749** [comment]
@hydrangea8604  review dùm nhé! cái thông tin thẻ tui để dạng collapse!

**Comment by hydrangea8604** [comment]
![image](https://cloud.githubusercontent.com/assets/12366868/8718436/9d1a3f3c-2bce-11e5-8c06-af7d490537a8.png)
Chỉ có 1 thẻ duy nhất, không cần collapse đâu, đã bỏ khỏi tab cho nhìn thấy trực tiếp rồi mà, giấu nó đi làm gì nữa.
Thông tin dài như thế này thì bị xuống hàng hết. Xem lại xử lý thế nào

**Comment by phucnguyen60749** [comment]
- Đã chỉnh lại thông tin không bị xuống hàng! 
- Tui vẫn giữ collapse nhé! Trang detail nhiều thông tin biểu diễn nhìn rất rối mắt! Để collapse tui thấy ổn! :)

**Comment by trungdq88** [comment]
@phucnguyen60749 không cần để collapse đâu anh. Chỉ có 1 thẻ, diện tích chiếm cũng không nhiều, không lý do gì mà phải ẩn đi cả.

**Comment by phucnguyen60749** [comment]
- ok đã bỏ collapse! vẫn thấy để collapse đẹp hơn! :)

**Comment by hydrangea8604** [comment]
Ok, đã review
