### ISSUE TITLE
<Staff> Implement trang thông tin chung

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#331]
- Đổi "Hợp đồng mới" thành "Hợp đồng", hiện tổng số hợp đồng đang có.
- "Yêu cầu bồi thường" - hiện số yêu cầu bồi thường chưa giải quyết, link đến trang danh sách bồi thường.
- "Yêu cầu cấp thẻ mới", tương tự "Yêu cầu bồi thường".
- "Huỷ hợp đồng" đổi thành "Yêu cầu huỷ hợp đồng", hiện số hợp đồng đang được yêu cầu huỷ, chuyển đến trang danh sách hợp đồng.

<img width="954" alt="screenshot 2015-07-14 10 24 44" src="https://cloud.githubusercontent.com/assets/4214509/8665808/b09b8524-2a12-11e5-875a-0b16bcff2a40.png">

**Comment by minhtridn2001** [comment]
Review giúp a nhé :v:

**Comment by trungdq88** [comment]
:white_check_mark: Đã review.
