### ISSUE TITLE
<Customer> Yêu cầu thẻ mới thanh toán PayPal tính sai giá tiền deliveryRequest

### ISSUE THREAD

**Issue by minhtridn2001** [trungdq88/insurance-card#333]

**Comment by trungdq88** [comment]
Có hình gì không anh?

**Comment by minhtridn2001** [comment]
Khi vào PayPal qua trang thanh toán thì Tính tiền bị ngược deliveryRequest :D Mạng chậm quá a gửi hình ko đc. Tí a sửa lại rồi em review nhé

**Comment by minhtridn2001** [comment]
@trungdq88 A fix rồi. Em review qua nhé.

**Comment by trungdq88** [comment]
Đã thấy lỗi. Đã confirm hết lỗi. :+1:
