### ISSUE TITLE
<Customer> contract-detail: Lỗi hiển thị thông tin

### ISSUE THREAD

**Issue by hydrangea8604** [trungdq88/insurance-card#334]
__Cancelled__
- [x] Lý do & ghi chú có thể rất dài, có thể bị vượt khung.
![image](https://cloud.githubusercontent.com/assets/12366868/8718132/c5190b74-2bcb-11e5-916f-d95a7e472534.png)
Chỉnh sửa lại như bên Staff.
![image](https://cloud.githubusercontent.com/assets/12366868/8718136/d315da0e-2bcb-11e5-9f1a-e9f5c3549623.png)

__Ready__
- [x] Label chứa trạng thái của hợp đồng thừa fa trong class.

![image](https://cloud.githubusercontent.com/assets/12366868/8718186/80cdac76-2bcc-11e5-9aa1-18ac21a3866e.png)
__Modal Cancel contract__
- [x] Chỉnh lại chữ và các radio button cho cân với modal, giờ nó đang bị lệch về phía bên trái.
![image](https://cloud.githubusercontent.com/assets/12366868/8718209/c0605f3c-2bcc-11e5-964e-d8d391b2cf31.png)
- [x] Nút "Hủy Bỏ"  sửa thành "Đóng", class là "btn-default"... Sửa lại theo hình
![image](https://cloud.githubusercontent.com/assets/12366868/8718256/26cf5fac-2bcd-11e5-90f3-b10c64969d53.png)

__Request cancel__
- [x] Lý do hủy bị vượt khung
- [x] Nút "Hủy Yêu Cầu" sửa thành "Hủy yêu cầu", đưa xuống dưới lý do hủy, cách 1 br
![image](https://cloud.githubusercontent.com/assets/12366868/8718276/4d80d5ea-2bcd-11e5-90e8-4494c642645c.png)

**Comment by trungdq88** [comment]
:+1:

**Comment by phucnguyen60749** [comment]
đã fix! không bị vượt khung

**Comment by hydrangea8604** [comment]
- [ ] Cancel date và cancel reason bị lệch quá nhiều sang phải, nút Hủy yêu cầu lại lệch quá nhiều sang trái.
- [ ] 2 cái div trên để col-sm-3 thay thì 4
- [ ] div chứa button để class là đủ rồi, không cần padding-right

![image](https://cloud.githubusercontent.com/assets/12366868/8726408/43443306-2c04-11e5-8341-35a4d54b6456.png)

**Comment by phucnguyen60749** [comment]
@hydrangea8604  done

**Comment by hydrangea8604** [comment]
Đã review
