### ISSUE TITLE
<notification> Hợp đồng tự chuyển status từ Pending --> No card

### ISSUE THREAD

**Issue by phucnguyen60749** [trungdq88/insurance-card#335]
- Hợp đồng tự chuyển status từ pending --> no card khi chưa được thanh toán! 
![1](https://cloud.githubusercontent.com/assets/12363394/8720141/1016b8d8-2bdb-11e5-87c7-3b02cd80568f.png)
![2](https://cloud.githubusercontent.com/assets/12363394/8720140/1013e68a-2bdb-11e5-9edd-36f8b5302d86.png)
![3](https://cloud.githubusercontent.com/assets/12363394/8720143/1018f710-2bdb-11e5-8beb-074e295b2f46.png)
![4](https://cloud.githubusercontent.com/assets/12363394/8720142/10176c1a-2bdb-11e5-8b05-1f51e8e3f745.png)

**Comment by phucnguyen60749** [comment]
- Đang ở trang list status là Pending khi vào detail thì chuyển sang No card

**Comment by trungdq88** [comment]
Do database dữ liệu sai. Ngày startDate và ngày expireDate khác nhau thì sẽ xem như là đã thanh toán rồi.
