### ISSUE TITLE
<Staff> Huỷ yêu cầu thẻ mới

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#337]

**Comment by minhtridn2001** [comment]
Review plz!

**Comment by trungdq88** [comment]
Hiện tại em không thấy nút huỷ trong trang contract detail đâu cả, có khi tại anh đặt sai chỗ làm nó không hiện? (Contract của em là status = no card).

Anh đừng cho hiện nút ở trang contract detail, anh cho hiện ở trang yêu cầu thẻ mới ấy nha. Anh cho hiện chung cột với nút thanh toán, đổi tên cột đó là "Thực hiện" (text cũ là "Thanh toán" không phù hợp nữa") và đưa cộn "Thực hiện" ra cuối.

**Comment by minhtridn2001** [comment]
Em xem thử thế này ok ko nha

**Comment by trungdq88** [comment]
Hiện tại vẫn còn các lỗi sau:

> - [ ] Cho hiện nút Huỷ ở trang detail của customer luôn.
> - [ ] Hiện tại nếu Yêu cầu thẻ mới kèm Huỷ thẻ cũ thì ở trang Danh sách yêu cầu thẻ mới của customer và staff vẫn hiện nút "Huỷ" (phải ẩn đi vì đã huỷ thẻ cũ thì ko thể huỷ yêu cầu được)
> - [ ] Nếu Yêu cầu thẻ mới + huỷ thẻ cũ thì ở trang contract detail của customer không hiện label "Đang yêu cầu thẻ mới".

Em close issue này, chuyển qua làm việc ở issue #338 nha.
