### ISSUE TITLE
<Customer> Huỷ yêu cầu thẻ mới.

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#338]

**Comment by minhtridn2001** [comment]
Review giúp a nhé Trung :sos:

**Comment by trungdq88** [comment]
Anh vẫn cho hiện cái label "Đang yêu cầu thẻ mới nha", xong thì hiện nút "Huỷ" nhỏ nhỏ ngay cạnh đó là được rồi. Ví dụ hiện tại trong trường hợp yêu cầu thẻ mới + huỷ thẻ cũ thì chỗ đó trống không, người dùng không biết là đang yêu cầu thẻ.

**Comment by minhtridn2001** [comment]
A đang cho hiện nút hủy ở trang list yêu cầu thẻ mới giống như bên Staff. Em xem đc ko nha

**Comment by trungdq88** [comment]
- [ ] Cho hiện nút Huỷ ở trang detail của customer luôn.
- [ ] Hiện tại nếu Yêu cầu thẻ mới kèm Huỷ thẻ cũ thì ở trang Danh sách yêu cầu thẻ mới của customer và staff vẫn hiện nút "Huỷ" (phải ẩn đi vì đã huỷ thẻ cũ thì ko thể huỷ yêu cầu được)
- [ ] Nếu Yêu cầu thẻ mới + huỷ thẻ cũ thì ở trang contract detail của customer không hiện label "Đang yêu cầu thẻ mới".

**Comment by trungdq88** [comment]
Chỗ ẩn hiện nút "Huỷ" đã ok. Nhưng vẫn còn 3 lỗi bên trên, anh @minhtridn2001 check nhé.

**Comment by minhtridn2001** [comment]
@trungdq88 Anh fix  3 lỗi trên rồi nha em.

**Comment by trungdq88** [comment]
Trường hợp Yêu cầu thẻ + đã thanh toán qua paypal thì nút hủy không hiện (cả staff và customer). Anh fix cái này nha.
