### ISSUE TITLE
<Customer> Chỉnh sửa lại trang gửi yêu cầu compensation 

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#339]
Trang yêu cầu compensation bên staff làm rất đẹp. Có thể chỉnh cho bên customer cũng giống như vậy được không? Vì phần yêu cầu bồi thường bên customer mới là core flow.

(hình bên staff)
<img width="920" alt="screenshot 2015-07-16 22 11 38" src="https://cloud.githubusercontent.com/assets/4214509/8727056/ca5b890e-2c07-11e5-8c09-1143cfaefab4.png">

**Comment by phucnguyen60749** [comment]
@hydrangea8604  giong trang ben staff! ben staff them <br/> cho cai nut gui boi yeu cau boi thuong nhe!  no sat voi footer

**Comment by hydrangea8604** [comment]
Bên staff nó sát là do để màn hình rộng thôi, thu gọn lại 1000 là nó sẽ có br. Mà để đưa nó vào trong div luôn

**Comment by hydrangea8604** [comment]
Đã review, mà nhớ cái này có gắn link mà? Gắn link vào là có thể close.
![image](https://cloud.githubusercontent.com/assets/12366868/8765941/751d1008-2e4f-11e5-8694-fcf1fab8eef3.png)

**Comment by phucnguyen60749** [comment]
đã add link

**Comment by hydrangea8604** [comment]
Lỡ làm thì làm cho trót, gắn vào cả customer name luôn đi :)
