### ISSUE TITLE
<Staff> Yêu cầu bồi thường: Trọng tải/số chỗ ngồi: min char = 1 (hiện tại = 2)

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#340]
Trọng tải có thể cho nhập 1 ký tự. Hồi đó có thể ko xem xét rõ, sửa lại validate client & server luôn.

<img width="499" alt="screenshot 2015-07-16 22 14 42" src="https://cloud.githubusercontent.com/assets/4214509/8727112/2658a02a-2c08-11e5-9f0f-c0db97bd13f9.png">

**Comment by minhtridn2001** [comment]
@hydrangea8604 Kha rảnh review lại nhé
