### ISSUE TITLE
Implement các business rule vào code có sẵn.

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#344]
### Vấn đề
Hiện tại một số đoạn code chưa sử dụng các giá trị từ business rule (do trước đây không tồn tại business rule). Cần implement cho đầy đủ.

Em cần mọi người kiểm tra hết **tất cả các giá trị của business rule** sau đó **liệt kê các chức năng có dùng tới các giá trị đó**, sau cùng là implement cho chỗ đó.

### Ví dụ một chỗ mới phát hiện:
> Thời hạn mặc định là 24 tháng
> <img width="512" alt="screenshot 2015-07-17 00 15 54" src="https://cloud.githubusercontent.com/assets/4214509/8730100/27574ac4-2c19-11e5-910c-0945e1c29a1d.png">
> Chỗ này vẫn hiện 1 năm
> <img width="278" alt="screenshot 2015-07-17 00 12 09" src="https://cloud.githubusercontent.com/assets/4214509/8730108/343ca130-2c19-11e5-992d-8eaa57ccbe3a.png">
> Ở đây cũng vậy.
> <img width="342" alt="screenshot 2015-07-17 00 11 05" src="https://cloud.githubusercontent.com/assets/4214509/8730116/3c1ac814-2c19-11e5-989f-4e7a8a787418.png">
> Lúc tạo hợp đồng mới thì thời hạn cũng chỉ có 1 năm
> <img width="406" alt="screenshot 2015-07-17 00 13 15" src="https://cloud.githubusercontent.com/assets/4214509/8730141/53a4ce12-2c19-11e5-8cb8-e418fda5d1f7.png">
> Ở trang tạo hợp đồng mới của staff, giá trị cũng hiển thị có 1 năm
> <img width="601" alt="screenshot 2015-07-17 00 18 48" src="https://cloud.githubusercontent.com/assets/4214509/8730162/78ba411e-2c19-11e5-8b80-3cf00399d863.png">
> Tương tự, trang tạo hợp đồng mới của customer:
> <img width="467" alt="screenshot 2015-07-17 00 19 46" src="https://cloud.githubusercontent.com/assets/4214509/8730188/99366454-2c19-11e5-9ace-97fb55b09f96.png">

Đó là chỉ có giá trị **Thời hạn mặc định của hợp đồng**, chúng ta cần phải kiểm tra cả những giá trị khác. Ví dụ trong Scheduler em còn thấy sử dụng biến từ Constants (các giá trị thời hạn thông báo HĐ sắp hết hạn lần 1/lần 2/lần 3)...

## Cách thực hiện:
Em sẽ liệt kê các rule kèm theo các chỗ cần sửa ở comment đầu tiên của issue này, mọi người sẽ bổ sung bằng cách edit comment của em. Sau khi đầy đủ thì sẽ bắt đầu implement, em sẽ assign cho một người hoặc chia thành các phần để làm (tính sau).

**Comment by trungdq88** [comment]
### Thời hạn mặc định của hợp đồng:
- [ ] Trang public: label thời hạn 1 năm
- [ ] Trang register: thời hạn 1 năm
- [ ] Trang register: sau khi thanh toán thì gán giá trị expiredDate cách 1 năm.
- [ ] Trang tạo contract của staff (thông tin lúc hiển thị)
- [ ] Trang tạo contract của customer (label 1 thời hạn 1 năm)
- [ ] Trang hoàn tất thanh toán của staff
- [ ] Trang hoàn tất thanh toán của customer
- [ ] 

### Thời gian thông báo hợp đồng sắp hết hạn lần 1 (lần 2, lần 3)
- [ ] Scheduler Business

**Comment by trungdq88** [comment]
@phucnguyen60749 @minhtridn2001 @hydrangea8604 mọi người vào bổ sung nha.

**Comment by trungdq88** [comment]
Em vừa gắn tên vào các task ở comment bên trên, mọi người implement xong thì check vào và assign lại cho người tiếp theo nhé. Đầu tiên assign cho anh @hydrangea8604.

**Comment by hydrangea8604** [comment]
@minhtridn2001 Bàn giao công trình, mời đồng chí kiểm tra và hoàn thiện phần của mình theo nghĩa vụ đã được Quang Trung bệ hạ giao phó :flags:

**Comment by minhtridn2001** [comment]
@phucnguyen60749 Phúc ít làm trước đi P. Khỏi chờ, t còn nhiều task quá

**Comment by minhtridn2001** [comment]
Done! @phucnguyen60749 làm nốt nhé.

**Comment by phucnguyen60749** [comment]
@hydrangea8604  review dum nhe! 
- mấy chổ format date time lúc view P thấy chưa ổn lắm
@minhtridn2001  
         ContractEntity contract = contractDao.create(contractEntity);
        // Send notification
        NotificationBusiness notif = new NotificationBusiness();
        ContractEntity notifContract = contractDao.read(contract.getContractCode());
        notif.send(NotificationBuilder.customerCreateContract(notifContract));

đoạn code này trong hàm RegisterInformationDto (RegisterBusiness) P thấy trí chưa kiểm tra contract mới được tạo có thành công không trước khi gọi tới NotificationBusiness !

**Comment by hydrangea8604** [comment]
![image](https://cloud.githubusercontent.com/assets/12366868/8765983/bce81b7e-2e51-11e5-845f-4d5e1b21ed96.png)
- [ ] Lỗi hàm tính ngày, tháng 2 năm 2017 không có ngày 29
- [ ] Nếu có thể thì dùng label để hiển thị Thời điểm hết hiệu lực, disabled input không hay lắm.
- [ ] Thiếu config: Ngày bắt đầu hợp đồng sau ngày hiện tại (startDateMax)
- [ ] Bỏ bớt br dưới nút Thêm hợp đồng
- [ ] Trường hợp config như sau:
![image](https://cloud.githubusercontent.com/assets/12366868/8766055/2ae272ee-2e54-11e5-9cee-25232e2914b9.png)

Thì hiển thị giá trị như sau:
![image](https://cloud.githubusercontent.com/assets/12366868/8766059/3b65637e-2e54-11e5-9427-162d887ec1d8.png)

Thanh toán paypal OK lại ra như thế này:
![image](https://cloud.githubusercontent.com/assets/12366868/8766075/7325b39a-2e54-11e5-83e0-ecb4ee597b84.png)

- [ ] Trong **CustomerCreateContractDto** không thấy code validate server startDateMin, Max, contract term...

**Comment by phucnguyen60749** [comment]
- đang tính hỏi cái thời gian mặc đinh hợp đồng trong config rule ko có giới hạn là bao nhiêu hả! 
- Thiếu config: Ngày bắt đầu hợp đồng sau ngày hiện tại (startDateMax) khi nhấn nút "Thêm hợp đồng" nó sẻ báo! 
- Trong CustomerCreateContractDto không thấy code validate server startDateMin, Max, contract term (cái này hàm DTO của trí tui sữa lun hay sao! )

**Comment by hydrangea8604** [comment]
```
<div class="col-sm-3">
       <input required type="date" name="contract:startDate"
                 min="<%=new Date().getYear()+1900%>-<%=(new Date().getMonth()+1)<10?"0"+(new Date().getMonth()+1):(new Date().getMonth()+1)%>-<%=(new Date().getDate())<10?"0"+(new Date().getDate()):(new Date().getDate())%>"
        title="Vui lòng chọn ngày bắt đầu"
        value="${startDate}"
        class="form-control" id="dateDefault"
       />
</div>
```
Code thế này, search .max cũng không có cái nào thì tự báo bằng niềm tin

**Comment by phucnguyen60749** [comment]
view history dum cai! chổ đó Trí implement

**Comment by hydrangea8604** [comment]
Vậy thì ông nói nó sẽ báo làm chi, t đâu biết code ai gõ, chỉ cần biết review ra vấn đề đó rồi đưa lên thôi, handle thế nào thì tự đi discuss

**Comment by phucnguyen60749** [comment]
click vào thêm hợp đồng mới nếu ngày start nhỏ hơn ngày hiện tại thì nó sẽ báo html5!

**Comment by trungdq88** [comment]
> @trungdq88 cái thời gian mặc đinh hợp đồng trong config rule ko có giới hạn là bao nhiêu hả!

Trong config rule thì staff thích đặt bao nhiêu cũng được, không có giới hạn, miễn là số nguyên dương.

**Comment by phucnguyen60749** [comment]
- Nếu có thể thì dùng label để hiển thị Thời điểm hết hiệu lực, disabled input không hay lắm--> cái này là form input tui để input lun cho đồng bộ!

**Comment by trungdq88** [comment]
> Trang hoàn tất thanh toán của customer - PhucNH
> Hoàn tất thanh toán (Đã làm từ trước)

Em có ghi cái này mà chưa thấy implement. Mọi người đọc kỹ ghi chú giúp em nha. Implement thì đọc 1 lượt, review thì đọc lại 1 lượt nữa để khỏi sai sót.

Các phần chưa thấy implement còn sót lại:

- [ ] Chức năng hoàn tất thanh toán của customer vẫn còn tính ngày tháng sai. - PhucNH (Customer tạo hợp đồng, tới trang thanh toán thì ngừng lại, mở trang contract detail > Hoàn tất thanh toán online bằng paypal > pay xong thì vẫn chỉ cộng thêm 1 năm).

- [ ] Tương tự chức năng hoàn tất thanh toán bên staff. - KhaNC

**Comment by hydrangea8604** [comment]
Phần complete payment của a đã xong, xin lỗi @trungdq88, quên mất dưới business dùng hàm addOneYear ở DateUtils. Cứ nghĩ là task chỉ có set min max paidDate nên sót.

**Comment by trungdq88** [comment]
Done. :checkered_flag:

**Comment by hydrangea8604** [comment]
Ở trên a review còn 2 cái chưa làm mà? Ví dụ tạo hợp đồng có thể bắt đầu từ năm 2016, dù __Ngày bắt đầu hợp đồng sau ngày hiện tại__ là __60 ngày__. Cũng chưa thấy các hàm validate trong DTO

**Comment by trungdq88** [comment]
Thiếu sót.

- [ ] Thiếu config: Ngày bắt đầu hợp đồng sau ngày hiện tại (startDateMax)

Anh @phucnguyen60749 fix nốt nha.

Còn cái này chuyển qua issue #360
- [ ] Trong CustomerCreateContractDto không thấy code validate server startDateMin, Max, contract term...

**Comment by minhtridn2001** [comment]
Trong cái CustomerCreateContractDto có hàm kiểm tra ngày bắt đầu rồi mà: 
```
@AssertTrue(message = "Ngày bắt đầu phải kể từ ngày hôm nay trở đi")
    private boolean isValidStartDate() {...}
```

**Comment by phucnguyen60749** [comment]
cái dto là thiếu validate với business rule Trí ới! :))

**Comment by hydrangea8604** [comment]
Cái đó là cái khác @minhtridn2001, đang nói là ngày bắt đầu không được phép sau ngày quy định.

**Comment by minhtridn2001** [comment]
Đây là trang customer mà. Ngày bắt đầu khi nào chẳng đc @@ Tưởng thầy Khánh nói KH chọn ngày bắt đầu lúc nào cũng đc mà. Còn config là dành cho Nhân Viên thôi chứ ??? Phải hok ta. Cần confirm cái này @trungdq88 .

**Comment by phucnguyen60749** [comment]
:+1:  @minhtridn2001 nếu giới hạn vậy thì phải comment phía trên cho customer nó bit chứ!

**Comment by minhtridn2001** [comment]
Mạng t bị gì rồi Facebook load ko đc. Ai hỏi Trung giúp cái nha

**Comment by minhtridn2001** [comment]
Vì cái này giống Guest đăng ký hợp đồng. Lần trước thầy nói thích đăng ký khi nào cũng đc. Đến ngày thì active hợp đồng thôi

**Comment by trungdq88** [comment]
> Đây là trang customer mà. Ngày bắt đầu khi nào chẳng đc @@ Tưởng thầy Khánh nói KH chọn ngày bắt đầu lúc nào cũng đc mà. Còn config là dành cho Nhân Viên thôi chứ ??? Phải hok ta. Cần confirm cái này @trungdq88 .

Em cũng nhớ là thầy nói customer chọn lúc nào cũng được, vậy tại sao lại có rule này nhỉ? Nếu customer được chọn thoải mái thì staff cũng phải được như thế chứ?

**Comment by trungdq88** [comment]
Vậy bây giờ mình biểu quyết cho chỗ này. Ý kiến mọi người thế nào?
Theo em thì để cho customer chọn thoải mái là ok.

**Comment by phucnguyen60749** [comment]
- mình chọn phương án cho customer chọn thoải mái!

**Comment by trungdq88** [comment]
Nếu để customer chọn thoải mái thì cũng không được, nếu customer chọn tới năm 2200 thì rõ ràng là không đúng. Vậy em nghĩ là mình vẫn implement rule này, và trong admin config sẽ đặt giới hạn là 5 năm sau. (= 365 * 5 ngày)

@hydrangea8604 @phucnguyen60749 @minhtridn2001 quyết định vậy nhé.

**Comment by hydrangea8604** [comment]
:white_check_mark: Áp dụng giới hạn ngày bắt đầu hợp đồng cho cả người dùng (both home & customer create new contract page)

**Comment by trungdq88** [comment]
Nếu để customer chọn thoải mái thì cũng không được, nếu customer chọn tới năm 2200 thì rõ ràng là không đúng. Vậy em nghĩ là mình vẫn implement rule này, và trong admin config sẽ đặt giới hạn là 5 năm sau. (= 365 * 5 ngày)

@hydrangea8604 @phucnguyen60749 @minhtridn2001 quyết định vậy nhé.

**Comment by minhtridn2001** [comment]
T cũng vote ko giới hạn. Hoặc nếu có sử dụng startDateMax thì set thời gian nó lên cao 1 tí. Lỡ mai này thay đổi business phải dùng tới thì ko phải thay đổi lại nữa.

**Comment by minhtridn2001** [comment]
ok Trung :+1:

**Comment by trungdq88** [comment]
> T cũng vote ko giới hạn. Hoặc nếu có sử dụng startDateMax thì set thời gian nó lên cao 1 tí. Lỡ mai này thay đổi business phải dùng tới thì ko phải thay đổi lại nữa.

Vậy là coi như đồng ý với phương án implement startDateMax với thời gian là 5 năm.

@phucnguyen60749 hy vọng là nãy giờ anh vẫn đang implement chứ không ngồi chờ kết quả thảo luận. Chừng nào xong thì assign em review nhé.

**Comment by hydrangea8604** [comment]
Bổ sung: đang config là __tháng__ nên 5 năm là 60 tháng.

**Comment by minhtridn2001** [comment]
Đâu có, startDate là ngày mà.

**Comment by phucnguyen60749** [comment]
ở đây nên tính theo năm

**Comment by hydrangea8604** [comment]
Ặc, mình lại lanh chanh, xin lỗi

**Comment by trungdq88** [comment]
> Bổ sung: đang config là tháng nên 5 năm là 60 tháng.

Hiện tại đang tính theo ngày chứ không phải tháng.

Anh @minhtridn2001 cũng đổi luôn cái này trong dummy data của business rule nha.

> ở đây nên tính theo năm

Giờ mình tính theo ngày rồi. Anh implement như đã bàn bạc nha.

**Comment by minhtridn2001** [comment]
OK. Vậy start_date_after trong dummy data sẽ là 365*5 = 1825 ngày nhé.

**Comment by phucnguyen60749** [comment]
@trungdq88 e review lai di

**Comment by trungdq88** [comment]
Trời, gì đây anh

```
Timestamp maxDate = DateUtils.addFiveYear(currentDate);
```

Cái số 5 năm là anh lấy từ trong config ra chứ không phải anh tự đặt như vậy đâu. Sửa lại nha.

**Comment by minhtridn2001** [comment]
@phucnguyen60749 Phúc phải lấy từ config chứ ko đc code cứng 5 năm vậy @@

**Comment by trungdq88** [comment]
@phucnguyen60749 với lại, còn phải validate ở client nữa chứ? Anh làm cẩn thận giúp em nha.

**Comment by phucnguyen60749** [comment]
- bay h còn vấn đề gì! validate client voi server dung ko!

**Comment by trungdq88** [comment]
- [ ] Giá trị startDateMax phải lấy từ config, không được code cứng.
- [ ] Validate ở server.
- [ ] Validate ở client.

**Comment by trungdq88** [comment]
Server validate message bị sai:
<img width="589" alt="screenshot 2015-07-20 01 33 29" src="https://cloud.githubusercontent.com/assets/4214509/8767212/5a9480c4-2e7f-11e5-8218-26feac811db7.png">

**Comment by trungdq88** [comment]
Done.
