### ISSUE TITLE
Thanh toán paypal: nếu click nhanh vào nút PayPal lúc trang vừa load thì hiện Exception Number Infinity or NaN

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#345]
Hiện tại bị exception **Number is Infinity or NaN** khi vào trang thanh toán mà click nhanh vào nút PayPal lúc trang vừa load. Trường hợp lúc xảy ra là đang renew contract của customer, giờ hệ thống đã được đổi tới thời điểm 18/07/2016.

Nguyên nhân có thể là (chỉ là dự đoán):
- Số tiền thanh toán được load bằng javascript và nếu click nhanh thì ko load kịp để chuyển qua PayPal
- Giờ hệ thống tại thời điểm thanh toán không đúng > PayPal không chấp nhận vì lý do bảo mật.
- Hàm lấy tỷ giá đô la từ Yahoo không hoạt động do giờ hệ thống bị sai.

**Trong cả 3 trường hợp đều phải fix không được cho hiện exception**.

Đây là core flow, cần xem xét kỹ lại trường hợp này: lý do, cách giải quyết.

Một số hình của exception (quên chụp exception trên web, xem tạm ở log của tomcat nha):

<img width="840" alt="screenshot 2015-07-17 11 33 20" src="https://cloud.githubusercontent.com/assets/4214509/8740676/f6622b32-2c77-11e5-8563-66825a070913.png">

<img width="738" alt="screenshot 2015-07-17 11 33 47" src="https://cloud.githubusercontent.com/assets/4214509/8740710/6ae3648a-2c78-11e5-9f54-b940acfa29cc.png">

**Comment by trungdq88** [comment]
- [ ] Cần cấu hình để Remote Deploy trên Windows XP, tránh deploy bằng tay (vì tốn thời gian lúc demo)

**Comment by trungdq88** [comment]
Anh Phúc review giúp nhé.

**Comment by phucnguyen60749** [comment]
đã test lại 5 lần không phát hiện lỗi như trên! close
