### ISSUE TITLE
Thay đổi nội dung các bảng hướng dẫn trong staff

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#346]
Các bảng hướng dẫn này đã có từ thời prototype, bây giờ đã có nhiều thay đổi.

**Comment by hydrangea8604** [comment]
Uhm, a sẽ tách ra riêng để dễ control nội dung

**Comment by hydrangea8604** [comment]
- [ ] Quy trình cấp lại thẻ mới: Yêu cầu thẻ mới
- [ ] Quy trình phát hành thẻ: Tạo hợp đồng thành công

**Comment by hydrangea8604** [comment]
@minhtridn2001 review dùm nha, cũng không thay đổi nhiều lắm.

**Comment by minhtridn2001** [comment]
OK :banana:
