### ISSUE TITLE
Sửa lại class diagram theo review của thầy Tài

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#347]
- [x] Thêm Notification và NotificationRead class.
- [x] Sửa lại các trọng số trong quan hệ NewCardRequest và CardInstance (như trong hình)
<img width="121" alt="screenshot 2015-07-17 14 28 05" src="https://cloud.githubusercontent.com/assets/4214509/8742492/3587eb0e-2c90-11e5-8b55-da5f39c81a15.png">
 - [x] Sửa lại class dictionary.

**Comment by minhtridn2001** [comment]
Review plz!

**Comment by trungdq88** [comment]
Đã review :+1:
