### ISSUE TITLE
<Admin> Bussiness change: cấu hình cho rule 1 tháng chỉnh sửa sau khi huỷ hợp đồng.

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#348]
Sau khi hợp đồng hủy, trong vòng 1 tháng cho phép người dùng nộp các văn bản cần thiết, cho phép Staff thêm yêu cầu bồi thường, thông báo tai nạn, vi phạm… trong thời hạn trên.

**Comment by minhtridn2001** [comment]
Review plz! :money_with_wings:

**Comment by trungdq88** [comment]
Done :checkered_flag:
