### ISSUE TITLE
<Staff> Implement 1 tháng chỉnh sửa sau khi huỷ hợp đồng.

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#349]
Dùng giá trị rule ở #348

**Comment by trungdq88** [comment]
Đã implement xong, issue này có thể bắt đầu làm. 
Dùng hàm `ConfigUtils#getUpdateContractDueDate` để lấy giá trị nhé.

**Comment by hydrangea8604** [comment]
@minhtridn2001 Papoi :tada:

**Comment by minhtridn2001** [comment]
@hydrangea8604 Có cần validate bên phía server hok Kha nhỉ

**Comment by hydrangea8604** [comment]
Chắc là optional, để làm

**Comment by hydrangea8604** [comment]
Để tạo issue khác, close cái này đi Trí

**Comment by minhtridn2001** [comment]
OK!

**Comment by hydrangea8604** [comment]
Implement validate server-side here #360
