### ISSUE TITLE
<Customer> Implement 1 tháng chỉnh sửa sau khi huỷ hợp đồng

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#350]
Dùng giá trị rule ở #348

**Comment by trungdq88** [comment]
Đã implement xong, issue này có thể bắt đầu làm. 
Dùng hàm `ConfigUtils#getUpdateContractDueDate` để lấy giá trị nhé.

**Comment by phucnguyen60749** [comment]
@hydrangea8604  :8ball:

**Comment by hydrangea8604** [comment]
Đã review

**Comment by trungdq88** [comment]
Cách implement của anh @phucnguyen60749 chỉ có tác dụng ở client side, nếu truy cập thẳng vào đường link thì vẫn add được.

Tuy nhiên chỗ này là phần phụ, để vậy cũng không sao. Chỉ là vi phạm đạo đức người lập trình một tý.
