### ISSUE TITLE
<Admin> Contract Type: Xóa là deactivate, không cho hiển thị ở trên hệ thống (thêm field active)

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#351]
Implement luôn chức năng chỉnh sửa.

**Comment by minhtridn2001** [comment]
Review plz! :lollipop:

**Comment by trungdq88** [comment]
Đã review :white_check_mark:

**Comment by trungdq88** [comment]
Khoan đã,
Nút đóng anh để màu "default" (trắng) nha. Sửa lại rồi tự close nhé.
