### ISSUE TITLE
Mobile app: chuyển phần check thẻ lên server

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#352]

**Comment by trungdq88** [comment]
Anh @phucnguyen60749 review nhé, nhớ review các trường hợp check thẻ sau hoạt động đúng bình thường:

- Thẻ hợp lệ
- Thẻ không hợp lệ
- Thẻ hết hạn
- Thẻ sắp hết hạn

App: https://www.facebook.com/groups/insurancecard/885831944785747/
Database: 20150717.sql

**Comment by phucnguyen60749** [comment]
đã review!
