### ISSUE TITLE
Sửa lại tất cả các nút "Pick file" (đổi sang tiếng Việt)

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#353]

**Comment by trungdq88** [comment]
Assign trước cho anh @phucnguyen60749, anh Phúc làm xon thì assign cho anh @hydrangea8604.

**Comment by phucnguyen60749** [comment]
@hydrangea8604  nhan hang

**Comment by hydrangea8604** [comment]
Đã review phần của @phucnguyen60749, @minhtridn2001 review dùm nha

**Comment by minhtridn2001** [comment]
Đã review phần của Kha :love_hotel:
