### ISSUE TITLE
Implement ajax ở các trang Create Contract, Create compensation

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#356]
- [x] Create contract: select customer @trungdq88 demo
- [x] Create & edit compensation: select contract learn & implement from @trungdq88 code
- [x] Edit accident: select contract
- [x] Edit punishment: select contract

Assign to @hydrangea8604 when implement demo completed

**Comment by trungdq88** [comment]
As you will :game_die:

**Comment by hydrangea8604** [comment]
@minhtridn2001 Banana :banana:

**Comment by minhtridn2001** [comment]
@hydrangea8604 Kha sửa lại validate expiredDate bị sai xót chỗ nào rồi. Ko chọn được ngày nào hết.
![image](https://cloud.githubusercontent.com/assets/12363317/8762318/fc0229d8-2d9f-11e5-9366-908fcacb3ec1.png)

**Comment by minhtridn2001** [comment]
Review Ajax OK. Nhưng nhớ lần trước Trung có nói là edit thì ko cho thay đổi mã HD mà @trungdq88?

**Comment by trungdq88** [comment]
> Nhưng nhớ lần trước Trung có nói là edit thì ko cho thay đổi mã HD mà @trungdq88?

Chưa giải đáp mà đã close rồi anh?

Anh @hydrangea8604: edit compensation thì không được đổi mã hợp đồng, anh sửa lại nha.

**Comment by hydrangea8604** [comment]
Hôm nọ nói a cũng rep rồi mà, nếu là staff tạo mà họ nhập nhầm mã hợp đồng thì sao? Cho phép người ta sửa chứ?

**Comment by trungdq88** [comment]
Lúc tạo accident/punishment thì staff đó có cần chọn hợp đồng đâu, sao nhầm được nhỉ? Riêng cái compensationi thì ok.

**Comment by hydrangea8604** [comment]
Ok, để a sửa lại edit accident & punishment :yum:

**Comment by hydrangea8604** [comment]
Đã xóa, @minhtridn2001 :closed_book:

**Comment by minhtridn2001** [comment]
OK!
