### ISSUE TITLE
<Customer> Create compensation: tự động điền mặc định các thông tin của hợp đồng hiện tại.

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#357]

**Comment by phucnguyen60749** [comment]
@hydrangea8604 review dùm nhé! 
- các filed màu hồng nhạt là chưa nhập giá trị!

**Comment by trungdq88** [comment]
- [ ] Bỏ màu hồng nhạt ở các field chưa nhập giá trị.
- [ ] Field trọng tải bị thừa dấu / ở cuối.
<img width="368" alt="screenshot 2015-07-23 13 08 19" src="https://cloud.githubusercontent.com/assets/4214509/8844158/0e655eac-313c-11e5-8ea6-32dd81ca086a.png">

**Comment by phucnguyen60749** [comment]
- trang compensation rất nhiều field nhập trị! nếu ko thể hiện màu thì khó xem xét các giá trị chưa nhập! 
-  field trọng tải bị thừa dấu / ở cuối --> em xem trong db em contract đó có set_capacity ko!

**Comment by trungdq88** [comment]
> trang compensation rất nhiều field nhập trị! nếu ko thể hiện màu thì khó xem xét các giá trị chưa nhập!

Ok.

> field trọng tải bị thừa dấu / ở cuối --> em xem trong db em contract đó có set_capacity ko!

Trang chi tiết hợp đồng
<img width="897" alt="screenshot 2015-07-23 13 16 28" src="https://cloud.githubusercontent.com/assets/4214509/8844255/2a1beeee-313d-11e5-9cb3-d0b986e82832.png">

Database:
<img width="701" alt="screenshot 2015-07-23 13 18 04" src="https://cloud.githubusercontent.com/assets/4214509/8844274/5dc75ba2-313d-11e5-818d-9d3b6164a855.png">

Trang compensation
<img width="914" alt="screenshot 2015-07-23 13 16 41" src="https://cloud.githubusercontent.com/assets/4214509/8844276/6615c9f6-313d-11e5-863b-f3c9ecdc9532.png">

**Comment by phucnguyen60749** [comment]
- vậy a vẫn giữ lại màu hồng nhạt nhé! 
- db của e cái seat_capacity = null kìa!

**Comment by trungdq88** [comment]
> db của e cái seat_capacity = null kìa!

Field đó có thể null mà anh? Lúc đăng ký người dùng không nhập gì thì nó null thôi. Nhưng mà lỗi ở đây là cái "23/" đó anh, sao nó lại có dấu / ở cuối?

**Comment by trungdq88** [comment]
Trọng tải, số chỗ ngồi tức là chỉ hiện field "seat_capacity" thôi anh, sao anh đưa cái dung tích vào chi?

**Comment by phucnguyen60749** [comment]
à ý là trọng tải hoặc số chổ ngồi ! a tưởng là số trọng tải trên số chổ ngồi! để sữa lại!

**Comment by hydrangea8604** [comment]
Biển số xe gây tai nạn & trọng tải/số chỗ ngồi là của xe gây tai nạn. Khi bị tai nạn thì lấy thông tin xe gây tai nạn với mình điền vào đây, chứ nếu xe mình tự gây tai nạn thì không có vụ yêu cầu bồi thường. Chỉ nhập sẵn 3 thông tin là Họ tên lái xe, số điện thoại và địa chỉ thôi.

**Comment by trungdq88** [comment]
> Biển số xe gây tai nạn & trọng tải/số chỗ ngồi là của xe gây tai nạn

Cái này có chắc chắn không anh?

> nếu xe mình tự gây tai nạn thì không có vụ yêu cầu bồi thường

Cái này nữa, có chắn chắn như vậy không anh?

**Comment by hydrangea8604** [comment]
A xin lỗi, chỗ này đọc sai & hiểu nhầm nên nói bậy. Đoạn phát biểu trên là không đúng đâu.

**Comment by phucnguyen60749** [comment]
https://luatminhkhue.vn/bao-hiem/nghi-dinh-103-2008-nd-cp-cua-chinh-phu-ve-bao-hiem-bat-buoc-trach-nhiem-dan-su-chu-xe-co-gioi.aspx

**Comment by trungdq88** [comment]
Vậy anh kiểm tra lại chỗ này bên issue #359 luôn nha.

**Comment by phucnguyen60749** [comment]
ok vay @trungdq88 check lại dum nhe!

**Comment by trungdq88** [comment]
:+1: Done.
