### ISSUE TITLE
<Customer> create new contract: lỗi hiển thị, font... etc

### ISSUE THREAD

**Issue by hydrangea8604** [trungdq88/insurance-card#358]
Trang create
- [x] Bỏ bớt br dưới nút Thêm hợp đồng

Trang review
![image](https://cloud.githubusercontent.com/assets/12366868/8766015/a8763e2c-2e52-11e5-8fbb-9c9bb1c523f8.png)
- [x] Sửa chữ lại thành như sau:
![image](https://cloud.githubusercontent.com/assets/12366868/8766034/3a26161c-2e53-11e5-9bb7-db3633ad3206.png)
![image](https://cloud.githubusercontent.com/assets/12366868/8766005/5adeef10-2e52-11e5-8cee-82e3591d9700.png)
- [x] Hiển thị sai format
- [x] Thời điểm hết hiệu lực bị lệch

**Comment by trungdq88** [comment]
:+1:

**Comment by phucnguyen60749** [comment]
@hydrangea8604  xem lai dum nhe

**Comment by hydrangea8604** [comment]
- [ ] Lỗi font
![image](https://cloud.githubusercontent.com/assets/12366868/8766672/f9b9b796-2e6b-11e5-8dc8-9223b5a50c61.png)

**Comment by trungdq88** [comment]
> Lỗi font

Cái này ở trang nào vậy anh?

**Comment by trungdq88** [comment]
@hydrangea8604 anh check lại cấu hình tomcat, em không tái tạo được lỗi này.
http://stackoverflow.com/a/138950/1420186

**Comment by hydrangea8604** [comment]
Là do thiếu cấu hình tomcat, xin lỗi. Có thể close
