### ISSUE TITLE
<Staff> Create compensation: tự động điền mặc định các thông tin của hợp đồng hiện tại.

### ISSUE THREAD

**Issue by hydrangea8604** [trungdq88/insurance-card#359]

**Comment by hydrangea8604** [comment]
@minhtridn2001 Tự động điền được 3 field Họ tên lái xe, điện thoại, địa chỉ. Các field còn lại đều là không xác định được nên không điền giá trị

**Comment by hydrangea8604** [comment]
Update thêm 2 field biển số và trọng tải/số chỗ ngồi

**Comment by hydrangea8604** [comment]
Ok, có thể review

**Comment by minhtridn2001** [comment]
Phần tạo bồi thường từ Trang bồi thường thì OK rồi Kha. Nhưng tạo bồi thường từ trang Hợp đồng thì ko tự động điền luôn :D

**Comment by hydrangea8604** [comment]
Ko biết làm sao xử lý tự động điền khi nhấn từ trang chi tiết hợp đồng nữa =.=!

**Comment by minhtridn2001** [comment]
Trong hàm getCreate(), Kha get contract detail bằng contractCode truyền qua param, rồi set mấy thuộc tính cần tự điền vào Dto và truyền vào request attribute "submitted" ak.

**Comment by hydrangea8604** [comment]
Cách đó thì nói làm gì, làm sao tự động load AJAX với keyword là mã hợp đồng truyền từ param mới hay.

**Comment by minhtridn2001** [comment]
Thế thì hỏi Trung ấy :D klq chứ xem hình thổ dân chưa :3

**Comment by hydrangea8604** [comment]
Ok, implement cách cùi bắp :cry:

**Comment by trungdq88** [comment]
> Ok, implement cách cùi bắp :cry:

Cách anh làm là đúng rồi đó anh.

**Comment by minhtridn2001** [comment]
Đã review :+1:
