### ISSUE TITLE
<Staff> Implement validate server-side: Một số config staff và business rule

### ISSUE THREAD

**Issue by hydrangea8604** [trungdq88/insurance-card#360]
- [x] Renew contract: af2b1d6
  - [x] Hợp đồng trạng thái Request cancel & Cancelled không được renew
  - [x] Hợp đồng còn thời hạn hơn 2 tháng không được renew.
- [x] Cancel: hợp đồng cancelled không được cancel.
- [x] Create payment: hợp đồng cancelled không được thêm thông tin thanh toán.
- [ ] Compensation:
  - [x] 1 tháng sau khi cancel, hợp đồng không được tạo mới
  - [ ] Thời hạn xử lý bồi thường tối đa là 30 ngày kể từ ngày nhận được yêu cầu. (Staff)
- [x] Accident:  1 tháng sau khi cancel, hợp đồng không được tạo mới
- [x] Punishment:  1 tháng sau khi cancel, hợp đồng không được tạo mới

Customer:

- [x] Trong CustomerCreateContractDto không thấy code validate server startDateMin, Max, contract term...

**Comment by hydrangea8604** [comment]
@minhtridn2001 Compensation còn 1 cái chưa tick, nó là optional, nghĩ lại thấy không cần thiết nên không implement

**Comment by trungdq88** [comment]
> Thời hạn xử lý bồi thường tối đa là 30 ngày kể từ ngày nhận được yêu cầu. (Staff)

Cái này là mới phát sinh hả anh? Em không nhớ là có rule này nhỉ?

**Comment by hydrangea8604** [comment]
Nó từ issue #355 tách ra đó. Hôm nọ ngoài quán cafe đọc Luật tìm thấy, là optional

**Comment by trungdq88** [comment]
:+1:

**Comment by minhtridn2001** [comment]
@hydrangea8604  Review OK. Nhưng câu thông báo khi gia hạn hợp đồng Cancel or Request Cancel: "Không thể gia hạn hợp đồng có trạng thái hiện tại" gây phân vân quá. Nên sửa lại :"Không thể gia hạn hợp đồng đã hủy hoặc đang yêu cầu hủy"

**Comment by hydrangea8604** [comment]
Ok, đã sửa, chắc là close được rồi đó @minhtridn2001

**Comment by minhtridn2001** [comment]
Ko biết tự close nữa :dancers:
