### ISSUE TITLE
<Staff, Customer> Request new card: Thiếu link, thừa chữ

### ISSUE THREAD

**Issue by hydrangea8604** [trungdq88/insurance-card#361]
- [ ] Trang request new card customer thiếu link:
![image](https://cloud.githubusercontent.com/assets/12366868/8770028/ff702158-2ed3-11e5-8981-68e2b72f648f.png)

- [ ] Trang staff: số 341
![image](https://cloud.githubusercontent.com/assets/12366868/8770035/12afacca-2ed4-11e5-808f-f094003d3651.png)

**Comment by trungdq88** [comment]
> Trang request new card customer thiếu link:

Trang customer không gắn link chỗ này. Lý do là có thể thẻ đó đã bị deactive, customer không thể xem được những thẻ đã deactive.

**Comment by trungdq88** [comment]
Cái số 341 là sai sót của em. Đã sửa.
