### ISSUE TITLE
Chuẩn bị sẵn dummy data: ít nhất 40 customer trong hệ thống.

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#362]

**Comment by minhtridn2001** [comment]
Mình insert thêm cho đủ 40 customer trong dummy database rồi(Mã customer tự phát sinh theo thứ tự) . Bây giờ chia ra mỗi người thêm các bảng khác cho 10 customer nhé. Chia theo thứ tự:
- Trung :customer 1-10
- Phuc: 11- 20
- Tri: 21-30
- Kha: 31- 40.
Mọi người thấy sao? @trungdq88  @phucnguyen60749  @hydrangea8604

**Comment by trungdq88** [comment]
:+1: Mật khẩu của các customer là gì vậy anh?

**Comment by minhtridn2001** [comment]
Mật khẩu hơn 1/2 a để default ak còn lại là 123123. Mình lấy staff thêm thông tin cho lẹ :D

**Comment by trungdq88** [comment]
Ok.

**Comment by trungdq88** [comment]
Đã xong data từ customer 1 - 10.

**Comment by hydrangea8604** [comment]
@phucnguyen60749 Làm trước nha

**Comment by phucnguyen60749** [comment]
@hydrangea8604 tu 20-30 nhe

**Comment by hydrangea8604** [comment]
Ở trên ghi rõ 21 - 30 là của Trí mà =.=!

**Comment by minhtridn2001** [comment]
@phucnguyen60749 Phúc kiểm tra lại dummy data đi Phúc. T chạy của P lên thì bị exception. Kiểm tra thì thấy P ko thêm cái card nào hết, vậy sao hợp đồng thành Ready được hay vậy. Mà Phục làm customer từ 11-20 nha.

**Comment by phucnguyen60749** [comment]
@minhtridn2001  ben p chay binh thuong ma! tri drop database hien tai cua tri! xong roi tao moi 1 cai mic_data_20150724 --> roi chay sql cua P!

**Comment by trungdq88** [comment]
Anh @phucnguyen60749 commit làm ơn gắn số vào giúp em.

**Comment by phucnguyen60749** [comment]
a wen sr! tai cai do a add vo bang github!

**Comment by trungdq88** [comment]
Anh làm đúng quy trình: drop db cũ, import file trungdq.sql trong thư mục "default data", rồi chạy app, thêm dữ liệu, sau đó export toàn bộ ra file sql mới để anh Trí làm tiếp.

**Comment by trungdq88** [comment]
Em confirm file `phucnh.sql` chạy bị exception lúc vào trang chi tiết hợp đồng (VD: http://localhost:8080/staff/contract?action=detail&code=HD000K).

Anh Phúc **thêm data vào bằng app chứ KHÔNG GÕ TRỰC TIẾP TRONG FILE SQL** nha.

**Comment by trungdq88** [comment]
File `phucnh.sql` bị lỗi, anh @phucnguyen60749 sửa lại nha.

**Comment by phucnguyen60749** [comment]
@minhtridn2001 xong roi tri

**Comment by minhtridn2001** [comment]
Kha làm tiếp nhé

**Comment by hydrangea8604** [comment]
Có cần làm dummy mấy cái request cancel, request new card... không nhỉ?

**Comment by trungdq88** [comment]
Đã xong.
