### ISSUE TITLE
Checker app: send punishment. set smaller image size for better performance (upload / show image)

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#364]

**Comment by trungdq88** [comment]
- Cần xem xét lại, nếu kích thước hình bị giảm thì sẽ khó nhìn chữ trong hình. Mục tiêu của chức năng này là chụp hình biên bản.
- Xử lý: giảm size hình đến kích thước vừa đủ.
- Với cùng 1 size hình, có chắc chắn là tất cả điện thoại đều có thể đọc được chữ?
- Thêm thông tin vi phạm nằm trong core flow. Nếu upload hình quá lâu sẽ ảnh hưởng đến quá trình demo.

**Comment by trungdq88** [comment]
- Kích thước hình: chiều rộng luôn là 1000px.
- Thời gian upload trung bình: 1 - 3 giây.

Anh @phucnguyen60749 review nhé.
Link tải app mới: https://www.facebook.com/groups/insurancecard/888286541206954/

**Comment by phucnguyen60749** [comment]
Test ok với cỡ ảnh (640x480)
