### ISSUE TITLE
<Admin> Stop contract type: There are 123 contracts is using this contract type. Do you really want to stop this contract type?

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#368]

**Comment by minhtridn2001** [comment]
Em review nhé :tada:

**Comment by trungdq88** [comment]
Anh kiểm tra lại nhé:

- [ ] Trang /admin/contract bây giờ chỉ hiện các contract type có hợp đồng. (Sửa lại: phải hiện hết)
- [ ] Nhấn nút ngưng hoạt động nhưng trạng thái hợp đồng vẫn không đổi.

**Comment by minhtridn2001** [comment]
@trungdq88 Nhấn nút ngưng hoạt động nhưng trạng thái hợp đồng vẫn không đổi => Vẫn đổi bt mà em ? Nó đổi thành Ngưng hoạt động mà :|

**Comment by minhtridn2001** [comment]
Còn lỗi chỉ hiện contract type có hợp đồng là do a ko để ý :D thanks em nhé

**Comment by trungdq88** [comment]
> @trungdq88 Nhấn nút ngưng hoạt động nhưng trạng thái hợp đồng vẫn không đổi => Vẫn đổi bt mà em ? Nó đổi thành Ngưng hoạt động mà :|

Vậy anh sửa lỗi kia đi, xong thì assign cho em. Em sẽ drop db cũ để test lại lần nữa.

**Comment by minhtridn2001** [comment]
@trungdq88 Ah mà mình tính số hợp đồng của contract type đó là tất cả hợp đồng hay là chỉ hợp đồng active thôi em.

**Comment by trungdq88** [comment]
Tất cả luôn đi anh. Cho đơn giản.

**Comment by minhtridn2001** [comment]
A đã sửa hiện hết loại hợp đồng lên rồi. Còn lỗi bên dưới a ko tạo ra được. E test lại dùm a nha

**Comment by trungdq88** [comment]
Cái phần deactive/active bên em nó vẫn lỗi. Nó bị giống cái bug business rule mà cứ F5 là nó đổi data vậy. Chắc cái hibernate trên máy của em có vấn đề.
Anh @hydrangea8604 giúp em review lại issue này được không?

**Comment by hydrangea8604** [comment]
:white_check_mark: Nút ngưng/tái đã hoạt động, đã review trong database, home & staff/customer create contract
