### ISSUE TITLE
Add message "Welcome customer" or "Welcome staff" to know what page belongs to which user.

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#369]
Làm sao để hội đồng nhìn vào là biết đây là trang staff hoặc customer là được.

**Comment by phucnguyen60749** [comment]
review please
- bên customer thì phần header màu xanh sáng hơn!

**Comment by trungdq88** [comment]
Đã thêm hình để dễ phân biệt hơn. Canh lại lề, đưa css vào file style.css.
Close.
