### ISSUE TITLE
Implement branch extend

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#371]
**Document**
- [x] New Conceptual Diagram
- [x] New ERD
- [x] New Class Diagram (with new attribute - add class dictionary)
- [x] New Physical Diagram (with new attribute - add attribute dictionary)
- [x] Add new section to algorithm describes scalability #354

**Database**
- [x] New database script

**Code**
- [x] New entity (web app, mobile apps)
- [x] Migrate code related to CardInstance

**Comment by trungdq88** [comment]
Bắt đầu merge qua master.

**Comment by trungdq88** [comment]
Đã merge vào master.

**Comment by trungdq88** [comment]
Anh @minhtridn2001 giúp em phần class diagram nhé.

**Comment by minhtridn2001** [comment]
Anh add rồi nha. Trung review lại đi.

**Comment by trungdq88** [comment]
- [ ] Anh thêm các note từ ERD vào class diagram luôn nhé.
- [ ] Chỗ khoanh đỏ bị sai, phải là 0..1 và là aggregation mới đúng
<img width="701" alt="screenshot 2015-07-23 14 19 51" src="https://cloud.githubusercontent.com/assets/4214509/8845108/fe3f0622-3145-11e5-99d4-bfec10962ea6.png">

**Comment by minhtridn2001** [comment]
Cái lost reported in a phải là 1 chứ em.

**Comment by minhtridn2001** [comment]
New request nào cũng phải có oldCardInstanceId mà

**Comment by trungdq88** [comment]
À đúng rồi. Xin lỗi em nhìn nhầm.
Vậy anh thêm các note vào là đủ nha.

**Comment by minhtridn2001** [comment]
Ok e

**Comment by minhtridn2001** [comment]
Đã thêm notes.

**Comment by trungdq88** [comment]
:checkered_flag: Done.
