### ISSUE TITLE
Thêm business rule: Thời hạn tối đa còn lại của hợp đồng được phép gia hạn

### ISSUE THREAD

**Issue by minhtridn2001** [trungdq88/insurance-card#373]
- [x] Sửa database.
- [x] Sửa Entity.
- [x] Thêm vào ConfigUtils.
- [x] Sửa những chỗ validate fix cứng 2 tháng:
  - [x] Customer renew contract: client & server side validation : #374
  - [x] Staff renew contract: client & server side validation #360
- [x] Sửa lại add, view detail config business rules page

**Comment by hydrangea8604** [comment]
Làm xong hai cái đầu assign lại cho t nha

**Comment by minhtridn2001** [comment]
@hydrangea8604 Xong rồi Kha :baby:

**Comment by hydrangea8604** [comment]
@minhtridn2001 Phần của t xong rồi Trí :cake:

**Comment by minhtridn2001** [comment]
Done. Plz review! :rose:

**Comment by trungdq88** [comment]
:+1: Đã review.
