### ISSUE TITLE
<Customer> Renew contract : Validate client và server số ngày tối đa còn lại của hợp đồng được phép gia hạn

### ISSUE THREAD

**Issue by minhtridn2001** [trungdq88/insurance-card#374]
Validate client và server số ngày tối đa còn lại của hợp đồng được phép gia hạn dựa vào bảng business rules : contractRenewLimit

**Comment by phucnguyen60749** [comment]
@hydrangea8604  review dùm nhé! 
- tui đổi câu thông báo thành! KHÔNG THỂ GIA HẠN HỢP ĐỒNG CÒN GIÁ TRỊ TRÊN "n" NGÀY

**Comment by trungdq88** [comment]
:+1: Đã review (hiện trang business rule chưa có field này nên review bằng cách đổi database)
