### ISSUE TITLE
Xem lại hàm tính ngày kiểm tra hết hạn thanh toán. Và những chỗ tính ngày tháng khác

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#376]
Kiểm tra tất cả các hàm ngày tháng trong Scheduler

**Comment by minhtridn2001** [comment]
Em review lại giúp a nhé :gem:

**Comment by trungdq88** [comment]
Sao thấy edit có 1 chỗ `checkIfContractExceedPaymentDueDate` vậy nhỉ.

**Comment by minhtridn2001** [comment]
@trungdq88  A test lại hết mấy chỗ khác rồi. Có mỗi checkIfContractExceedPaymentDueDate  bị sai do có giờ phút thôi :D

**Comment by trungdq88** [comment]
- [ ] Ngày hết hạn là 25/07, nếu hôm nay là 25/7 thì tình trạng hợp đồng phải là Hết hạn (tức là sẽ bị hết hạn lúc 00:00 ngày 25/07 tức 23:59 ngày 24/07)
<img width="941" alt="screenshot 2015-07-25 20 11 08" src="https://cloud.githubusercontent.com/assets/4214509/8889575/b05ef3ac-3309-11e5-9833-829f4c1a4fd7.png">

**Comment by trungdq88** [comment]
- [ ] Ngày đăng ký hợp đồng là 26/07, tức là sẽ được tính từ 00:00 ngày 26/07. Giới hạn tới 7 ngày sau tức là 26/07 + 7 ngày = 02/08. Hợp đồng phải bị hủy vào lúc 00:00 ngày 02/08, tức 23:59 01/08.
<img width="410" alt="screenshot 2015-07-25 20 23 22" src="https://cloud.githubusercontent.com/assets/4214509/8889604/0404b2e8-330b-11e5-9f61-d6e849ecd978.png">

<img width="942" alt="screenshot 2015-07-25 20 19 14" src="https://cloud.githubusercontent.com/assets/4214509/8889590/722c2f54-330a-11e5-9ab6-4bde24d5e1f1.png">

**Comment by minhtridn2001** [comment]
Anh sửa lại rồi nha Trung ơi

**Comment by trungdq88** [comment]
Done
