### ISSUE TITLE
<Customer> Update use cases specification

### ISSUE THREAD

**Issue by hydrangea8604** [trungdq88/insurance-card#379]
Danh sách các use case cần update:
- [x] Renew contract
- [ ] Cancel contract
- [ ] View payment history
- [ ] View accident history
- [ ] View punishment history
- [x] Request compensation
- [ ] View compensation history

Sửa vào file đã được tách ra và commit sẵn, vì toàn là chữ nên làm kỹ, review lại flow đã mô tả để tìm những chỗ cần sửa.

**Comment by phucnguyen60749** [comment]
WC02
          Change 
                       -  Contract’s expired date is less than 2 months than 60 days .
          Addition
                       -  If contract type of contract is not active the customer will not be able renew contract.
WC07
         Addition
                       -  Contract’s status must not be “Pending”.
                       -  Contract’s status must not be “Canelled”  or “Expired” has  expired date is more than                  30 days with current date.

**Comment by trungdq88** [comment]
Đã review.

**Comment by trungdq88** [comment]
Mà sao chỉ thấy update có 2 use case vậy nhỉ? Các use case còn lại không có thay đổi gì à?

> - [x] Renew contract
> - [ ] Cancel contract
> - [ ] View payment history
> - [ ] View accident history
> - [ ] View punishment history
> - [x] Request compensation
> - [ ] View compensation history

Anh @hydrangea8604 đã liệt kê ra các use case này thì chắc có lý do, anh có thể ghi rõ lý do cần đổi trong các use case này để anh @phucnguyen60749 làm theo không?

**Comment by phucnguyen60749** [comment]
@trungdq88 cái đó Kha liệt kê ra hết! rồi đọc từ trên xuống dưới xem có chổ nào cần chỉnh sữa vs cái rule mới thì update lại!

**Comment by hydrangea8604** [comment]
Đó là liệt kê những use case cần sửa, những cái không cần sửa không hề đề cập tới. Còn sửa chỗ nào thì tự đọc rồi sửa thôi chứ giờ chỉ ra từng cái thì tự làm cho rồi

**Comment by phucnguyen60749** [comment]
@hydrangea8604 thỉ đọc rồi ko thấy cần update nên ko update! ko đọc comment hả!

**Comment by hydrangea8604** [comment]
Ví dụ như Cancel contract, coi lại mấy cái option coi có thay đổi không? Payment history 6 cái field đó là đúng?

**Comment by trungdq88** [comment]
Anh Phúc kiểm tra lại các use case còn lại nhé. Ví dụ em thấy cần sửa các chỗ sau:
- WC03 - <Customer> Cancel contract: Main Success Scenario: system response, Reason to cancel: liệt kê tất cả các reason đang có, hiện tại mới liệt kê có 2 cái (từ rất lâu rồi)
- WC04 các cột trong payment history không đúng với trong giao diện.

Anh check lại nhé, em chưa check tất cả, nhưng anh Kha đã liệt kê thì chắc chắn là có thay đổi.

**Comment by phucnguyen60749** [comment]
- WC03 - Cancel contract : thêm đầy đù các reason hiện tại
- WC04: Main Success Scenario-> System Response : sữa đúng theo các cột payment history
- WC02: Renew contract: Main Success Scenario-> System Response :add Type of contract: text
- WC05 View accident history-> Main Success Scenario-> System Response: sữa lại đúng theo các cột trong accident list
- WC06 View punishment history-> Main Success Scenario-> System Response: sữa lại đúng theo các cột trong punishment list
- WC08 View compensation history --> Main Success Scenario-> System Response: sữa lại đúng theo các cột trong compensation list

**Comment by trungdq88** [comment]
Done.
