### ISSUE TITLE
Khi gia hạn, tạo mới, lấy tên của người dùng đang đăng nhập vào hệ thống điền vào receiver trong payment.

### ISSUE THREAD

**Issue by hydrangea8604** [trungdq88/insurance-card#38]

**Comment by trungdq88** [comment]
Đã implement phần đăng nhập. Đã có thể bắt đầu implement chức năng này.

**Comment by trungdq88** [comment]
Trong Database, bảng mic_contract có một field là staff_code, lưu code của người staff tạo contract. Mặc dù trên giao diện không hiển thị nhưng vẫn nên implement. Sẽ thảo luận về chỗ để hiển thị thông tin này.

**Comment by hydrangea8604** [comment]
Lúc tạo hợp đồng thì lưu code lần đầu tiên, vậy lúc gia hạn hay hủy hợp đồng thì có cập nhật lại tên không Trung?

**Comment by trungdq88** [comment]
Lúc gia hạn thì lưu staff vào payment rồi mà. Còn lúc huỷ thì business của mình là không có lưu người staff huỷ.

**Comment by trungdq88** [comment]
Có vấn đề: Field receiver trong bảng Payment không phải lưu tên staff mà là lưu mã số staff và phải có khoá ngoại qua bảng Staff. Xem #167.
Issue này sẽ fix sau #167

**Comment by trungdq88** [comment]
Đã review :white_check_mark:
