### ISSUE TITLE
<Others> Update use cases specification

### ISSUE THREAD

**Issue by hydrangea8604** [trungdq88/insurance-card#380]
Danh sách các use case cần update
- [x] <Guest> Create new contract request
- [x] <Customer> New card request
- [x] <Staff> Update contract type information
- [x] < Admin> Add staff (input staff code)
- [x] <System> Notify schedule
- [x] <Police> Verify card information
- [x] <Police> Add punishment information
- [x] <Staff> Search / filter contract
- [x] <Staff> View contract information
- [x] <Staff> Print information to NFC card

Bị nhiều nhất là mô tả business rule 1 năm, 15 ngày... Mà mình phát sinh cái config business rules nên giờ ghi vậy là không đúng nữa.

PS: Giao diện trang Tạo nhân viên đang để header là "Thiết lập cấu hình"

**Comment by minhtridn2001** [comment]
Em review giúp a nha Trung :love_letter:

**Comment by trungdq88** [comment]
- [ ] WC09 - <Customer> New card request - Preconditions: ghi rõ các status nào của contract thì được tạo new card request.
- [ ] WY01 - Sửa lại preconditions: System time is at 00:00 AM.
- [ ] PS01 - Sửa lại business rule: chỉ search theo contract code và customer name
- [ ] PS03 - Kiểm tra lại preconditions: các status của contract có thể in thẻ.

**Comment by minhtridn2001** [comment]
PS03 - Kiểm tra lại preconditions: các status của contract có thể in thẻ.

A nghĩ vì contract nào cũng gọi được hàm này nhưng có in được hay không thôi. Cho nên anh đưa nó vào Alternative 1 đó em. Em xem có được ko nha.

**Comment by trungdq88** [comment]
> PS03 - Kiểm tra lại preconditions: các status của contract có thể in thẻ.
> A nghĩ vì contract nào cũng gọi được hàm này nhưng có in được hay không thôi. Cho nên anh đưa nó vào Alternative 1 đó em. Em xem có được ko nha.

Ok, hợp lý :+1: .
Đã review các use case còn lại.
