### ISSUE TITLE
Hợp đồng chưa thanh toán thì không hiện thời gian đến ngày hết hạn

### ISSUE THREAD

**Issue by minhtridn2001** [trungdq88/insurance-card#381]
Kha ơi lần trước thầy nói hợp đồng chưa thanh toán thì không hiện thời gian đến ngày hết hạn, gây hiểu nhầm.
![image](https://cloud.githubusercontent.com/assets/12363317/8879695/37babe6a-325d-11e5-9dab-3c4fcc750e47.png)

**Comment by hydrangea8604** [comment]
- Pending, chưa thanh toán: hiển thị "Không có"
- Pending, đã thanh toán: hiển thị số ngày
@minhtridn2001 papoy :tomato:

**Comment by minhtridn2001** [comment]
Kha cho ẩn luôn dòng Thời gian đến ngày hết hạn luôn đi. Tự nhiên cho nó hiện ra rồi ghi không có :D @trungdq88  thấy sao Trung?

**Comment by hydrangea8604** [comment]
Ok, nếu chưa thanh toán thì ẩn luôn

**Comment by minhtridn2001** [comment]
Đã review :+1:
