### ISSUE TITLE
Tính ngày quá hạn bị sai

### ISSUE THREAD

**Issue by minhtridn2001** [trungdq88/insurance-card#382]
Tính ngày quá hạn bị sai. Và hợp đồng chưa thanh toán thì ko nên hiện ngày quá hạn như thế, dễ gây hiểu nhầm.
![image](https://cloud.githubusercontent.com/assets/12363317/8879797/1cdff0f0-325e-11e5-8b5f-d58b26d03673.png)

**Comment by phucnguyen60749** [comment]
ok! @minhtridn2001  cho hoi xiu!
-  truong hop nay tạo hợp đồng mới rồi đồi ngày hệ thống lên 3 ngày nữa hay sao!

**Comment by minhtridn2001** [comment]
Bị lệch 1 ngày đó Phúc. Như trong hình tạo này 10/8, ngày hệ thống là 12/8 thì quá hạn 3 ngày.

**Comment by minhtridn2001** [comment]
Nhưng mà hợp đồng chưa thanh toán P để tình trạng hợp đồng khác đi, đừng có để quá hạn x ngày. Thay bằng "chưa thanh toán" chẳng hạn.

**Comment by trungdq88** [comment]
@phucnguyen60749 anh lưu ý là ở đây có 2 bug đó nha:
- [ ] Tính ngày bị sai
- [ ] Không hiển thị "Quá hạn xxx ngày" khi trạng thái Pending hoặc Cancelled

**Comment by phucnguyen60749** [comment]
khi hop dong moi tao la pending thi khong  hien so ngay. nhung khi pending nhung customer ko thanh toan thi phai hien so ngay chu vi qua x ngay neu ko thanh toan thi hop dong se huy. vay chi ko hien so ngay khi moi tao hop dong nhung ko thanh toan. ok nha

**Comment by trungdq88** [comment]
> khi hop dong moi tao la pending thi khong hien so ngay. nhung khi pending nhung customer ko thanh toan thi phai hien so ngay chu vi qua x ngay neu ko thanh toan thi hop dong se huy. vay chi ko hien so ngay khi moi tao hop dong nhung ko thanh toan. ok nha

Ok, trường hợp đã thanh toán nhưng vẫn Pending thì vẫn hiện ngày.

**Comment by trungdq88** [comment]
Dành cho người review: check lại trường hợp này luôn nhé (15 ngày mới đúng, trong hình ghi là 14 ngày)

<img width="937" alt="screenshot 2015-07-25 20 08 26" src="https://cloud.githubusercontent.com/assets/4214509/8889556/f7aea05a-3308-11e5-8efa-d24e9bf24186.png">

**Comment by trungdq88** [comment]
Tình trạng "Không xác định" là sao nhỉ?!

<img width="941" alt="screenshot 2015-07-25 20 11 08" src="https://cloud.githubusercontent.com/assets/4214509/8889562/5adc2274-3309-11e5-85e9-5fd5005eff60.png">

**Comment by phucnguyen60749** [comment]
@minhtridn2001  check lai dum nha! 
- mới tạo chưa thanh toán --> peding : không hiện ngày 
- nếu chưa thanh toán vẫn để --> báo ngày!

**Comment by minhtridn2001** [comment]
Ko khác biệt gì hết

**Comment by minhtridn2001** [comment]
P lại đọc review của Trung đi

**Comment by phucnguyen60749** [comment]
@trungdq88 check lai dum nhe! sao tren may minh test ko ra loi! :(

**Comment by minhtridn2001** [comment]
```
         var oneDay = 24 * 60 * 60 * 1000;
         var timeNow = new Date();
         var expiredDate = new Date(date);
         return Math.round((expiredDate.getTime() - timeNow.getTime()) / (oneDay) + 1 );
```
Trường hợp timeNow = đúng lúc 00:00:00 thì kết quả sẽ bị lệch 1 ngày. Mà sau này Scheduler dự định sẽ cho chạy lúc 00:00:00 => Phúc nên lấy timeNow vào ngày hôm đó lúc 00:00:00 giờ luôn, khỏi phải +1 nữa.
Còn trường hợp chưa thanh toán thì vẫn hiện : Quá hạn xx ngày thì Trung confirm lại giúp anh nha @trungdq88 
![image](https://cloud.githubusercontent.com/assets/12363317/8893901/457def4c-33cd-11e5-9c77-87542356d7ef.png)

**Comment by phucnguyen60749** [comment]
@minhtridn2001 da reset time now! not wrong again

**Comment by trungdq88** [comment]
> Còn trường hợp chưa thanh toán thì vẫn hiện : Quá hạn xx ngày thì Trung confirm lại giúp anh nha @trungdq88 

@minhtridn2001 @phucnguyen60749 

- Pending chưa thanh toán: KHÔNG hiện ngày
- Pending đã thanh toán: hiện ngày.

**Comment by minhtridn2001** [comment]
> - Pending chưa thanh toán: KHÔNG hiện ngày
- Pending đã thanh toán: hiện ngày.

Vậy Phúc sửa lại nha.

**Comment by phucnguyen60749** [comment]
@minhtridn2001 xem lai dum nhe

**Comment by minhtridn2001** [comment]
Hợp đồng chưa thanh toán, mà ngày startDate sau ngày current thị nó hiện : Còn hạn : xx ngày => Sai
![image](https://cloud.githubusercontent.com/assets/12363317/8894685/2a3f1388-33ea-11e5-8bcb-d0e8e6979ec5.png)

**Comment by phucnguyen60749** [comment]
@minhtridn2001 tri ctrl+F5 dum P! hoac pull lại thử! P đã test tr hop nay ko bi!

**Comment by minhtridn2001** [comment]
OK sr Phúc. T có pull mà chắc do cache hay gì đó. Đã review !
