### ISSUE TITLE
<Staff> Contract detail: thời điểm có hiệu lực/hết hiệu lực: bỏ thời gian.

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#383]
Bỏ chỗ "lúc 12:00:00 AM" đi

<img width="470" alt="screenshot 2015-07-26 14 09 51" src="https://cloud.githubusercontent.com/assets/4214509/8892913/14f6ae36-33a0-11e5-9087-0bbfb550d31d.png">

**Comment by hydrangea8604** [comment]
@minhtridn2001 Nhìn nó hơi trống vắng nhỉ :space_invader: Tách jsp ra include vào nhiều chỗ nên chỉ cần sửa 1 chỗ là được, review lại dùm nha.

**Comment by trungdq88** [comment]
Nếu sợ trống vắng anh có thể đổi lại thành: "Ngày 26 tháng 7 năm 2015"

**Comment by hydrangea8604** [comment]
Ok, đã sửa lại thành ngày xx tháng xx năm xxxx, cảm ơn @trungdq88 đại đế :crown:

**Comment by minhtridn2001** [comment]
Đã hiện ngày xx tháng xx năm xxxx :+1:
