### ISSUE TITLE
Format currency at staff/new card request/payment. Use VNĐ unit.

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#387]
#### Staff: @hydrangea8604
- [x] Chi tiết thông tin thanh toán
- [x] Gia hạn hợp đồng (Phí gia hạn, Phí thẻ mới, Phí vận chuyển, Tổng chi phí)
- [x] Chi tiết hợp đồng
  - [x] Phí bảo hiểm
  - [x] Thông tin thanh toán
- [x] Tạo hợp đồng
- [x] Kiểm tra thông tin và hoàn tất hợp đồng

#### Guest: @minhtridn2001 
- [x] Sửa _VND_ thành **VNĐ** nha Trí
- [x] Bỏ dấu ngoặc đơn với VND ở trang thanh toán
- [x] Thanh toán new card request

#### Admin:
- [x] Trang loại hợp đồng

#### Customer: @phucnguyen60749 
- [x] Lịch sử giao dịch
- [x] Chi tiết thông tin thanh toán
- [x] Tooltip thanh toán hợp đồng Pending.
- [x] Gia hạn hợp đồng

Thống nhất hiển thị theo ví dụ: __86.000 VNĐ__. Không dùng kiểu _Phí bảo hiểm (VNĐ) 86.000_

**Comment by hydrangea8604** [comment]
@minhtridn2001 review dùm luôn nha

**Comment by minhtridn2001** [comment]
Đã review phần Kha OK :+1:

**Comment by trungdq88** [comment]
Chỗ này trên máy của anh hiện như thế nào vậy anh @hydrangea8604 

<img width="348" alt="screenshot 2015-07-30 12 55 09" src="https://cloud.githubusercontent.com/assets/4214509/8976642/3c88991a-36ba-11e5-8cae-f566b631b73b.png">

**Comment by hydrangea8604** [comment]
Hiển thị như thế này, sao nó lại hiển thị như bên Trung nhỉ, Mac hay XP thế?
![image](https://cloud.githubusercontent.com/assets/12366868/8976807/5e4ee66a-36bc-11e5-930c-5ba803e5cdb8.png)

**Comment by minhtridn2001** [comment]
Ah phải set location là vn nữa thì nó mới hiện đằng sau :D

**Comment by minhtridn2001** [comment]
Browser t location là VN nên bị sót trường hợp này. Kha thêm vào giúp t nha

**Comment by hydrangea8604** [comment]
Ừa, sửa từ chiều rồi

**Comment by phucnguyen60749** [comment]
@hydrangea8604  review dum lun nha!

**Comment by hydrangea8604** [comment]
Sửa lại dấu phẩy ở trang home là ok

**Comment by minhtridn2001** [comment]
OK Thanks Kha nhé  chẳng hiểu sao còn sót 1 chỗ :D

**Comment by hydrangea8604** [comment]
:heavy_check_mark: Done
