### ISSUE TITLE
Customer/contract detail: tình trạng hợp đồng: chuyển code tính ngày lên server.

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#389]
Nếu để ở client, lúc đổi ngày thì chrome bị delay => không tốt.

- [x] Tình trạng hợp đồng: chuyển code tính ngày lên server.
- [x] Chuyển code phần ẩn/hiện nút "Gia hạn", "Hủy hợp đồng" lên server.

**LƯU Ý**: kiểm tra lại tất cả các trường hợp của đoạn code này. Hạn chế phát sinh lỗi khi chuyển từ client => server.

**Comment by phucnguyen60749** [comment]
@trungdq88 ơi  Chuyển code phần ẩn/hiện nút "Gia hạn", "Hủy hợp đồng" lên server! why??

**Comment by phucnguyen60749** [comment]
@trungdq88  review dum nhe!

**Comment by trungdq88** [comment]
@phucnguyen60749 của anh là anh Kha review chứ?

**Comment by phucnguyen60749** [comment]
a nham ! :)

**Comment by hydrangea8604** [comment]
Ok, đã review

**Comment by trungdq88** [comment]
Trường hơp này:
- Hợp đồng hết hạn ngày 29/07/2014, trạng thái "Expired".
- Trong admin/config/Thời hạn tối đa còn lại để gia hạn hợp đồng = 60 ngày.

Không thấy xuất hiện nút "Gia hạn" (phải hiện nút gia hạn mới đúng).

Do đoạn code này bị sai:
<img width="513" alt="screenshot 2015-07-29 19 57 34" src="https://cloud.githubusercontent.com/assets/4214509/8957958/319bbec6-362c-11e5-9084-126f89f9ac45.png">

Anh @phucnguyen60749 sửa lại, anh @hydrangea8604 review lại nhé.

**Comment by trungdq88** [comment]
Code tính số ngày bị sai:
<img width="705" alt="screenshot 2015-07-29 20 01 24" src="https://cloud.githubusercontent.com/assets/4214509/8958055/bcd94a4e-362c-11e5-8825-1ef3bcbd99a1.png">

Em biết ngay chỗ này chuyển lên server kiểu gì cũng phát sinh lỗi, ra ghi rất rõ là check cẩn thận giùm rồi

> LƯU Ý: kiểm tra lại tất cả các trường hợp của đoạn code này. Hạn chế phát sinh lỗi khi chuyển từ client => server.

Anh @phucnguyen60749 sửa lại, anh @hydrangea8604 review lại nhé.

**Comment by trungdq88** [comment]
Trường hợp chưa thanh toán thì cho hiện "Chưa thanh toán" ở khung "Tình trạng hợp đồng" (hiện tại đang bị trống).
<img width="927" alt="screenshot 2015-07-29 20 08 00" src="https://cloud.githubusercontent.com/assets/4214509/8958288/234ef214-362e-11e5-9f73-c31c4b7c67ec.png">

**Comment by phucnguyen60749** [comment]
@hydrangea8604 đã fix các tr hợp của Trung review! ok rồi! review please

**Comment by hydrangea8604** [comment]
Ok, đã review những lỗi @trungdq88 chỉ ra, xin lỗi vì review sót
