### ISSUE TITLE
Staff/contract detail: tình trạng hợp đồng: chuyển code tính ngày lên server.

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#391]
Chuyển luôn phần ẩn hiện nút "Gia hạn", "Hủy hợp đồng" lên server.

**Comment by hydrangea8604** [comment]
@minhtridn2001 Review dùm nha, tks

**Comment by minhtridn2001** [comment]
Ô kê con gà đen :chicken:

**Comment by trungdq88** [comment]
@minhtridn2001 anh check các trường hợp tương tự như bên này chưa anh? #389

**Comment by minhtridn2001** [comment]
Anh đã kiểm tra số ngày được phép gia hạn đúng thì mới hiện nút Gia hạn rồi @trungdq88
