### ISSUE TITLE
Change time to 2016 > customer/create compensation error javascript.

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#392]

**Comment by trungdq88** [comment]
Không tái tạo được lỗi. Cần xem xét lại.

**Comment by trungdq88** [comment]
Anh @minhtridn2001 tái tạo lỗi này giúp em xem có được không nha. Máy ảo XP của em không tái tạo được.

**Comment by minhtridn2001** [comment]
Anh vẫn bị lỗi giống hôm demo trên máy của Kha nè Trung
![image](https://cloud.githubusercontent.com/assets/12363317/8959109/2b1430ae-3633-11e5-8114-4c0059b7ea7c.png)

**Comment by minhtridn2001** [comment]
@phucnguyen60749 tái tạo được lỗi ko?

**Comment by trungdq88** [comment]
Vậy anh chụp hình rồi assign cho anh Phúc để fix nha.

**Comment by phucnguyen60749** [comment]
close cái này! lúc demo gửi compensation tr rồi đổi ngày!
