### ISSUE TITLE
Phí hợp đồng lúc đăng ký / gia hạn: làm tròn thành 1000 đồng.

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#393]

**Comment by hydrangea8604** [comment]
@minhtridn2001 Review dùm nhé

**Comment by minhtridn2001** [comment]
Làm tròn thì OK rồi mà phí Kha tính theo ngày nên lúc chia ra nó lẻ quá. Cho nên lúc làm tròn thì nó sẽ tăng thêm 1000. Phí 12 tháng là 86000. Đổi thời gian mặc định là 24 tháng thì phí thành 173000 :thought_balloon: 
![image](https://cloud.githubusercontent.com/assets/12363317/8959884/6b1f11c4-3637-11e5-934a-ee953b2bd8c8.png)

**Comment by hydrangea8604** [comment]
Vậy giờ xử lý như thế nào? Có biện pháp nào chỉ dùm với

**Comment by hydrangea8604** [comment]
Chỉ nghĩ ra một cách là chơi xấu, nếu số ngày là 366 thì set lại thành 365, khi đó sẽ không bị vụ thêm 1000 với năm nhuận :d

**Comment by minhtridn2001** [comment]
Mình tính lại theo tháng được ko? Thay vì chênh lệch ngày thì mình tính theo chênh lệch tháng

**Comment by hydrangea8604** [comment]
@trungdq88 Xem lại chỗ này dùm với Trung, không nghĩ ra cách nào :sob:

**Comment by trungdq88** [comment]
Tính theo cái này nha anh #401 (phải đổi code tính tiền ở client + server)

**Comment by trungdq88** [comment]
Close issue này vì đã làm tròn xong. Issue liên quan: #402.
