### ISSUE TITLE
Phí hợp đồng lúc đăng ký: làm tròn thành 1000 đồng.

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#394]

**Comment by phucnguyen60749** [comment]
cái này fix chung khi làm 
- Customer/hoàn tất thanh toán: phí thanh toán hiển thị sai: #400
- Customer: gia hạn: thời hạn gia hạn mặc định = thời gian hợp đồng mặc định #395
@hydrangea8604  đẹp chai review dùm lun nhá

**Comment by hydrangea8604** [comment]
Làm tròn ở trang tạo hợp đồng của khách hàng, phí hợp đồng làm tròn lên

**Comment by phucnguyen60749** [comment]
đã làm tròn lên

**Comment by trungdq88** [comment]
Phí trả về sai: 86.000 thì hiện 85.000

Code sai:

```java
// fix 1000
        realFee = realFee - (realFee % 1000);
        realFee += 1000;
```

**Comment by phucnguyen60749** [comment]
fix roi trung oi

**Comment by trungdq88** [comment]
Done
