### ISSUE TITLE
Customer: gia hạn: thời hạn gia hạn mặc định = thời gian hợp đồng mặc định

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#395]
- [x] Chỉnh lại hiển thị trên client (trong modal gia hạn)
- [x] Code renew ở server.

![image](https://cloud.githubusercontent.com/assets/12363317/8901784/af88f546-3475-11e5-8062-fa435ff8f7d5.png)

**Comment by phucnguyen60749** [comment]
@hydrangea8604  review please! :)

**Comment by hydrangea8604** [comment]
Thời hạn mặc định của hợp đồng: 24 tháng
![image](https://cloud.githubusercontent.com/assets/12366868/8985792/2754ccbe-3703-11e5-85a0-afc4132b13e5.png)
Tiền thì tính đúng mà ngày gia hạn đến sai

**Comment by phucnguyen60749** [comment]
@hydrangea8604  chổ nào kha gia hạn từ contract đã expired hay no card or ready vậy! sai sao kha

**Comment by hydrangea8604** [comment]
Hợp đồng HD000N expired của KH000T trong default database, không chỉnh sửa gì.

**Comment by phucnguyen60749** [comment]
@hydrangea8604  cái này chung vs cái Ngày hết hạn hiển thị sai (do tính toán tháng bị sai). #403

**Comment by trungdq88** [comment]
Đã review.
