### ISSUE TITLE
<Customer> Tạo hợp đồng, phí hợp đồng tính theo thời hạn mặc định của hợp đồng

### ISSUE THREAD

**Issue by minhtridn2001** [trungdq88/insurance-card#396]
Tạo hợp đồng: phí hợp đồng tính theo thời hạn mặc định của hợp đồng. Như trong hình: Thời hạn mặc định 2 năm mà giá vẫn 86.000 ( giá hàng năm)
![image](https://cloud.githubusercontent.com/assets/12363317/8901705/0e180486-3475-11e5-9bcd-698f011777f4.png)

**Comment by minhtridn2001** [comment]
Trung review giúp a nhé :santa:

**Comment by trungdq88** [comment]
Đã review.
