### ISSUE TITLE
<Public> Register phí hợp đồng tính theo thời hạn mặc định của hợp đồng

### ISSUE THREAD

**Issue by minhtridn2001** [trungdq88/insurance-card#398]
- [x] Home
- [x] Register

**Comment by minhtridn2001** [comment]
Review plz! :love_letter:

**Comment by trungdq88** [comment]
Không hiểu sao không thể thanh toán qua Paypal được. Chắc tại paypal đang có vấn đề.
Chiều review lại.

**Comment by trungdq88** [comment]
Done.
