### ISSUE TITLE
Customer/hoàn tất thanh toán: phí thanh toán hiển thị sai:

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#400]
Phí thanh toán chưa tính dựa theo thời gian mặc định của hợp đồng. 

- [x] Trong hình cài đặt thời gian mặc định là 2 năm nhưng vẫn hiển thị 86.000 VNĐ (1 năm). 
- [x] Ngày kết thúc hiển thị sai: phải hiện ngày sau ngày bắt đầu 2 năm.

<img width="594" alt="screenshot 2015-07-29 20 08 36" src="https://cloud.githubusercontent.com/assets/4214509/8958210/a78e4986-362d-11e5-88eb-c739ed03e778.png">
<img width="507" alt="screenshot 2015-07-29 20 10 31" src="https://cloud.githubusercontent.com/assets/4214509/8958240/e2a1fbee-362d-11e5-8617-8078683308b6.png">

**Comment by phucnguyen60749** [comment]
@trungdq88  check lai dùm nhé ! a chuyển thành modal ko dùng tooltip nua

**Comment by trungdq88** [comment]
Sao cứ đưa em review hoài vậy trời :disappointed:

**Comment by phucnguyen60749** [comment]
à wen nham nham! sr :v:

**Comment by hydrangea8604** [comment]
Thời hạn mặc định của hợp đồng: 31 tháng
![image](https://cloud.githubusercontent.com/assets/12366868/8985335/0f509348-3701-11e5-99d9-6173aff75e2a.png)
- [ ] Ngày 30/2/2018
- [ ] VN**Đ**

**Comment by phucnguyen60749** [comment]
@hydrangea8604  vậy cái này cũng bị bên create contract cusomter! 30/02/2018
- @minhtridn2001  xem lại lun kìa!

**Comment by trungdq88** [comment]
> Ngày 30/2/2018

Cái này có vấn đề gì vậy anh, có phải là việc format "2" vớ "02" không? @hydrangea8604

**Comment by hydrangea8604** [comment]
Thì tháng 2 không có ngày 30, mà ở trong hình trên nó hiển thị 30/02/2018 đó

**Comment by trungdq88** [comment]
À, ok :+1:

**Comment by minhtridn2001** [comment]
@phucnguyen60749  cái thời điểm hết hiệu lực là P thêm mà

**Comment by trungdq88** [comment]
Close issue này vì đã fix xong phí bảo hiểm hiển thị sai.
Issue liên quan: #403
