### ISSUE TITLE
Đổi lại code tính tiền ở staff.

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#402]
Đổi lại theo cách tính tiền ở #401

- [x] Tạo contract (client)
- [ ] Hoàn tất thanh toán hợp đồng Pending  (client + server): phần này không có tính tiền, bởi khi tạo hợp đồng ở trang public đã chọn loại, ngày bắt đầu và set contract fee. Chỉ thực hiện set lại ngày kết thúc và tạo payment mới.
- [x] Gia hạn contract  (client)

**Comment by hydrangea8604** [comment]
@minhtridn2001 Review dùm phần client-side đã làm xong dùm với Trí. Phần server-side đang chờ @trungdq88 có phải là validate số tiền ở mấy cái dto hay không.

**Comment by trungdq88** [comment]
> @trungdq88 có phải là validate số tiền ở mấy cái dto hay không.

Không cần đâu anh. Đáng lý ra thì số tiền phải được tính lại ở server mới đúng. Nhưng mà đồ án thì mình làm tới đây được rồi.

**Comment by minhtridn2001** [comment]
Tính tiền thì OK rồi mà sao bị lỗi này rồi : 
![image](https://cloud.githubusercontent.com/assets/12363317/8985117/daf74f98-36ff-11e5-9335-f5c2ae48cd5e.png)

**Comment by minhtridn2001** [comment]
OK rồi.
