### ISSUE TITLE
Ngày hết hạn hiển thị sai (do tính toán tháng bị sai).

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#403]
Thời hạn mặc định = 31 tháng. Tính ngày tháng thành 30/02 (tháng 2 không có ngày 30, tương tự với các trường hợp tháng có ngày 31 / không có ngày 31)

- [x] Staff / Create contract:

<img width="1074" alt="screenshot 2015-07-30 22 34 24" src="https://cloud.githubusercontent.com/assets/4214509/8987430/408b2b1c-370b-11e5-9a4d-6574414fb8be.png">

- [ ] Customer / create contract:

<img width="875" alt="screenshot 2015-07-30 22 36 25" src="https://cloud.githubusercontent.com/assets/4214509/8987459/755e056c-370b-11e5-878d-1885b385cfae.png">

- [x] Customer / Renew contract

![image](https://cloud.githubusercontent.com/assets/12366868/8985335/0f509348-3701-11e5-99d9-6173aff75e2a.png)

**Comment by trungdq88** [comment]
Anh @hydrangea8604 fix xong thì assign lại cho anh Phúc nhé.

**Comment by hydrangea8604** [comment]
Phần staff nãy Trí sửa hàm addMonth là ok rồi đó Trung, pull code lại thử xem, bên a chạy ok
![image](https://cloud.githubusercontent.com/assets/12366868/8987657/52530c24-370c-11e5-9f99-5d16eab77fe9.png)

**Comment by trungdq88** [comment]
:+1:

**Comment by minhtridn2001** [comment]
Phần staff em thử pull lại xem nha. A có test lại rồi. Còn customer vì ko được chọn ngày hết hạn nên a thấy chỉ gần ghi là Thời điểm hết hiệu lực: xx tháng kể từ ngày cấp. Là được. Vì nếu customer thanh toán trễ thì ngày hết hiệu lực ko đúng với cái ngày ban đầu nữa.
![image](https://cloud.githubusercontent.com/assets/12363317/8987837/312a4f5c-370d-11e5-9943-ff5b7dd2418a.png)

**Comment by trungdq88** [comment]
Em đã confirm phần staff.

> Còn customer vì ko được chọn ngày hết hạn nên a thấy chỉ gần ghi là Thời điểm hết hiệu lực: xx tháng kể từ ngày cấp. Là được. Vì nếu customer thanh toán trễ thì ngày hết hiệu lực ko đúng với cái ngày ban đầu nữa.

Rất hợp lý, nên làm như vậy.

**Comment by phucnguyen60749** [comment]
@hydrangea8604  phần renew với trường hợp pending đã fix xong!

**Comment by hydrangea8604** [comment]
Sửa luôn create contract đi rồi review

**Comment by trungdq88** [comment]
Anh @phucnguyen60749  nhớ phần create contract là làm như vậy nha:

> Còn customer vì ko được chọn ngày hết hạn nên a thấy chỉ gần ghi là Thời điểm hết hiệu lực: xx tháng kể từ ngày cấp. Là được. Vì nếu customer thanh toán trễ thì ngày hết hiệu lực ko đúng với cái ngày ban đầu nữa.

**Comment by phucnguyen60749** [comment]
- chổ này dùng script của trí!  @minhtridn2001 ơi help chổ này nhe!

**Comment by minhtridn2001** [comment]
T sửa rồi đó Phúc. Còn cái nào liên quan đến defaultExpired cũ của P thì P xóa giúp t nha.
```
<input type="text" id="defaultExpired" disabled="disabled" class="handleInput"/>
```

**Comment by phucnguyen60749** [comment]
@hydrangea8604  review lại dùm nhe! 
 - renew, pending
 - create contract (trí fix)

**Comment by trungdq88** [comment]
Đã review.
