### ISSUE TITLE
Nút upload file: ẩn hình review, chỉnh lại title của nút.

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#404]

**Comment by trungdq88** [comment]
Anh Phúc review nhé. Nhớ kiểm tra tất cả các chỗ có nút upload file.

**Comment by phucnguyen60749** [comment]
- chỉ có hai cái nút ở create punishment và create accident bỏ &nbsp;&nbsp; 

![untitled](https://cloud.githubusercontent.com/assets/12363394/9024724/3eb75fae-3909-11e5-8ee4-12ce863fc05e.png)

**Comment by trungdq88** [comment]
Done anh check lại nha

**Comment by phucnguyen60749** [comment]
ok done
