### ISSUE TITLE
Thêm ID thẻ vào chi tiết hợp đồng của mobile app.

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#405]
Bỏ luôn phần tự động bật app lúc áp thẻ.

**Comment by trungdq88** [comment]
Anh Phúc review nha. Link app mới: https://dl.dropboxusercontent.com/u/134202655/checker-app-20150801.apk

**Comment by phucnguyen60749** [comment]
- Đã review Thêm ID thẻ vào chi tiết hợp đồng của mobile app : +1
 - Bỏ luôn phần tự động bật app lúc áp thẻ --> máy a ko có nfc
