### ISSUE TITLE
Không được trùng biển số xe với hợp đồng Expired.

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#413]
- [x] Public register
- [x] Customer create contract
- [x] Staff create contract
- [x] Customer complete payment for Pending contract
- [x] Staff complete payment for Pending contract

**Comment by minhtridn2001** [comment]
Trung review giúp a nhé :heart_eyes:

**Comment by trungdq88** [comment]
Well done! :+1:
