### ISSUE TITLE
Staff/renew contract: nếu contract type đã bị deactive thì không cho gia hạn. Hiện thông báo.

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#416]

**Comment by hydrangea8604** [comment]
@minhtridn2001 review dùm nha

**Comment by minhtridn2001** [comment]
OK hợp lý :+1: 
![image](https://cloud.githubusercontent.com/assets/12363317/9025722/35cc7316-393b-11e5-833c-b294f40a96c3.png)
