### ISSUE TITLE
Customer/renew contract: nếu contract type đã bị deactive thì không cho gia hạn. Hiện thông báo

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#417]

**Comment by phucnguyen60749** [comment]
@hydrangea8604  review nhe!

**Comment by hydrangea8604** [comment]
Tính năng thì ok nhưng giao diện thì xấu quá.
- [ ] Không sửa title của modal mà hiện thông báo ở phần modal-body
- [ ] Dùng alert thì không dùng well, cũng như ngược lại

Đoạn class dài như vầy
```
alert alert-block alert-error fade in well well-lg text-info alertRenew
```
để làm gì trong khi
```
alert alert-danger
```
đẹp hơn
- [ ] Sửa lại câu thông báo thành "Hiện tại, công ty đã ngừng cung cấp loại hợp đồng này, quý khách vui lòng liên hệ nhân viên để biết thêm chi tiết. Thành thật xin lỗi vì bất tiện này, mong quý khách thông cảm. Cảm ơn vì đã sử dụng dịch vụ của chúng tôi"
Câu thông báo chỉ cần ghi vừa đủ đọc là được

**Comment by trungdq88** [comment]
@phucnguyen60749 @hydrangea8604 nếu được thì anh ghi câu như thế này nha:

"Hiện tại công ty đã ngừng cung cấp loại hợp đồng quý khác đang sử dụng (XXX). Quý khách không thể gia hạn hợp đồng này. Vui lòng liên hệ nhân viên để biết thêm chi tiết."

**Comment by phucnguyen60749** [comment]
@trungdq88 vậy là sữa lại câu thông báo đung hok! nảy giao diện e đã confirm vs a roi!

**Comment by trungdq88** [comment]
Lúc này confirm ở mức độ dùng được, nhưng comment của anh Kha đưa ra giải pháp tốt hơn thì cũng nên thay đổi. Giờ anh sửa lại thành câu của em đi, với cái `alert`, `well` gì đó nữa. Anh @hydrangea8604 cũng vậy nha.

**Comment by phucnguyen60749** [comment]
vậy là đẹp hả! 
![untitled](https://cloud.githubusercontent.com/assets/12363394/9025342/34f5972a-392b-11e5-8794-9930ba08d2cf.png)

**Comment by hydrangea8604** [comment]
Ít ra thì đẹp hơn
![image](https://cloud.githubusercontent.com/assets/12366868/9025352/9641b7f2-392b-11e5-9297-bf1f69663417.png)

**Comment by phucnguyen60749** [comment]
chụp thì chụp cho hết
 - 
![untitled](https://cloud.githubusercontent.com/assets/12363394/9025354/cd22e30e-392b-11e5-8e71-0a630a4f6743.png)

**Comment by hydrangea8604** [comment]
Ok, dont' care

**Comment by trungdq88** [comment]
> vậy là đẹp hả! 
> ![untitled](https://cloud.githubusercontent.com/assets/12363394/9025342/34f5972a-392b-11e5-8794-9930ba08d2cf.png)

Như vậy nhìn ok. Nhưng message chưa đúng đó anh.

Mọi người làm việc hiệu quả giúp em.

**Comment by phucnguyen60749** [comment]
- đã là ko gia hạn được cần gì phải giữ lại title --> dài dòng!
- để nguyên cái filed đỏ nhìn như bug của hệ thống! để màu gì nhẹ hơn ko đc à!

**Comment by phucnguyen60749** [comment]
@trungdq88 đã sữa câu text! customer click  button "Gia hạn" --> (case lạo hợp đồng đã hủy) --> alert modal (title -- ko thể gia hạn ; text --> lí do)

**Comment by trungdq88** [comment]
Đã review.
