### ISSUE TITLE
Customer / Contract / yêu cầu bồi thường / punishment/accident: chỉ cho phép trong thời gian hết hạn 30 ngày

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#419]

**Comment by phucnguyen60749** [comment]
@hydrangea8604  review!

**Comment by hydrangea8604** [comment]
30 không phải fix cứng mà là lấy updateContractDueDate trong ConfigUtils. Con số được thiết lập tại __Thời gian thêm thông tin sau khi hủy hợp đồng__ ở admin/config

**Comment by phucnguyen60749** [comment]
@hydrangea8604  cái này nhớ là bữa thống nhất fix theo 30 ngày mà! 
 - Customer / Contract / yêu cầu bồi thường / punishment/accident: chỉ cho phép trong thời gian hết hạn 30 ngày (đã ghi rõ 30 kìa)

**Comment by hydrangea8604** [comment]
Cái BusinessRules sinh ra để làm gì mà fix theo 30 ngày? Nếu vậy thì chờ @trungdq88 confirm đi

**Comment by phucnguyen60749** [comment]
- BusinessRules  để làm gì thì ai chả bít! còn nếu là  fix theo  "Thời gian thêm thông tin sau khi hủy hợp đồng" thì phải thêm rule mới vì rõ ràng không đúng ngữ nghĩa! vì contract này là sau khi đã hết hạn!

**Comment by trungdq88** [comment]
> 30 không phải fix cứng mà là lấy updateContractDueDate trong ConfigUtils

Câu này đúng.

> thì phải thêm rule mới vì rõ ràng không đúng ngữ nghĩa!

Rule cũ sẽ đổi ý nghĩa thành "Thời gian thêm của hợp đồng đã hủy / hết hạn"

**Comment by phucnguyen60749** [comment]
@hydrangea8604  đã fix theo updateContractDueDate!

**Comment by hydrangea8604** [comment]
Ok, đã review
