### ISSUE TITLE
Printer app: exception khi in thẻ 2 lần.

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#420]

**Comment by trungdq88** [comment]
Anh @hydrangea8604  có thể ghi lại cách tái tạo lỗi được không.
Em thực hiện trên máy ảo theo trình tự sau thì không thấy lỗi:
- Tạo hợp đồng HD0001.
- In thẻ 111 vào hợp đồng HD0001.
- App thông báo in thẻ thành công, nhấn Back quay lại trang danh sách hợp đồng.
- Chọn lại hợp đồng HD0001.
- In thẻ 111 vào hợp đồng. App thông báo: không thể in thẻ, thẻ này đã tồn tại trong hệ thống.

**Comment by minhtridn2001** [comment]
@trungdq88 Anh nhớ là thế này:
- Tạo hợp đồng HD0002.
- In thẻ 111 (của hợp đồng HD0001) cho HD0002.
- App thông báo lỗi, nhấn back quay lại.
- In thẻ mới, app bị exception.
Em check thử nha. A ko có device bây giờ nên ko có test được.

**Comment by hydrangea8604** [comment]
Ừ, quá trình tạo lỗi đúng như @minhtridn2001 nói

**Comment by trungdq88** [comment]
Vẫn chưa tái tạo bug được. Ngày mai sẽ debug lại trên máy thật.

**Comment by trungdq88** [comment]
Đã fix.
