### ISSUE TITLE
Trang Customer không hiện nút accident trong khi compensation vẫn hiện.

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#421]
Anh Phúc xem code lại thử nha.

Thời điểm test: 11:42 AM - 02 Aug 2015
<img width="949" alt="screenshot 2015-08-02 11 36 50" src="https://cloud.githubusercontent.com/assets/4214509/9024754/9450ae46-390b-11e5-8241-b5b26cb7c350.png">
<img width="950" alt="screenshot 2015-08-02 11 36 45" src="https://cloud.githubusercontent.com/assets/4214509/9024756/a83c19d6-390b-11e5-9a9d-6eabd68d6dda.png">
<img width="959" alt="screenshot 2015-08-02 11 36 42" src="https://cloud.githubusercontent.com/assets/4214509/9024759/bcf79f9e-390b-11e5-81aa-36f9862d1258.png">

**Comment by phucnguyen60749** [comment]
@trungdq88 đã fix em pull lại là hết

**Comment by trungdq88** [comment]
Anh comment cái commit vào cho em với nha.

**Comment by phucnguyen60749** [comment]
tại nảy a phát hiện ra tr khi em gán bug! nên commit vào! 
submit <Customer> contract detail: Pending: không được yêu cầu bồi thường/accident/punishment. #415 (v2)

**Comment by trungdq88** [comment]
Done.
