### ISSUE TITLE
<Customer> gửi comensation: thêm link download biểu mẫu nhập bằng tay ở đầu trang

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#422]

**Comment by phucnguyen60749** [comment]
@hydrangea8604  review dum nhe

**Comment by hydrangea8604** [comment]
Biểu mẫu điền chỉ là một phần trong cái văn bản đó thôi, cụ thể nó là phần phụ lục số 4, đó chỉ là mẫu do bộ phát hành, các công ty bảo hiểm lấy về và thay đổi thông tin thành của công ty mình, cụ thể là logo.
Đây là của một công ty khác: http://baohiemtructuyen.com.vn/BsioData/san-pham/xe-co-gioi/thong-bao-ton-that-giay-yeu-cau-boi-thuong.doc
Không bảo phải làm kỹ càng, hoành tráng như người ta, chỉ cần làm sao nhìn vào người ta biết không phải để y chang Luật là được, hoặc ít nhất cũng phải xóa mấy cái phụ lục không cần thiết.
Ghi chú rõ cho người dùng biết, nếu tải file về, điền và nộp cho công ty thì không cần phải điền trên web.

**Comment by trungdq88** [comment]
Anh thêm tên công ty + logo vào và bỏ các phần phụ lục là được nhé.

**Comment by phucnguyen60749** [comment]
- đã thêm tên công ty + logo! bỏ phụ lục! @hydrangea8604 review lại nhé!

**Comment by hydrangea8604** [comment]
Đã review
