### ISSUE TITLE
Checker app: Thời hạn từ: format lại ngày tháng, bỏ bớt một số thông tin không cần thiết.

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#425]

**Comment by trungdq88** [comment]
Review nha anh Phúc.

**Comment by phucnguyen60749** [comment]
- đã review ok! 
- thông tin bây giờ chỉ còn: chủ xe, địa chỉ, điện thoại, biển số xe, số khung, số máy, loại xe, thời hạn từ, mã thẻ
