### ISSUE TITLE
Notification: show old notifications.

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#428]

**Comment by trungdq88** [comment]
Review nha anh Phúc.

**Comment by phucnguyen60749** [comment]
@review ok :+1:  ! góp ý thêm 
 -  khi click vào "xem thông báo" thì active link "chưa đọc" hoặc "đã đọc"
 -  có thể thêm con số hiện bao nhiêu tin đã đọc hay bao nhiêu tin chưa đọc thì sẽ trực quan hơn!
![untitled](https://cloud.githubusercontent.com/assets/12363394/9066236/9957d0c6-3b00-11e5-909f-e68baf53f537.png)

**Comment by trungdq88** [comment]
Anh Phúc review tiếp nhé.

**Comment by phucnguyen60749** [comment]
done!
