### ISSUE TITLE
<Customer> lỗi hiển thị khi create new compensation 

### ISSUE THREAD

**Issue by phucnguyen60749** [trungdq88/insurance-card#430]
![untitled](https://cloud.githubusercontent.com/assets/12363394/9050635/05a44688-3a7a-11e5-942c-bbc5c6fc31e4.png)

**Comment by phucnguyen60749** [comment]
@minhtridn2001 review please! :8ball:

**Comment by minhtridn2001** [comment]
@@ Nhìn mãi mới ra cái bug của Phúc. Lần sau comment detail giúp t với nha :D
