### ISSUE TITLE
Report 6 - Public pages / Admin pages

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#431]

**Comment by minhtridn2001** [comment]
Review giúp mình nhé cậu :love_hotel:

**Comment by hydrangea8604** [comment]
Phần admin thì ok rồi, nhưng phần public thì nên bổ sung cả những trang sau khi nhấn nút "Tạo hợp đồng và thanh toán" nữa Trí ơi, như trang báo tạo hợp đồng thành công, trang thanh toán PayPal.

**Comment by minhtridn2001** [comment]
Tớ thêm rồi nha ;) :snowman:

**Comment by hydrangea8604** [comment]
Ok, đã review :heavy_check_mark:
