### ISSUE TITLE
<Staff> Contract: bỏ đơn vị, format ngày tháng

### ISSUE THREAD

**Issue by hydrangea8604** [trungdq88/insurance-card#437]
#### Create, edit
- [x] "Dung tích": cc
- [x] "Năm sản xuất": max = current year

#### Preview
- [x] Format example: 12/07/2015 lúc 00:00:00 thành ngày 12 tháng 07 năm 2015

**Comment by hydrangea8604** [comment]
@trungdq88 review dùm nha Trung

**Comment by trungdq88** [comment]
Done :white_check_mark:
