### ISSUE TITLE
Scheduler: hợp đồng sắp hết hạn: gửi 2 notifications

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#439]

**Comment by minhtridn2001** [comment]
Cái này là do mình chỉnh thời gian bỏ ngày nhiều quá nên nó thông báo lần 1 và lần 2 cùng 1 lúc luôn :D A thấy ko phải bug đâu.

**Comment by trungdq88** [comment]
Oh vậy hả, vậy chỉ cần chỉnh lại thời gian từ 15 ngày đến 7 ngày thì chắc không bị nữa nhỉ.

**Comment by trungdq88** [comment]
#459
