### ISSUE TITLE
Staff/new card request: Cần confirm lại thứ tự hiển thị ở danh sách yêu cầu thẻ mới

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#440]
Thứ tự đúng phải là:
- Ưu tiên 1: Yêu cầu chưa được giải quyết xếp lên trước.
- Ưu tiên 2: Yêu cầu tạo trước xếp lên trước.

Anh @hydrangea8604 giúp em confirm cái này nhé.

**Comment by hydrangea8604** [comment]
:white_check_mark:  Đã confirm, hiển thị đúng như thứ tự ưu tiên
