### ISSUE TITLE
Kiểm tra lại luật vấn đề: xe của anh A, bảo hiểm của anh A, anh B mượn đi và gây tai nạn, bồi thường cho ai?

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#444]

**Comment by trungdq88** [comment]
Câu này trả lời sao anh @hydrangea8604 nhỉ?

**Comment by hydrangea8604** [comment]
Câu này a đọc luật thì không có mô tả tới trường hợp cụ thể như thế này. Google cũng toàn là câu trả lời không có tính xác thực.
http://vnexpress.net/tin-tuc/oto-xe-may/tu-van/nguoi-khac-muon-xe-gay-tai-nan-chu-xe-co-bi-lien-doi-3144314.html
http://vnexpress.net/tin-tuc/oto-xe-may/dien-dan/ban-muon-xe-gay-tai-nan-chu-xe-co-phai-boi-thuong-3223375.html
