### ISSUE TITLE
Kiểm tra luật: Luật có quy định loại hợp đồng bắt buộc gồm những hợp đồng nào? Có bắt buộc mức giá hay không?

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#445]

**Comment by hydrangea8604** [comment]
Điểm 14.1, Khoản 14, Mục II
> Phải bán bảo hiểm bắt buộc trách nhiệm dân sự của chủ xe cơ giới theo đúng Quy tắc, biểu phí và mức trách nhiệm bảo hiểm theo quy định tại Thông tư này

Phụ lục 1: file TT151BTC-PL1.doc 98f2acb36c8ada198a820a906fb88f9a5eabc4e7

**Comment by hydrangea8604** [comment]
Khoản 3, Điều 6, Mục II
> Ngoài việc tham gia hợp đồng bảo hiểm bắt buộc trách nhiệm dân sự, chủ xe cơ giới có thể thoả thuận với doanh nghiệp bảo hiểm để tham gia hợp đồng bảo hiểm tự nguyện.

**Comment by trungdq88** [comment]
Done :+1:
