### ISSUE TITLE
Cho phép đăng ký hợp đồng trùng biển số với xe có hợp đồng hết hạn

### ISSUE THREAD

**Issue by minhtridn2001** [trungdq88/insurance-card#448]
- [x] Cho phép đăng ký hợp đồng trùng biển số với xe có hợp đồng hết hạn.

Những hợp đồng hết hạn có biển số xe trùng với hợp đồng đang có hiệu lực thì không cho gia hạn:
- [x] Renew contract by staff.
- [x] Renew contract by customer.

**Comment by minhtridn2001** [comment]
Review giúp nha Kha!

**Comment by hydrangea8604** [comment]
Phần staff thì ok rồi, nhưng phần customer bỏ link gắn với mã hợp đồng trên trang message đi, nếu hợp đồng của khách hàng khác click vào ra 404 đó.

T đề nghị cầu thông báo nên như thế này
> Không thể gia hạn, hiện tại hợp đồng HDxxxx đang có hiệu lực với biển số này. Vui lòng liên hệ nhân viên để biết thêm chi tiết.

**Comment by minhtridn2001** [comment]
OK Đã sửa :baby:

**Comment by trungdq88** [comment]
Cái này sao rồi nhỉ? @minhtridn2001 @hydrangea8604

**Comment by hydrangea8604** [comment]
Đã review :white_check_mark:
