### ISSUE TITLE
Các Use case spec cần sửa sau review 13 Aug

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#452]
Mã | Lý do sửa | Đã sửa
-----|---------------|-----------
CP01 | Chỉnh lại preconditions
CP02 | use case có relationship với verify card
CP02 | Business rule: định dạng cấu trúc hình
PS01 | Business rule: search theo tiêu chí gì, cá tình huống xử lý
PS02 | Business rule: viết quá sơ sài
PS03 | Bổ sung business rule.

**Comment by trungdq88** [comment]
CP01:
- Precondition: làm gì có staff ở đây nhỉ.
![image](https://cloud.githubusercontent.com/assets/4214509/9256093/c3e21f9a-4217-11e5-8386-29ca5197f8ae.png)
- System response: kiểm tra lại các field, mấy field này ghi sai so với app điện thoại hiện tại (có thể bật máy cái hình trong doc ra nhìn hoặc bật app trên máy ảo).
- Business rule: ghi rõ các trường hợp nào thì trả về kết quả nào (giống trong slide đọc lúc sáng).

CP02:
- Chỗ nhập thông tin: description bây giờ không required nữa.

**Comment by minhtridn2001** [comment]
Đã sửa theo review của Trung

**Comment by phucnguyen60749** [comment]
@trungdq88 review dùm nhé!
