### ISSUE TITLE
Sequence diagram: thêm các dấu destroy cho các thực thể

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#456]
Hướng dẫn: chỗ nào có thực thể (dấu 2 chấm ở đầu) thì thêm dấu destroy (dấu X trong staruml) ở cuối timeline.

Lưu các file sequence mới dạng file hình vào 1 thư mục **Sequence diagram** giúp em.

 Ví dụ:

<img width="349" alt="screenshot 2015-08-13 21 55 57" src="https://cloud.githubusercontent.com/assets/4214509/9253105/44271c3a-4206-11e5-8a5f-102260560592.png">

**Comment by trungdq88** [comment]
Mọi người chuyển hết các file sequence để anh Kha sửa cái này nhé.

**Comment by trungdq88** [comment]
Có thể làm xong trước 10h sáng mai (thứ 6, Aug 14) không anh?

**Comment by hydrangea8604** [comment]
@minhtridn2001 @phucnguyen60749 gởi file UML để thêm destroy nha

**Comment by minhtridn2001** [comment]
Confirm lại là file UML tối qua t gửi Kha đó nha.

**Comment by hydrangea8604** [comment]
Đã thêm destroy vào create contract by guest, paypal không cần destroy

**Comment by minhtridn2001** [comment]
Thanks Kha

**Comment by hydrangea8604** [comment]
@phucnguyen60749 Làm xong commit vào đây luôn nha

**Comment by phucnguyen60749** [comment]
@hydrangea8604  done! à mà mấy cái của kha nhớ cắt ngắn khi đã destroy!
