### ISSUE TITLE
State diagram thiếu trường hợp thanh toán rồi nhưng chưa đến ngày start

### ISSUE THREAD

**Issue by minhtridn2001** [trungdq88/insurance-card#458]
A vừa mới phát hiện ra TH này nè Trung
![image](https://cloud.githubusercontent.com/assets/12363317/9265924/817571e6-4264-11e5-8f1f-bd1ee8b074b4.png)

**Comment by trungdq88** [comment]
![image](https://cloud.githubusercontent.com/assets/4214509/9269250/e10acb6a-4291-11e5-9f51-084880d16432.png)
