### ISSUE TITLE
Fix scheduler delay.

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#459]
Solition: fake email: wont send

**Comment by trungdq88** [comment]
Anh @phucnguyen60749 kiểm tra lại xem cái scheduler có còn bị delay không nhé. Trung bình là phải 10s sau khi đổi giờ hệ thống thì sẽ phải có notification và email (đồng thời đổi luôn trạng thái hợp đồng).

**Comment by minhtridn2001** [comment]
OK! Đã bỏ qua những email @test.vn

**Comment by trungdq88** [comment]
> OK! Đã bỏ qua những email @test.vn

Quan trọng là scheduler nó có còn bị delay không anh? @minhtridn2001

**Comment by minhtridn2001** [comment]
Không em. Ko phải gửi nhiều email nữa nên nhanh hơn hẳn :D Nếu có bị delay thì là do phải gửi thông báo đến những email có thật khác.
