### ISSUE TITLE
<Customer> Thanh toán gia hạn hợp đồng

### ISSUE THREAD

**Issue by minhtridn2001** [trungdq88/insurance-card#461]
Phúc xem lại xem trên máy Phúc có bị lỗi font này ko nhé.
![image](https://cloud.githubusercontent.com/assets/12363317/9289349/91ab57dc-4396-11e5-8402-1fc0fe7c34aa.png)

**Comment by phucnguyen60749** [comment]
@minhtridn2001  tri xem lai fix cau hinh tren tomcat chua

**Comment by minhtridn2001** [comment]
OK!
