### ISSUE TITLE
Thông tin hợp đồng: chỉnh sửa thông tin hiển thị

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#464]
#### Staff
- [ ] Hợp đồng Pending: Ẩn ngày bắt đầu hợp đồng và ngày hết hạn hợp đồng, thêm thông tin chỉ hợp đồng chưa thanh toán.
- [ ] Ghi thêm thông tin là đã gia hạn bao nhiêu lần, ngày cuối cùng gia hạn là ngày nào.

#### Customer
- [ ] Hợp đồng Pending: Ẩn ngày bắt đầu hợp đồng và ngày hết hạn hợp đồng, thêm thông tin chỉ hợp đồng chưa thanh toán.
- [ ] Ghi thêm thông tin là đã gia hạn bao nhiêu lần, ngày cuối cùng gia hạn là ngày nào.

**Comment by minhtridn2001** [comment]
Done, review pls.

**Comment by hydrangea8604** [comment]
ok
