### ISSUE TITLE
Khi có yêu cầu huỷ từ KH: hiện lý do huỷ, thêm nút "Đồng ý huỷ".

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/insurance-card#63]

**Comment by hydrangea8604** [comment]
Khi có yêu cầu hủy, staff đồng ý thì chọn Hủy hợp đồng được không? Nếu có ghi chú gì thì viết vào đó luôn. Tạo ra thêm 1 nút nữa cũng là hiện cái modal hay ô nhập ghi chú thôi.

**Comment by trungdq88** [comment]
Vẫn tạo nút "Đồng ý huỷ" click vào sẽ mở ra modal của nút "Huỷ hợp đồng". Disable ô "Lý do huỷ" đi.
